### ISSUE TITLE
UdpSocket not implemented

### ISSUE THREAD

**Issue by patrick-scho** [HaxeFoundation/hashlink#103]
Even though it says on https://api.haxe.org/sys/net/UdpSocket.html that hl is supported it is not available. On the hashlink website it says that it is fully compatible with the Haxe specification, does that not include the sys API?

**Comment by Justinfront** [comment]
You can view the current sys support:
https://github.com/HaxeFoundation/haxe/tree/development/std/hl/_std/sys
I think that 'sys' support has been added after the initial launch of HashLink slowly as the target matures, and pull requests are no doubt welcome.

**Comment by ncannasse** [comment]
Right, the low level C was written but I didn't wrote the Haxe bindings,
this is now done here
https://github.com/HaxeFoundation/haxe/commit/ff5753a9e2282132fa39982c208057ce78bdd880
