### ISSUE TITLE
FMT: jpg/png metadata?

### ISSUE THREAD

**Issue by shakesoda** [HaxeFoundation/hashlink#113]
decoding jpg/png seems to require that I know the image size beforehand, but there don't seem to be any functions for getting that info from the raw buffer that I can find.

I'm currently decoding like this:

```
var png = read("foo.png");
var w = 1024;
var h = 512;
var c = 3;
var data = new hl.Bytes(w*h*c);
if (hl.Format.decodePNG(png, png.length, data, w, h, 0, hl.Format.PixelFormat.RGB, 0)) {
	// ...
}
```

is there a way to get the w/h/channel info without implementing my own metadata parsing?

also, a regular build on linux/ubuntu lts gives me a busted build with no png support, is this expected?

edit: if I use the format lib it looks like I can decode png meta (and all kinds of other stuff I don't need), but not jpg

**Comment by ncannasse** [comment]
That's a bit outside of the scope of the format library, although we could have helper functions for that, see https://github.com/HeapsIO/heaps/blob/master/hxd/res/Image.hx#L48 for example.
