### ISSUE TITLE
Is it possible to run hashlink in non JIT mode?

### ISSUE THREAD

**Issue by jagt** [HaxeFoundation/hashlink#118]
Hi,

I've found hashlink very cool and I'm wondering is interpreted mode execution on the development roadmap. If this is implemented then it can be a really cool alternative to lua for embedding into games on iOS.

Thanks for your great works!

**Comment by ncannasse** [comment]
There is an experimental interpreter that I wrote to validate and test the compiler here:
https://github.com/HaxeFoundation/haxe/blob/development/src/generators/hlinterp.ml
It should be rewritten in pure C in order to gain extra efficiency, but I have no plans to do that for now.

**Comment by jagt** [comment]
@ncannasse  Thanks a lot for the info.
I've been a long time fan of haxe and openfl. Thanks a lot for you awesome works!
