### ISSUE TITLE
OSX - CMake OggVorbis Include Paths

### ISSUE THREAD

**Issue by thejustinwalsh** [HaxeFoundation/hashlink#127]
FindOggVorbis.cmake does not actually ever define `OGGVORBIS_INCLUDE_DIR` instead it defines `VORBIS_INCLUDE_DIR` and `OGG_INCLUDE_DIR`.

The CMakeLists.txt for fmt `libs/fmt/CMakeLists.txt` uses `OGGVORBIS_INCLUDE_DIR` when searching for vorbis includes. Changing this to `VORBIS_INCLUDE_DIR` allows cmake to actually find the correct directory.

Without this change I am unable to compile on my Mac High Sierra install with dependencies installed with homebrew.

**Comment by andyli** [comment]
Indeed. Thanks for the report!
