### ISSUE TITLE
OSX - CMake libpng Path Collision

### ISSUE THREAD

**Issue by thejustinwalsh** [HaxeFoundation/hashlink#128]
I have mono installed on my Mac, and cmake will try and use the version of libpng found there causing all kinds of problems. In order to solve this issue, I had to add `set(CMAKE_FIND_FRAMEWORK LAST)` before calling `find_package(PNG REQUIRED)`.

**Comment by andyli** [comment]
You can always use `PNG_DIR` pointing to your desired png installation's `PNGConfig.cmake`. See https://cmake.org/cmake/help/latest/command/find_package.html

And you don't have to modify the CMakeLists.txt file, just use `cmake -DPNG_DIR=path ..` or `cmake -DCMAKE_FIND_FRAMEWORK=LAST ..`.

**Comment by Justinfront** [comment]
Andy is it possible to get HashLink on travis I feel at the moment it's a windows only advanced version of Neko. I don't think these issues should be closed while that is still many peoples experiance.

**Comment by Justinfront** [comment]
Mono is a common installation for using haxe c# on mac, it would be less relevant if it was mono on pc.
I did not realize you had Travis setup to test HashLink make on mac that good news, will need to try Hashlink again soon but did not get that far last time.  Would the brew expert be able to setup HashLink do you think?
