### ISSUE TITLE
JIT Hot Reload

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hashlink#145]
Allow to reload JIT code when .hl gets modified when running `hl --hot-reload`

- start a thread that waits for change on the file
- if change, parse the module
- reorder / pad classes data to preserve current in-memory fields order
- JIT the new module
- patch all current objects prototypes to point to new JIT addresses
- patch the current JIT so each method is now a jmp to the new JIT (handle existing closures objects) --- only if the method type was not changed!
- patching the current stack to return to newest JIT requires pausing all threads and might create crashes/incorrect behaviors since we are not 100% sure if is a correct stack address and not some integers looking like it - especially in 64 bits

**Comment by ncannasse** [comment]
Here's the test sample I'm currently using to experiment with the feature:
```haxe

class Main {

	macro static function randomValue() {
		return macro $v{100000 + Std.random(1000)};
	}

	#if !macro

	@:hlNative("std","sys_check_reload")
	static function check_reload() return false;

	static function foo() {
		return randomValue();
	}

	static function main() {
		while( true ) {
			Sys.println(foo());
			Sys.sleep(0.1);
			Sys.command("haxe",["-hl","main.hl","-main","Main"]);
			if( check_reload() ) Sys.println("RELOADED");
		}
	}
	
	#end
	
}
```

**Comment by sonygod** [comment]
it's work in 1.9?  

can we do the same thing as `[here](https://fungos.github.io/blog/2017/11/20/cr.h-a-simple-c-hot-reload-header-only-library/)`?

we change code and compile it's hot reload

**Comment by ncannasse** [comment]
If works in some cases with 1.9, but I didn't finalized that yet.
You need to run the program with  `hl --hot-reload`

**Comment by sonygod** [comment]
great!

**Comment by User7711** [comment]
This is actually a very nice feature.! But it crashes when you add/remove fields (properties, methods). Is there anything I can do on my end as a Haxe user to not make it crash when the fields change?

**Comment by darmie** [comment]
Status of this feature? Would be really nice for UI development with Haxe for native Apps

**Comment by ncannasse** [comment]
I've been working more on hot reload and documented it there : https://github.com/HaxeFoundation/hashlink/wiki/Hot-Reload
