### ISSUE TITLE
Missing Libraries in 1.5 Binary Release

### ISSUE THREAD

**Issue by Doppp** [HaxeFoundation/hashlink#146]
Was trying to run the Heaps Video sample but got this error: `FATAL ERROR : Failed to load library video.hdll`. Turns out `video.hdll` was not found in the [HashLink 1.5 release](https://github.com/HaxeFoundation/hashlink/releases/tag/1.5).

The `mesa` library is also missing.

**Comment by ncannasse** [comment]
Yes video.hdll is not yet shipped with binaries as it is yet unclear what are the licensing issues with it, see https://www.ffmpeg.org/legal.html

**Comment by Doppp** [comment]
@ncannasse Ah okay. But what happens if I want to ship HashLink compiled games? Like I see `mesa.hdll` and `video.hdll` in the Northgard directory. Was Northgard compiled in HL and then to C++?

**Comment by ncannasse** [comment]
Oh that's a mistake, they are compiled here but are not used, I guess I did copy *.hdll :)

**Comment by Krypt0n** [comment]
so how to use it then?

**Comment by ncannasse** [comment]
@Krypt0n you need to compile the library by had from sources here: https://github.com/HaxeFoundation/hashlink/tree/master/libs/video

**Comment by jackwlee01** [comment]
Are there any instructions on how to compile this on Mac?

**Comment by Aurel300** [comment]
@jackwlee01 If you have CMake installed it should be the usual `mkdir build; cd build; cmake ..; make` ?

**Comment by gsouf** [comment]
I have tried the instructions mentioned above on linux `mkdir build; cd build; cmake ..; make`  but the final `make` produces no output in the terminal and seems to produce no files (no `video.hdll`).

Is there anything I missing?

Sorry if that's a dumb question - I just have no experience and no idea what I'm doing with make tools and I have no clues where to find an answer.
