### ISSUE TITLE
Unable to setup and use hlsdl haxelib.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/hashlink#15]
It is not clear how to setup hlsdl on mac.
.src/module.c(207) : FATAL ERROR : Failed to load library ui.hdll
when trying to import sdl classes is this currently possible? Hello World works fine.

**Comment by ncannasse** [comment]
ATM ui.hdll is only available on Windows.

**Comment by joshbabb** [comment]
OK, I am on Windows but it is still a bit unclear even how to import hlsdl and use it.  Is there any documentation or are there any examples?

**Comment by ncannasse** [comment]
Go to the hl/lib/sdl directory and run `haxelib dev hlsdl .` You also need `ui.hdll` and `sdl.hdll` as well as `SDL2.dll` accessible for your application.
