### ISSUE TITLE
Actuate crash in HL output (works in other targets)

### ISSUE THREAD

**Issue by hoseyjoe** [HaxeFoundation/hashlink#153]
I am using 
haxe4 rc3
HL 1.5
actuate 1.8.7
I attempted to test HL 1.6 on git but ran into issue (couldnt load sdl.hdll). This was in conjunction with a haxe nightly.

See attached project. Other tweens work but this line 
Actuate.timer(1).onComplete (test);
causes
`Main.hx:4: Hello, world!
motion/actuators/SimpleActuator.hx:500: #motion._Actuate.TweenTimer
Uncaught exception: Can't cast (void ()) to #Main
Called from @0x940470
Called from $Reflect.callMethod(C:\sdks\haxe4\haxe\std/hl/_std/Reflect.hx:85)
Called from motion.actuators.GenericActuator.complete(motion/actuators/GenericActuator.hx:155)
Called from motion.actuators.SimpleActuator.update(motion/actuators/SimpleActuator.hx:501)
Called from motion.actuators.$SimpleActuator.stage_onEnterFrame(motion/actuators/SimpleActuator.hx:579)
Called from fun$329(C:\sdks\haxe4\haxe\std/haxe/Timer.hx:74)
Called from haxe.$MainLoop.tick(C:\sdks\haxe4\haxe\std/haxe/MainLoop.hx:166)
Called from haxe.$EntryPoint.processEvents(C:\sdks\haxe4\haxe\std/haxe/EntryPoint.hx:106)
Called from haxe.$EntryPoint.run(C:\sdks\haxe4\haxe\std/haxe/EntryPoint.hx:135)
Called from fun$468(?:1)`

[HeapsBug.zip](https://github.com/HaxeFoundation/hashlink/files/2010638/HeapsBug.zip)

**Comment by ncannasse** [comment]
Could try by replacing this file in haxe/std/hl/_std ? https://github.com/HaxeFoundation/haxe/blob/development/std/hl/_std/Reflect.hx

**Comment by hoseyjoe** [comment]
It does not appear to fix the issue. 
I did have to comment out line 76 in linked Reflect.hx but I dont believe that to be relevant. (makeClosure not available in api...which if you add isnt available in HL 1.5)

**Comment by ncannasse** [comment]
I'm having a different error now on HL 1.6
I'll try to add a corresponding unit test in https://github.com/HaxeFoundation/haxe/issues/7106

**Comment by jgranick** [comment]
I just fixed the issue on HashLink 1.6 and Haxe 4 preview 4 using this change

https://github.com/jgranick/actuate/commit/fdcf7b036104baafdb639893c1458e2e364d4ee4

Perhaps this will help with finding a fix

**Comment by ncannasse** [comment]
Related issue is https://github.com/HaxeFoundation/haxe/issues/7106, closing for now.
