### ISSUE TITLE
invalid signature generation

### ISSUE THREAD

**Issue by cougaro** [HaxeFoundation/hashlink#155]
Hi everyone, 

I'm using hashlink 1.5.0 and Haxe 4.0.0 (build @ 3018ab1)

In my Haxe class I declared the native method: 

`private static function victrixSetVertexBuffer ( vertices : Array<Float> ) : Void {};`

When I execute hashlink I get this error:
 
 FATAL ERROR : Invalid signature for function victrix@victrix_set_vertex_buffer : **POBi__v** required but POBf__v found in hdll

Why the `Array<Float>` is interepreted as _I32 and not _F32 ?

**Comment by ncannasse** [comment]
You shouldn't pass an Haxe Array for your C primitives. Use either hl.NativeArray for an Array of objects or hl.Bytes for an Array of floats. You can use hl.Bytes.getArray to get the bytes from an Array, and you will have to pass the length separately.
