### ISSUE TITLE
type not found linux mint

### ISSUE THREAD

**Issue by Criaan** [HaxeFoundation/hashlink#158]
Hy tested hashlink on linux mint. When compile my program i get the following error /usr/share/haxe/std/hl/F32.hx:24: characters 14-20 : Type not found : Single
i checked that directory that file is there. am i missing someting.

**Comment by ncannasse** [comment]
You need to use Haxe 4.0-RC3+ to compile using Haxe/HL. Seems like your Haxe standard library is not up to date (or use an older Haxe version?)
