### ISSUE TITLE
Failed to load library in Linux Mint 18.2 - HL 1.6

### ISSUE THREAD

**Issue by josuigoa** [HaxeFoundation/hashlink#160]
Hi!
I've downloaded the latest HL release for Linux (I'm using Mint 18.2 64bit) and my Haxe version is 4.0.0-preview.4. When I execute ```./hl main.hl``` it tells me ```src/module.c(268) : FATAL ERROR : Failed to load library fmt.hdll```. I've also tried building from source but it can't get it working.

**Comment by andyli** [comment]
Put the hdll files in `/usr/lib`, or use [`LD_LIBRARY_PATH`](http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html#AEN80).

**Comment by josuigoa** [comment]
I've put them in ```/usr/lib``` and I'm getting this

![image](https://user-images.githubusercontent.com/3088505/41584781-753f0572-73a8-11e8-876c-c05c2b912553.png)

I've tried putting in ```/usr/local/lib``` I get the ```fmt.hdll not found```

**Comment by ncannasse** [comment]
Seems like it goes further with /usr/lib, so there must be another missing dependency in `ssl.hdll`, try to run `ldd /usr/lib/ssl.hdll` to check what might be missing.

**Comment by andyli** [comment]
Yeah, I can see that ssl.hdll was linked with mbedtls dynamically:
```
$ ldd ssl.hdll 
	linux-vdso.so.1 =>  (0x00007ffcad3d0000)
	libhl.so (0x00007f4c81178000)
	libmbedtls.so.10 => /usr/lib/x86_64-linux-gnu/libmbedtls.so.10 (0x00007f4c80f51000)
	libmbedx509.so.0 => /usr/lib/x86_64-linux-gnu/libmbedx509.so.0 (0x00007f4c80d3d000)
	libmbedcrypto.so.1 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4c80b20000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4c80756000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4c8044d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4c815e7000)
	libmbedcrypto.so.0 => /usr/lib/x86_64-linux-gnu/libmbedcrypto.so.0 (0x00007f4c801f8000)
```

@ncannasse Why not just publish only win binaries like you did for hl 1.4? Mac and Linux binaries need some extra care to make sure these things are done right.

**Comment by ncannasse** [comment]
@andyli we could link mbedtls statically - if possible with the linux package. I thought having binaries would help some people

**Comment by andyli** [comment]
Yeah, so either check carefully everything (except libc) is statically linked, or just don't provide binaries.
