### ISSUE TITLE
failed to load gl_uniform_matrix4fv

### ISSUE THREAD

**Issue by Justinfront** [HaxeFoundation/hashlink#162]
99% close to having full HashLink working...

/hashlink-1.5/src/module.c(290) : FATAL ERROR : Failed to load function sdl@gl_uniform_matrix4fv

Not sure if it's relevant but running cmake in sdl folder it gets upset with 
set_as_hdll(sdl)

hello world runs fine but heaps test not.

Kind of sad HashLink is so hard to get running on mac, I presume it varies between mac.

I am not sure if this link was useful but think it was.
http://ethan.tira-thompson.com/Mac_OS_X_Ports.html

**Comment by ncannasse** [comment]
If you can't load it it means that your sdl.hdll is not up to date. Seems like you're running HashLink 1.5 whereas you need HashLink 1.6

Compiling HashLink on OSX is actually quite simple using `brew` , see instructions in README.md
