### ISSUE TITLE
Just 'hl' naming not optimal 

### ISSUE THREAD

**Issue by tong** [HaxeFoundation/hashlink#168]
Using just 'hl' as name for the vm binary, the header files and libhl.so isn't a good practice imho.
It's hard to search/find and pretty confusing since already used as bytecode file extension.

How about using the full 'hashlink' name ?
Someone could create an alias or link if that is prefered.

**Comment by ncannasse** [comment]
I don't see a real problem with `hl` since it's a not an already used unix utility.

**Comment by ClosetMonkey** [comment]
I agree that it's odd for an executable and a related file extension to be the same but I also see a certain symmetry to it as well. Confusing yes, but pretty easy to get past imo
