### ISSUE TITLE
ibhl.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#173]
hl: error while loading shared libraries: libhl.so: cannot open shared object file: No such file or directory

sys: Ubuntu 18.04
hl :git version
how to fixed that?

**Comment by ncannasse** [comment]
Try  "sudo make INSTALL_DIR=/usr install" , it will install in /usr/bin and /usr/lib instead of /usr/local/

**Comment by jboadas** [comment]
Didn't worked for me, instead of the command line parameter, edited the Makefile with:
`PREFIX ?= /usr`
And after that
`sudo make install`
and it works.
