### ISSUE TITLE
Performance of typedefs

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hashlink#178]
This benchmark shows performances that could be significantly improved in the following cases:

* [ ] optional fields (oi and of)
* [ ] access to `sub` object
* [x] access to `f` after json
* [x] access to arrays after json

```haxe
typedef Def = {
	var i : Int;
	var f : Float;
	@:optional var oi : Int;
	@:optional var of : Float;
	var ai : Array<Int>;
	var af : Array<Float>;
	var str : String;
}
typedef Obj = {>Def,
	var sub : Def;
}

class Main {

	static inline var K = 1000000;
	static var G = 0.;

	static macro function e( expr ) {
		var str = haxe.macro.ExprTools.toString(expr);
		return macro {
			var t0 = haxe.Timer.stamp();
			var tot = 0.;
			for( i in 0...K )
				tot += $expr;
			var dt = haxe.Timer.stamp() - t0;
			G += tot;
			Sys.println($v{str} + ": " + Std.int(dt*1000)/10);
		};
	}

	#if !macro

	static function bench( o : Obj ) {
		e(o.i);
		e(o.f);
		e(o.ai[0]);
		e(o.af[0]);
		e(o.oi);
		e(o.of);
		e(o.str.length);
		e(o.sub.i);
		e(o.sub.f);
		e(o.sub.ai[0]);
		e(o.sub.af[0]);
		e(o.sub.oi);
		e(o.sub.of);
		e(o.sub.str.length);
	}

	static function main() {
		var o : Obj = {
			i : 1,
			f : 1.0,
			oi : 1,
			of : 1.0,
			ai : [1],
			af : [1.0],
			str : "1",
			sub : {
				i : 1,
				f : 1.0,
				oi : 1,
				of : 1.0,
				ai : [1],
				af : [1.0],
				str : "1",
			}
		};
		bench(o);
		Sys.println("");
		trace("JSON:");
		bench(haxe.Json.parse(haxe.Json.stringify(o)));
	}

	#end


}
```

**Comment by ncannasse** [comment]
@Simn when do we have this benchmark thing to have nice graphs for all platforms ? :D

**Comment by Simn** [comment]
We could look into it if you find a server to run it on.

**Comment by ncannasse** [comment]
You can get it in the following hour when it become necessary, but I think we need to build and test the service first on a local computer so we don't rent it for months until we get it ready. That's post Haxe 4 anyway ;)

**Comment by Simn** [comment]
Maybe @ousado can help, he made some neat benchmarks for field/enum/array access a while back. I can write the actual benchmarks but I need some support to set up the framework around them.

**Comment by ncannasse** [comment]
13d0f63d45cef0e9ddc16c0e74534d79f4f04403 fixes most of these. Now the funny part is that the literal object is slower than the one that goes through json, I'll open an Haxe issue for that.

**Comment by ncannasse** [comment]
Everything is good with 903c46cdc0520e7c35e2f7133e5c3efd518b0f6e, thanks @Simn
