### ISSUE TITLE
creating a big array hangs on linux

### ISSUE THREAD

**Issue by AdrianV** [HaxeFoundation/hashlink#18]
the following code runs fine under hl/windows but hangs on linux hlc or crashes hl/jit

I am on Ubuntu 16.04 and compiled with gcc V 6.2.0 or gcc 5.4.1

```haxe
import haxe.Timer;



class BugArray {
	inline static var LOOP = 1000;
	inline static var LOOP2 = LOOP * LOOP;
	inline static var LOOP3 = LOOP2 * LOOP;

	public static function benchmark(dg: Void->Void, ? msg: String) {
		if (msg != null) trace('$msg :');
		var dt = #if (js || interp) haxe.Timer.stamp(); #else Sys.cpuTime(); #end
		dg();
		trace(#if (js || interp) haxe.Timer.stamp() #else Sys.cpuTime() #end - dt);
	}


	static function arrayTest1() {
		var ar: Array<Int> = new Array();
		ar[LOOP2] = 0;
		for (i in 0...LOOP2) {
			ar[i] = i;
		}
	}
	

    public static function main() {
        trace("start");
	benchmark(arrayTest1, "arrayTest1");	
        trace("done");
    }
}

```

the strange thing is, if I add another static function, than the code runs - sometimes and sometimes not - it depends on the combination of functions I add.

**Comment by ousado** [comment]
you can change the subject line using the 'Edit' button right next to it

**Comment by AdrianV** [comment]
thanks - sometimes I oversee the obvious :)

**Comment by ncannasse** [comment]
I can't reproduce on Ubuntu 14.04 / gcc 4.8.4 (tried in both 32 and 64 bits). Could you update + rebuild HL and try again?

**Comment by AdrianV** [comment]
I just pulled current HL and rebuild. Same hang on gcc 6.2 and 5.4.1. But I tried with gcc-4.8.5 and there it works. Seems to be code generation problem. Maybe variables on the stack and the gc

**Comment by AdrianV** [comment]
Sorry, I found the problem. I did a rebuild, but libhl.so was not copied to /usr/local/lib. So that was the problem.
