### ISSUE TITLE
hl.Int64 JIT support

### ISSUE THREAD

**Issue by Grabli66** [HaxeFoundation/hashlink#180]
```haxe
import hl.I64;

class Main {
    public static function main() {        
        var d:I64 = 1;
        trace(d);
    }
}
```

JIT ERROR 0 (jit.c line 3016)

HL/JIT 1.7.0 (c)2015-2018 Haxe Foundation
Windows 64-bit

**Comment by ncannasse** [comment]
Yes, native Int64 support is not yet complete

**Comment by onehundredfeet** [comment]
I'm running into quite a few instances where libraries I'm trying to integrate uses int64's natively. It would be awesome to have this finished off. I was looking at some of the missing parts, but I'm guessing it would be a lot faster for someone with more experience with the hashlink internals to do it.

If no one is interested, I'll take a crack at it.

**Comment by ncannasse** [comment]
Int64 support is fully complete now.

**Comment by onehundredfeet** [comment]
Great! Thanks @ncannasse
