### ISSUE TITLE
libhl.so: cannot open shared object file

### ISSUE THREAD

**Issue by briguyjm** [HaxeFoundation/hashlink#181]
Can't run the `hl` binary, get this error:

`hl: error while loading shared libraries: libhl.so: cannot open shared object file: No such file or directory`

Tried re-running the `sudo make install` command using this:
`sudo make INSTALL_DIR=/usr install` but the issue persists.

Fedora 28
hashlink-1.7 source code

**Comment by briguyjm** [comment]
`$ ldd hl`
`$ no such file or directory`

`$ ldd /usr/lib/libhl.so`

    linux-vdso.so.1 (0x00007ffd752be000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3d17859000)
    libm.so.6 => /lib64/libm.so.6 (0x00007f3d174c5000)
    libc.so.6 => /lib64/libc.so.6 (0x00007f3d17106000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f3d17cd4000)`

**Comment by ncannasse** [comment]
try ldd /usr/bin/hl,  or add rights so hl can access to libhl.so , it's possible that root does not give your user rights to it

**Comment by sonygod** [comment]
you have to copy *.so like this 

       cp -f /usr/local/lib64/libhl*  /lib64

**Comment by konsumer** [comment]
This may be unrelated, but I can run `hl`, but it can't find `libhl.so` or `.hdll` files, when I try to run a hashlink "hello world". I installed hashlink from source, on Ubuntu.

```
 ldd $(which hl)
        linux-vdso.so.1 (0x00007ffecef76000)
        libhl.so => not found
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3ffc959000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3ffc953000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3ffc931000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3ffc747000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3ffcafe000)

hl hello.hl
hl: error while loading shared libraries: libhl.so: cannot open shared object file: No such file or directory
```

` libhl.so => not found` seemed like this is the issue, and I watched what `sudo make instakll` did:

```
Linux==Darwin && make uninstall
make[1]: Entering directory '/home/konsumer/Downloads/hashlink-master'
rm -f /usr/local/bin/hl /usr/local/lib/libhl.so /usr/local/lib/*.hdll
rm -f /usr/local/include/hl.h /usr/local/include/hlc.h /usr/local/include/hlc_main.c
make[1]: Leaving directory '/home/konsumer/Downloads/hashlink-master'
mkdir -p /usr/local/bin
cp hl /usr/local/bin
mkdir -p /usr/local/lib
cp *.hdll /usr/local/lib
cp libhl.so /usr/local/lib
mkdir -p /usr/local/include
cp src/hl.h src/hlc.h src/hlc_main.c /usr/local/include
```

If I run from the hashlink source dir, it works (there is a libhl.so in it, along with `.hdll` files.)
I ran `sudo ldconfig` to update it to see so files in /usr/local/lib, and it would run, but now I get `src/module.c(360) : FATAL ERROR : Failed to load library fmt.hdll`. 

My /usr/local/lib looks like this:

```
fmt.hdll  libhl.so  mysql.hdll  node_modules  openal.hdll  python3.8  sdl.hdll  ssl.hdll  ui.hdll  uv.hdll
```

It seems like it's not finding the `.hdll` files, installed globally.

**Comment by konsumer** [comment]
For now, I can just use the binaries in a specific dir:

```
├── dist
│   ├── hello.hl
│   └── linux
│       ├── fmt.hdll
│       ├── hl
│       ├── libhl.so
│       ├── mysql.hdll
│       ├── openal.hdll
│       ├── sdl.hdll
│       ├── ssl.hdll
│       ├── ui.hdll
│       └── uv.hdll
├── hl.hxml
├── src
│   └── Main.hx
└── web.hxml
```

```
./dist/linux/hl dist/hello.hl
src/Main.hx:3: Hello World
```

**Comment by MSGhero** [comment]
If anyone else ends up here, @sonygod's solution worked for me, more or less. On a chromebook using Crostini, I had to copy from `/usr/local/lib/libhl.so` to `/lib`. The other solution does work, but that's annoying to have in every build directory.

**Comment by jordan-lapointe** [comment]
@MSGhero @sonygod Thank you; saved this n00b a lot of frustration. 

Also for anyone else landing here: see https://github.com/HaxeFoundation/hashlink/issues/173#issuecomment-414112361
