### ISSUE TITLE
[hxtelemetry] Failed to load function std@track_enable

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/hashlink#182]
I built hashlink from source (63e0e00574ce86e74b29dc95f82f4b0a46210ace) on macos.
Also installed hxtelemetry from github.
With `-lib hxtelemetry` the app compiles fine but when run I got the error:

`src/module.c(311) : FATAL ERROR : Failed to load function std@track_enable`

Any help is appreciated. Thanks.

**Comment by ncannasse** [comment]
You need to include track.c in compilation, I don't think it's currently done on Linux/Macos

**Comment by kevinresol** [comment]
works now, awesome.
