### ISSUE TITLE
[JUST CURIOUS] Using multiple .hl files in a project

### ISSUE THREAD

**Issue by darmie** [HaxeFoundation/hashlink#184]
So I am curious about the possibility of using multiple `.hl` bytecodes in a single project, something like using multiple `.jar` archives in a single Java project. 

I think writing `.hdll` libraries in C will be daunting for developers who don't code in C. I once thought of maybe generating `.hdll` libraries from Haxe code using macros, but I believe there should be a hack free alternative to doing this. 

If anyone can be kind enough to give suggestions on how to go about this, I would be glad.

**Comment by ncannasse** [comment]
Look at #179
