### ISSUE TITLE
hl/jit does not work on armv7 processor

### ISSUE THREAD

**Issue by Grabli66** [HaxeFoundation/hashlink#185]
I am compiled hashlink for raspberry pi 3 (armv7 32 bit). And then i am tried to launch simple program compiled to hashlink. But i got an error "Illegal instruction" on launch.
I am sure that's becasue of jit. It uses some instructions that armv7 can't handle.

**Comment by ncannasse** [comment]
Right, JIT only supports x86 and x86_64 so far. I have no plans to add ARM support right now, please use hashlink/C and native C compiler to get binaries.

**Comment by Grabli66** [comment]
Can i open feature request issue? Maybe you will deside to implement it in future?

**Comment by ncannasse** [comment]
It would be very hard to do so, and I don't much ARM devices allow JIT execution as part of their terms anyway.

**Comment by shakesoda** [comment]
Android and ARM Linux account for a pretty huge amount of devices... just
not iOS or Switch (afaik).

**Comment by ncannasse** [comment]
Yes, but you don't need JIT on these platforms, you can output HL/C code and directly compile it using native compilers, it will actually be faster than JIT become you get all the C compiler optimizations.
