### ISSUE TITLE
HL/C windows cross compilation problem on Linux

### ISSUE THREAD

**Issue by YRTV** [HaxeFoundation/hashlink#187]
`i686-w64-mingw32-gcc main.c -v -o main.exe -std=c11 -O3 -I./ -I./hl170win/include -L./hl170win -ldbghelp -llibhl -municode`
Where `hl170win` is hashlink from release page.
`./hl170win/include/hl.h:208:11: fatal error: Windows.h: No such file or directory` 
`./hl170win/include/hlc_main.c:31:11: fatal error: DbgHelp.h: No such file or directory`
Linux file system is case-sensitive. Headers names must be lowercase windows.h and dbghelp.h

**Comment by ncannasse** [comment]
The original headers as part of the Win32 SDK are correctly cased, and some windows file systems are case sensitive as well, so we would need to detect the usage of a cross compiler to include different headers, please submit a tested PR.
