### ISSUE TITLE
FATAL ERROR : Can't lock GC in hl_blocking section

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/hashlink#188]
When running the test cases of our haxelib [haxe-concurrent](https://travis-ci.org/vegardit/haxe-concurrent/) on Haxe4 with HL the process crashes with:
in HL1.6: `src\alloc.c(212) : FATAL ERROR : Can't lock GC in hl_blocking section`
in HL1.7: `src\alloc.c(213) : FATAL ERROR : Can't lock GC in hl_blocking section`

If I am running the test case that crashes isolated (without the other test cases) HL does not crash, so I cannot really pin point the issue any further, except that the test case involves using `hl.vm.Mutex.tryAcquire()`.

https://travis-ci.org/vegardit/haxe-concurrent/jobs/439284910
```
hx/doctest/DocTestRunner.hx:53: [INFO] **********************************************************
hx/doctest/DocTestRunner.hx:54: [INFO] Invoking [hx.concurrent.TestRunner#testRLock()]...
hx/doctest/DocTestRunner.hx:55: [INFO] **********************************************************
test/hx/concurrent/TestRunner.hx:218: [OK] assertFalse(false)
test/hx/concurrent/TestRunner.hx:219: [OK] assertFalse(false)
test/hx/concurrent/TestRunner.hx:220: [OK] assertFalse(false)
test/hx/concurrent/TestRunner.hx:221: [OK] assertEquals(1, 1)
test/hx/concurrent/TestRunner.hx:230: [OK] assertFalse(false)
test/hx/concurrent/TestRunner.hx:232: [OK] assertFalse(false)
test/hx/concurrent/TestRunner.hx:233: [OK] assertTrue(true)
test/hx/concurrent/TestRunner.hx:234: [OK] assertTrue(true)
test/hx/concurrent/TestRunner.hx:235: [OK] assertEquals(0, 0)
src/alloc.c(212) : FATAL ERROR : Can't lock GC in hl_blocking section
```

It fails here https://github.com/vegardit/haxe-concurrent/blob/master/test/hx/concurrent/TestRunner.hx#L237 where at the end `Mutex#tryAcquire()` is called.

**Comment by ncannasse** [comment]
Do you have some way to run the test from within gdb or another debugger ? Typically this must involve calling `hl_blocking(true)` (which does not occur in tryAcquire) while we haven't performed `hl_blocking(false)` yet. This is no supposed to happen.

**Comment by sebthom** [comment]
Here is a small code snippet that consistently triggers the crash on my machine (Win10, Haxe4+HL1.7):

```haxe
class Test {

    public static function main() {
       func1();
       func2();
    }

    static function func1() {
       var q1 = new hl.vm.Deque<String>();
    }

    static function func2() {
        hl.vm.Thread.create(function() {
            var q2 = new hl.vm.Deque<String>();
            while (true) {
                var fn = function() {
                    q2.pop(false);
                };
                fn();
            }
        });
        Sys.sleep(5);
    }
}
```

**Comment by ncannasse** [comment]
Thanks for the reproducible example
