### ISSUE TITLE
JIT ERROR -1 (jit.c line 1498)

### ISSUE THREAD

**Issue by kevinw** [HaxeFoundation/hashlink#189]
while using haxe --connect to connect to a running haxe compilation server, my project results in

```
haxe --connect 10001 game.hxml   && hl game.hl
JIT ERROR -1 (jit.c line 1498)
```

It happens on the *second* compilation. The first one succeeds.

The hxml and hx files are attached here: [jiterror.zip](https://github.com/HaxeFoundation/hashlink/files/2465308/jiterror.zip)

**Comment by ncannasse** [comment]
@Simn funny : second compilation gives indeed an HL error, but third one prints `D:\Projects\haxe\lib\ecx/git/src/ecx/types/TypeManager.hx:13: lines 13-40 : Missing function body`. Definitely something to do with macros/compiler cache.

**Comment by ncannasse** [comment]
PS: requires `haxelib git ecx git https://github.com/eliasku/ecx.git`

**Comment by ncannasse** [comment]
Using `-dce no` triggers Haxe compilation bug on second compilation

**Comment by ncannasse** [comment]
Compiling with `-D hl-check` gives `` Unresolved method haxe.rtti.Meta:getType(@2317)` so this is definitely a haxe compiler cache bug, moving it to https://github.com/haxeFoundation/haxe

**Comment by kevinw** [comment]
Great, thanks for following up!

**Comment by ncannasse** [comment]
I've opened another issue where it belongs, closing this one although not yet fixed.
