### ISSUE TITLE
HL pre-casting objects in unexpected ways

### ISSUE THREAD

**Issue by FireSlash** [HaxeFoundation/hashlink#191]
I don't know how else to explain this, so I've baked the repro down as thin as I can.

````haxe
import haxe.MainLoop.MainEvent;
import haxe.rtti.Meta;

class Main {
	static function main() {
		new Main();
	}
	public function new()
	{
		var classFields = Meta.getFields(Main);
		for(classFieldName in Reflect.fields(classFields)) 
		{
			// This is the line that is affected:
			var functionFields = Reflect.field(classFields, classFieldName);
			trace("Type of functionFields is: " + Type.typeof(functionFields) );
			for(functionFieldName in Reflect.fields(functionFields)) 
			{
				trace(functionFieldName);               
			}
			
			// Commenting this function out will change the behavior of line 17.
			// With the function commented out, it returns an object-like structure, 
			// as one would expect. When the function is left in though, it returns
			// a string representation of said object instead.
			doThing(functionFields);                
		}
	}

	private function doThing(thisMatters: String) {
		trace("Doesn't matter");
	}

	@foo
	@bar(1)
	function testFunction(message:String){
		trace("Doesn't matter");
	}
}
````

Output as written:
src/Main.hx:16: Type of functionFields is: TClass(#$String)
src/Main.hx:19: bytes
src/Main.hx:19: length
src/Main.hx:33: Doesn't matter

Output with `doThing(functionFields)` commented out:
src/Main.hx:16: Type of functionFields is: TObject
src/Main.hx:19: bar
src/Main.hx:19: foo

This took a LOT of debugging. The original issue was caused by a debugging line in a throw, inside a catch that we never even hit. But because the code path was possible, the return type of `Reflect.field(classFields, classFieldName)` became string (which unsurprisingly broke the code that was expecting an object).

The real head-scratcher was that this works fine on *most targets* (For example, Neko). HL was the first target tested that didn't work, as most would do the string conversion at doThing(), while HL seems to read ahead and do it during assignment. This might simply be a difference in how each target infers the type of functionFields  (which is not specified, and being returned a Dynamic).

Ultimately, this may not be a bug. But I spent the better part of three hours debugging a library that had this bug, and the behavior was neither obvious or easy to debug. I only realized the string casting behavior after getting halfway through this report and realizing I could cut out a few more lines in my repro case, which ultimately narrowed it down to the argument type of `doThing`. This also probably *only* affects the case in which a function returns pure Dynamic, as any vaguely more strict type will throw a compile time error as one would hope/expect.

So I guess tl;dr: Dynamic's teeth are especially sharp in HL.

**Comment by ncannasse** [comment]
I can't reproduce using Haxe GIT + HL GIT.
