### ISSUE TITLE
Help installing on Debian (Error: "Library hashlink not installed")

### ISSUE THREAD

**Issue by uvtc** [HaxeFoundation/hashlink#193]
I downloaded and build HL 1.7 in what I think is the usual way (I wrote up [my notes on it here](http://www.unexpected-vortices.com/haxe/getting-started-tutorials/hashlink/getting-started.html)). This in on Debian Testing.

I can then run `haxe -hl output.hl -main Main` just fine (and run the `hl output.hl` file), but get an error when trying:

~~~
$ haxe -hl src/main.c -main Main
Error: Library hashlink is not installed
Error: Build failed
~~~

Here is what's in my /usr/local/lib after installing HL:

~~~
$ ls -1 /usr/local/lib
fmt.hdll
libhl.so
mysql.hdll
openal.hdll
python2.7
python3.6
python3.7
sdl.hdll
ssl.hdll
ui.hdll
uv.hdll
~~~

(I don't think I've ever seen an ".hdll" file on GNU/Linux.)

I just [asked about this on the forum](https://community.haxe.org/t/install-haxe-4-preview-on-debian-where-do-i-put-std-dir/1170/4), but then thought maybe here is a better place, since it may be an issue with the HL install instructions (?).

Or maybe I didn't install Haxe 4 correctly?

Thanks.

**Comment by uvtc** [comment]
Looks like this is solved (per Valentin's suggestion) by `haxelib install hashlink`.

Though, that seems like an unfortunate overloading of the name "hashlink". Shouldn't that be `haxelib install hxhashlink`, to be more consistent with hxcpp, hxcs, and hxjava?

**Comment by uvtc** [comment]
Or maybe `haxelib install hxhl`.

**Comment by ncannasse** [comment]
I don't like much prefixing the libraries name with hx on haxelib as they are all haxe libraries anyway :)
But yes the error message should be modified with "please run haxelib install <lib>", but that's an haxelib issue when doing "haxelib run"

**Comment by melMass** [comment]
This is still showing the same message.
