### ISSUE TITLE
Improved documentation for embedding HL

### ISSUE THREAD

**Issue by Sunjammer** [HaxeFoundation/hashlink#194]
This is very cool tech and the Embedding Hashlink wiki page needs a lot of love. "HashLink can be easily embedded into any application" is not really true when the knowledge needed to bootstrap it is distributed across a non-trivial C project with few if any comments.

**Comment by ncannasse** [comment]
I'm not sure what there is to say more. You have a full 160 lines C code example (which is not much) available here:

https://github.com/HaxeFoundation/hashlink/blob/master/src/main.c

What else would be required ?

**Comment by sonygod** [comment]
it's seem there are no api about haxe in hl  call   native c api ?

**Comment by ncannasse** [comment]
@sonygod no, you can't directly call C api for now

**Comment by sonygod** [comment]
@ncannasse  because current I want to embed into Unity and call unity api in hl.

**Comment by ncannasse** [comment]
@sonygod atm the best way is to write wrappers like we do for directx/sdl/etc.

**Comment by sonygod** [comment]
some confusing  about that.

May  be step like this?

step 1  define export function  

    DEFINE_PRIM(_BOOL, win_set_fullscreen, TWIN _I32);

step 2:add meta like

    @:hlNative("sdl")?

step3:defined static function in hl?

    static function winSetFullscreen( win : WinPtr, mode : DisplayMode ) {

            return false;
        }

are there anything missing ?

**Comment by sonygod** [comment]
@ncannasse  how to invoke hl static function from c++? can you give a small example?

I can't understand from [here](https://community.haxe.org/t/hashlink-calling-haxe-functions-from-c-c/737) your description 

    class Main 
    {
        
        static function main() 
        {
        
        
        }
        
        
        public static function start(){
            Debug.Log("hl realy startnow ");
        }
        
    }
