### ISSUE TITLE
Cannot run HL on Ubuntu

### ISSUE THREAD

**Issue by fantoine** [HaxeFoundation/hashlink#197]
My problem is that I cannot run HL on Ubuntu.

I compiled it from 1.7.0 release and followed instructions available on https://github.com/HaxeFoundation/hashlink#building-on-linuxosx.

After running `make` and `make install` the hl executable is available but when I run it, I get the following error:

```
hl: error while loading shared libraries: libhl.so: cannot open shared object file: No such file or directory
```

Any solution?

**Comment by ncannasse** [comment]
See https://unix.stackexchange.com/questions/67781/use-shared-libraries-in-usr-local-lib
