### ISSUE TITLE
JIT ERROR 9 (jit.c line 3291)

### ISSUE THREAD

**Issue by Beeblerox** [HaxeFoundation/hashlink#201]
I've found this issue while working on Spine player for Heaps. My code works on js and cpp targets (tested with openfl), but on HashLink it crashes immediately after start with the message:
```
JIT ERROR 9 (jit.c line 3291)
```
After a day of attempts to isolate this issue i've found that it is somehow caused by using combination of abstract (array abstract) and dynamic values. I've assembled minimal example project showing this issue:
https://github.com/Beeblerox/HashLink-JIT-ERROR-9

UPD: forgot to mention that i'm using Haxe 4.0.0-preview.5+7eb789f54, HashLink 1.8.0, Heaps 1.5.0 and hldx 1.8.0
OS: Windows 7 x64

**Comment by Beeblerox** [comment]
updated sample project (https://github.com/Beeblerox/HashLink-JIT-ERROR-9). hope it will help in solving this issue

**Comment by ncannasse** [comment]
`-D hl-check` reports it's an issue with Haxe compiler (not HashLink runtime)

**Comment by Beeblerox** [comment]
@ncannasse ok, i'll open issue there once i get home

**Comment by ncannasse** [comment]
Closing the issue in favor or https://github.com/HaxeFoundation/haxe/issues/7598

**Comment by Beeblerox** [comment]
Thanks!
