### ISSUE TITLE
POBi__v required but PB_v found in hdll?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#208]
FATAL ERROR: POBi__v required but PB_v found in hdll?

c code

    HL_PRIM void HL_NAME(message_box)(vbyte *title) {

      
        printf((char*)title);

    }
    DEFINE_PRIM(_VOID, message_box,_BYTES);

hl code

    @:hlNative("unity")
    class MessageBox 
    {

        @:hlNative("unity","message_box")
        public static function message_box(content:String):Void{
            trace("from hl"+content);
        }
        
    }

**Comment by ncannasse** [comment]
String is an object with utf16 bytes, while vbyte * is just a unsigned char *
You must type message_box( content : hl.Bytes ) on Haxe side, and pass it   @:privateAccess string.toUtf8() to get its utf8 bytes.
