### ISSUE TITLE
MacOS make issue - <png.h> not found in fmt.c

### ISSUE THREAD

**Issue by 32gits** [HaxeFoundation/hashlink#210]
I'm following the mac os instructions and after successfully running `brew bundle`, running `make` produced the following error:

```
cc -Wall -O3 -I src -msse2 -mfpmath=sse -std=c11 -I include/pcre -I include/mikktspace -D LIBHL_EXPORTS -m64 -I /opt/libjpeg-turbo/include -I /usr/local/opt/jpeg-turbo/include -I /usr/local/include -I /usr/local/opt/libvorbis/include -I /usr/local/opt/openal-soft/include -Dopenal_soft -o libs/fmt/fmt.o -c libs/fmt/fmt.c
libs/fmt/fmt.c:2:10: fatal error: 'png.h' file not found
#include <png.h>
         ^~~~~~~
1 error generated.
make: *** [libs/fmt/fmt.o] Error 1
```

I see `png.h` in `include/png/`. I'm not the most experienced with makefiles. Anything I need to edit or can I exclude anything and still have this work ok?

I'm on Mac OS 10.14.2

**Comment by ncannasse** [comment]
#213 should have fixed this, seems like travis is happy now.
