### ISSUE TITLE
Why does the Android platform not support jit?

### ISSUE THREAD

**Issue by cjmxp** [HaxeFoundation/hashlink#212]
Why does the Android platform not support jit?

**Comment by cjmxp** [comment]
As I've read, Android doesn't limit jit. It's easy to update games with JIT support or script support.

**Comment by ncannasse** [comment]
As stated in #185, ARM JIT is entirely different from x86 JIT, and that would require a lot of additional work.

**Comment by cjmxp** [comment]
@ncannasse Hope to be able to support, even if the foot is running as a script.
