### ISSUE TITLE
Failed to start hl process (Error: spawn hl ENOENT)

### ISSUE THREAD

**Issue by mundusnine** [HaxeFoundation/hashlink#221]
OS: Ubuntu 18.04
Haxe preview 5
Hashlink 1.8 compiled locally

When putting hl in /usr/bin/ hl is detected ergo the cp command of make install, should put hl in /usr/bin/ instead of /usr/local/bin/.

**Comment by andyli** [comment]
`/usr/local` is the correct prefix for user-installed custom software. `/usr` is normally reserved for system packages and it is normally advised not to place things there manually.

`/usr/local/bin` is usually already in $PATH, so one can run `hl` directly. If it's not the case, just add it to $PATH.

If you really want to change the install prefix, you can use the [`PREFIX` make variable](https://github.com/HaxeFoundation/hashlink/blob/722d831c461b5797275675bc7c26b8cfbc528f96/Makefile#L4), e.g. `make PREFIX=/usr install`.

**Comment by ncannasse** [comment]
We have a pb on Ubuntu because while /usr/local/bin is in the PATH, /usr/local/lib is not in the LD_LIBRARY_PATH, meaning hl will no run when installed to /usr/local/*

What should be the correct way to deal with it?

**Comment by ncannasse** [comment]
PS: atm workaround is to do `make INSTALL_DIR=/usr install`

**Comment by ncannasse** [comment]
@andyli what's the correct way to install local binary + libraries on Ubuntu ? /usr/local/bin for binaries, but what about libraries?

**Comment by andyli** [comment]
I believe we have to check the rpath thing. There are some CMake options (if not already the default) that handle it pretty well. I can try copy the generated command to the Makefile once I figure it out.
