### ISSUE TITLE
High CPU usage on Heaps.io demo

### ISSUE THREAD

**Issue by 7sharp9** [HaxeFoundation/hashlink#222]
With the following demo:
https://github.com/Beeblerox/Simplest-Heaps-Examples/tree/master/19_heaps_layers

Im getting a cpu usage of 84% which is really high for such a simple demo.  As a comparison with MonoGame rendering the same tile map used 8% cpu.  With the JavaScript version of example 19 it uses 10-20% cpu.

Im using osx 10.14.2
Haxe 4.0.0-preview.5+7eb789f
HL 1.9.0
Heaps 1.5.0

![screenshot 2019-01-19 at 11 28 00](https://user-images.githubusercontent.com/588746/51426783-6658c600-1be7-11e9-8d30-8bb80c788329.png)

**Comment by Beeblerox** [comment]
the same demo on my pretty old laptop with Windows 7 x64 and Intel Core i5 2430M (2.40GHz) uses around 2% of cpu
![hl_performance](https://user-images.githubusercontent.com/857406/51427018-6666bf00-1c03-11e9-94b4-c85d3caaea08.png)

**Comment by ncannasse** [comment]
Most likely vsync is disabled on your opengl driver. I think I heard some issue with it on recent OSX. Try upgrading SDL to latest release.

**Comment by ncannasse** [comment]
PS : you can confirm that by displaying fps

**Comment by 7sharp9** [comment]
Thanks @ncannasse / @Beeblerox  I'll find out about the vsync ...

**Comment by 7sharp9** [comment]
How would I go about updating the sdl that heaps uses?

**Comment by 7sharp9** [comment]
So it looks like its running at 1600 fps, just need to figure out how to address vsync

**Comment by ncannasse** [comment]
Well, in the meanwhile you can simply add a Sys.sleep(0.155) in your update loop to simulate the vsync

**Comment by ncannasse** [comment]
This has been fixed in SDL just one month ago here
https://hg.libsdl.org/SDL/rev/73f3ca85ac0e

**Comment by ncannasse** [comment]
Sadly latest SDL 2.0.9 is from October, so does not contain the fix

**Comment by 7sharp9** [comment]
@ncannasse Thanks!  I actually added in a `Sys.sleep(0.013);` and I get 60fps on my counter and 9% cpu time, so thats quite similar to the MonoGame comparison doing the tile map.

**Comment by ncannasse** [comment]
Closing as it's not hashlink specific.
