### ISSUE TITLE
Compile static and dynamic library with Hashlink

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/hashlink#224]
Would be possible to compile static ( .lib or .a ) and dynamic library ( .dll and .so) for windows / linux using hashlink ?
I was read about compiling library using hxcpp , but not sure is it possible with hashlink ?

**Comment by ncannasse** [comment]
It's definitely possible by using hl/c output, since it's C code you can compile and link it the way you want.
ATM, automatic native compilation is outside of the things we directly support, so there is no change to be done to hashlink sources.

**Comment by melMass** [comment]
@ncannasse Do you have a guide somewhere related to that ?
I can build HLC on all three platforms but it seems to be shared and not static:
On mac for instance:

```bash
gcc mytools.c -o mytools -I. -lm -lhl /usr/local/lib/fmt.hdll /usr/local/lib/uv.hdll
```
And when I run `otool -L`:
```ruby
mytools:
	libhl.dylib (compatibility version 0.0.0, current version 0.0.0)
	fmt.hdll (compatibility version 0.0.0, current version 0.0.0)
	uv.hdll (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```

**Comment by piboistudios** [comment]
> It's definitely possible by using hl/c output, since it's C code you can compile and link it the way you want.
> ATM, automatic native compilation is outside of the things we directly support, so there is no change to be done to hashlink sources.

Is this still true? I recently tried compiling and linking a dll with HashLink and it said native compilation isn't supported (it works without hl/c).

I was using ammer and an ammer hell. I couldn't find the source code where the error as in hashlink, but it seemed intentional (like a TODO type thing)

**Comment by ncannasse** [comment]
The error is about "automatic" compilation. It means you need to compile the C code manually.
