### ISSUE TITLE
Problem with hashlink debugger visual studio code

### ISSUE THREAD

**Issue by demacedius** [HaxeFoundation/hashlink#230]
Hi, i have try make a heaps program and use hashlink in vscode. But he don't run normaly he make a .json in my folder. But nothing help me pls.

**Comment by mundusnine** [comment]
This lacks information to be helped. What OS, what hashlink version and what heaps version ?

**Comment by demacedius** [comment]
All is ok mundusnine if you can talk french with me i'm very happy
