### ISSUE TITLE
Invalid signature for function std@test_test:Pii_i required but pi_i found in hdll?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#234]
hashlink 1.9

add test.c in libhl project ,and build test . where is wrong?

![image](https://user-images.githubusercontent.com/748320/54119766-14872c00-4431-11e9-8ce8-9ad3977ed28e.png)

![image](https://user-images.githubusercontent.com/748320/54119894-6def5b00-4431-11e9-8337-fcc4cc744755.png)

![image](https://user-images.githubusercontent.com/748320/54119906-78115980-4431-11e9-888b-b947d6d89496.png)

**Comment by ncannasse** [comment]
You can an error in you DEFINE_PRIM, parameters should be not separated with commas:

`DEFINE_PRIM(_I32, test_test, _I32 _I32)`
