### ISSUE TITLE
How to remove GC finalizers?

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hashlink#237]
Using CFFI, we use `val_gc(ptr, finalizer);` then `val_gc(ptr, NULL)` in order to set or remove an object finalizer.

I have the following code to use finalizers on HashLink:

```cpp
struct HL_CFFIPointer {
	void* finalizer;
	void* ptr;
};

typedef void (*hl_finalizer)(void* v);

HL_CFFIPointer* HLCFFIPointer (void* handle, hl_finalizer finalizer) {
	HL_CFFIPointer* pointer = (HL_CFFIPointer*)hl_gc_alloc_finalizer (sizeof (HL_CFFIPointer));
	pointer->finalizer = finalizer ? (void*)finalizer : 0;
	pointer->ptr = handle;
	return pointer;
}

// example

HL_CFFIPointer* ref = new HLCFFIPointer (ptr, (hl_finalizer)finalizer);
```

However, I am having a crash when trying to remove the finalizer:

```
if (glObjectPtrs.find (object) != glObjectPtrs.end ()) {

	HL_CFFIPointer* handle = (HL_CFFIPointer*)glObjectPtrs[object];
	handle->finalizer = NULL;
	delete handle;
	glObjectPtrs.erase (object);

}
```

> HerokuShaders(71366,0x11c4565c0) malloc: *** error for object 0x10f702178: pointer being freed was not allocated
HerokuShaders(71366,0x11c4565c0) malloc: *** set a breakpoint in malloc_error_break to debug

I believe we will need to remove our custom struct, but I do not want the finalizer to run. Am I doing this properly? Any suggestions?

EDIT: Am I just overthinking this? Should I skip the `delete`, and assume the VM will remove that memory later?

Thank you

**Comment by ncannasse** [comment]
Just setting the finalizer to NULL is enough. You shouldn't delete the gc
allocated pointer. Maybe you meant delete handle->pointer ?

Le jeu. 14 mars 2019 23:11, Joshua Granick <notifications@github.com> a
écrit :
