### ISSUE TITLE
fmt hdll linux

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/hashlink#24]
Trying to check out heaps hl but it says:
`src/module.c(207) : FATAL ERROR : Failed to load library fmt.hdll`

So I check and indeed I don't have it,
it's mentioned in the makefile but there's no rule for it.

What is the command to compile it?

**Comment by ncannasse** [comment]
Yes I have to check compilation for that, it requires some dependencies and it seems libPNG API is changing depending on the library version :'(

**Comment by ncannasse** [comment]
Libs to install (for note):  libjpeg-turbo-dev libturbojpeg (yes both) libpng-dev libz-dev libsdl2-dev

**Comment by ncannasse** [comment]
PS: I have added Makefile support for it, please tell me if it works for you

**Comment by ibilon** [comment]
For the packages, on ubuntu 16.04:
```
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
Note, selecting 'zlib1g-dev' instead of 'libz-dev'
E: Unable to locate package libjpeg-turbo-dev
```
so I ended doing `apt install libturbojpeg:i386 libpng12-dev:i386 zlib1g-dev:i386 libsdl2-dev libsdl2-2.0-0:i386 `

but not enough, somehow I had to do `ln -s /usr/lib/i386-linux-gnu/libSDL2-2.0.so.0 /usr/lib/i386-linux-gnu/libSDL2.so`,
but after that it compiled.

Running the base2D sample didn't work, missing ui.hdll, though not sure why it'd need it, and an issue ofc since it's not available on linux.

Also is 64 bits support far? It's a huge pain to deal with 32bits on a 64.

**Comment by ibilon** [comment]
Actually doesn't work, stubbed a ui.hdll,
and I get `PNG support is missing for this libPNG version`.

**Comment by ibilon** [comment]
You use the simplified api from libpng 16, while ubuntu 16.04 only offers libpng 12,
that's going to be an issue.

I'll try getting libpng from source, but that's not ideal.

**Comment by ibilon** [comment]
Ok, got libpng 16 from a debian package and it works.
I'll open another issue about ui.hdll.

**Comment by ncannasse** [comment]
Yes, but I don't know how much simple it is for people to get libpng16 installed on their computers. If it's not widely distributed enough i'll have to write libpng12 compatibility

**Comment by ncannasse** [comment]
Regarding 64 bits support : HL/C supports 64 bits compilation but not HL/JIT, I need to fully rewrite the JIT because maintaining the two backends the way I did it is not really feasible, I also need much more optimizations although I'm surprised how well it runs :)
