### ISSUE TITLE
Comparison equality bug

### ISSUE THREAD

**Issue by rushmobius** [HaxeFoundation/hashlink#241]
Running hashlink 1.9 on windows the following doesn't have the expected results.
It works as expected for flash/js/cpp targets.

`class Test {
    static function main() {
        
        var a:Array<Dynamic> = [];
        
        a.push(foo);
        
        var index = a.indexOf(foo);
        
        var c = a[0];
        
        if (index == -1)
        {
            trace('not found by index');
		}
        else
        {
            trace('found by index');
        }
            
        if (c != foo)
        {
            trace('c != foo');
        }
        else
        {
			trace('c == foo');
        }
    }
    
    static function foo():Void
    {
        
    }
}`

**Comment by ncannasse** [comment]
On some platforms (including HashLink), functions needs to be compared using Reflect.compareMethods.
