### ISSUE TITLE
CI failure

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hashlink#245]
CI has been failing for some time now with some weird ASM errors in uvsample which I don't really understand. Can you look into it @andyli ? Thanks!

**Comment by andyli** [comment]
I can reproduce that in Ubuntu Bionic in WSL, but I have no idea.
Can you reproduce it?

**Comment by ncannasse** [comment]
Not on Ubuntu 16 which I am using.

**Comment by andyli** [comment]
But I just reproduced that with a clean Ubuntu 16.04 docker image.
The commands I used:

```
apt update

# libjpeg-turbo
apt install git cmake nasm make gcc -y
git clone --single-branch --branch 2.0.2 --depth 1 https://github.com/libjpeg-turbo/libjpeg-turbo.git /libjpeg-turbo
mkdir /libjpeg-turbo/build
pushd /libjpeg-turbo/build
cmake ..
make
make install
popd


# haxe
apt install software-properties-common -y
add-apt-repository ppa:avsm/ppa -y
add-apt-repository ppa:haxe/releases -y
apt update
apt install ocaml-nox camlp4-extra opam m4 neko neko-dev -y
opam init --disable-sandboxing --yes
eval $(opam env)
pushd path/to/haxe
opam install . --deps-only --yes
make
make install
popd
haxelib setup ~/haxelib
haxelib install hashlink


# hashlink
apt install libpng16-dev libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev -y
cd path/to/hashlink
make
make install
haxe -hl src/_main.c -cp other/tests -main HelloWorld
make hlc
```

**Comment by andyli** [comment]
unassigning myself since it's not CI specific

**Comment by ncannasse** [comment]
@andyli according to https://travis-ci.org/HaxeFoundation/hashlink/builds it started failing two months ago and does not seem related to any specific commit, so it does not look like a regression due to a change in HashLink...

**Comment by ncannasse** [comment]
Was due to having variables prefixed by $ in HL/C generation.
