### ISSUE TITLE
Debugger does not launch

### ISSUE THREAD

**Issue by schmidh** [HaxeFoundation/hashlink#247]
I  am using Ubuntu 18.10, hl 1.9.0, haxe 4.0.0-rc.2+77068e1, VS Code 1.33.1. When trying to debug Heaps samples for self-teaching reasons I get following error from VS Code:

`Could not start hl process, executable was not found in PATH. Restart VSCode or computer.` 

The build itself works fine. `hl` is in directory `/usr/local/bin` and causes no problems using from the command line. VS Code has this path also in the `process.env.PATH` variable. No idea why hl cannot be launched. Tried also with haxe 4.0.0.-rc1 because it has been mentioned in the documentation that hashlink is compatible with that version, but no difference.

**Comment by ncannasse** [comment]
This was fixed in hashlink debugger repo.

**Comment by r0mac09** [comment]
@schmidh You may want to follow "Additional steps for Heaps and HashLink VM" from https://heaps.io/documentation/installation.html. That fixed it for me.
