### ISSUE TITLE
compiler conditional blocks completely ignored sometimes.

### ISSUE THREAD

**Issue by hedgehog90** [HaxeFoundation/hashlink#248]
For me, this statement produces different results on each compile:

```
#if true
//do stuff
#end
```

It's literally like rolling a dice. I compiled my app for hl 15 times in a row with no alterations, this was the result (0 = ignored conditional blocks, 1 = conditional blocks ran):

001001001110011

Can't detect a pattern there. Really bizarre...

I'm using the latest release.

**Comment by ncannasse** [comment]
Please report this on https://github.com/HaxeFoundation/haxe with a fully tested reproducing sample. Sometimes a small example does not reproduce the issue.
