### ISSUE TITLE
Windows process stdout non-blocking

### ISSUE THREAD

**Issue by JeremyGiner** [HaxeFoundation/hashlink#249]
I'm trying to redirect the stdout of multiple child process ( child process which execution may last hours ).

When i attempt to read stdout of a Process, the function readByte never throw Error.Blocked, and instead block the main process.

After a quick research it seems the problem is due to CreatePipe in hashlink/src/std/process.c, according to [this stackoverflow thread](https://stackoverflow.com/questions/60645/overlapped-i-o-on-anonymous-pipe) only the CreateNamedPipe function can use the asynchronous behavior of ReadFile.

Windows 7, hl 1.9.

Haxe documentation never really explicitly say which behaviour the function readByte should have, althought i really wish all input stream were non-blocking.

Can readByte be changed to non-blocking ?

**Comment by ncannasse** [comment]
We are currently working on an fully async system API for Haxe, which will answer this issue as well as many others. In the meanwhile, you can easily copy and modify the process.c content by creating your own HL extension (NDLL file).
