### ISSUE TITLE
Invalid string comparison

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/hashlink#250]
```haxe
class Main {
	static public function main() {
		var s = "𠜎zя";
		var s2 = "abя";
		trace(s > s2);
	}
}
```
That yields `false` on hashlink, `true` on all other targets.

**Comment by ncannasse** [comment]
I see...
s bytes (utf16) : `41d80edf7a004f04`
s2 bytes (utf16) : `610062004f04`
and I'm using direct bytes compare, which is not correct here...

**Comment by ncannasse** [comment]
Also, String ordering is not strictly guaranteed, should depend on #if utf16, as the following shows:

```
		var s = String.fromCharCode(0xFF61);
		var s2 = String.fromCharCode(0x10002);
		trace(s > s2); // #if utf16 true #else false #end
```

**Comment by ncannasse** [comment]
@Aurel300 we might want to add unit tests for the two samples above
