### ISSUE TITLE
Initializing classes and calling functions from c++

### ISSUE THREAD

**Issue by nesrak1** [HaxeFoundation/hashlink#253]
I've been trying to find details on how to create a new instance of a class and call functions from it in c++ but haven't been able to find much. I also found this post on the [haxe forums](https://community.haxe.org/t/hashlink-calling-haxe-functions-from-c-c/737) about doing this same thing, however the instructions are still not very clear.

I have a simple class and some functions in a script:

```hx
class ClassA {
	var test : Int;
	public function new() {
		this.test = 5;
	}
	public function someOtherCode() {
		Sys.print(test);
	}
}
```

Using code from that post, I find the type:

```cpp
for (int i = 0; i < ctx.code->ntypes; i++) {
	hl_type *type = ctx.code->types + i;

	if (type->kind == HOBJ && ucmp(type->obj->name, USTR("ClassA")) == 0) {
		vdynamic* inst = hl_alloc_obj(type);
		//but how to get the function reference?
		
		vclosure* closure = hl_alloc_closure_void(inst->t, funcptr);
		bool isExc;
		hl_dyn_call_safe(closure, NULL, 0, &isExc);
		//...
	}
}
```

The post mentions getting the constructor by finding the global value in `type->obj->rt->global_value`, however there is no global_value in rt (not that I would know what to do with global_value.) So then how do I get a pointer to `__constructor__` to pass into `hl_alloc_closure_void`?

I also tried to loop through the functions "array" and it finds a match for `ClassA` and `someOtherCode` as well as `$ClassA` and `__constructor__`, but I'm not even sure if the `hl_function` is helpful.

```cpp
hl_function* targetfunc = NULL;
for (int i = 0; i < ctx.code->nfunctions; i++) {
	hl_function *func = ctx.code->functions + i;

	if (func != NULL && func->field.name != NULL) {
		if (func->obj == NULL) {
			uprintf(USTR("%s from unknown class\n"), func->field.name);
		} else {
			uprintf(USTR("%s from %s\n"), func->field.name, func->obj->name);
			if (ucmp(func->obj->name, USTR("ClassA")) == 0 && ucmp(func->field.name, USTR("someOtherCode")) == 0) {
				targetfunc = func;
			}
		}
	}
}
```

Passing `functions_ptrs[targetfunc->findex]` into `hl_alloc_closure_void` crashes the program.

**Comment by ncannasse** [comment]
You need to hl_hash the field name, then look it up using:

```
static hl_field_lookup *obj_resolve_field( hl_type_obj *o, int hfield ) {
	hl_runtime_obj *rt = o->rt;
	do {
		hl_field_lookup *f = hl_lookup_find(rt->lookup,rt->nlookup,hfield);
		if( f ) return f;
		rt = rt->parent;
	} while( rt );
	return NULL;
}
```

Once you have the `hl_field_lookup`, you can use hl_dyn_call_obj

**Comment by nesrak1** [comment]
Is this for regular functions/methods or for the constructor?
Here's what I've got:

```cpp
vdynamic* typeinst = hl_alloc_obj(type);
hl_runtime_obj* runtimeobj = hl_get_obj_rt(type);
int hash = hl_hash((vbyte*)USTR("nameofmethod"));
hl_field_lookup* lo = obj_resolve_field(type->obj, hash);
vdynamic ret;
hl_dyn_call_obj(typeinst, type, lo->hashed_name, NULL, &ret);
```

When testing with `__constructor__`, it errors with
`Field __constructor__ is of type dynamic and cannot be called`. With `someOtherCode` it errors in `hl_wrapper_call` because `tfun->ret` is 1 (might be related to the constructor not being called yet?).

**Comment by ncannasse** [comment]
It's for calling normal methods. To fetch the constructor you need to get the class which is the global value, then do something similar as Haxe Type.createInstance is doing:
https://github.com/HaxeFoundation/haxe/blob/development/std/hl/_std/Type.hx#L124

**Comment by nesrak1** [comment]
Where does the global value come from then? There's `type->obj->global_value` but that's just NULL.

**Comment by ncannasse** [comment]
That's weird, are you calling from HL/C or HL/JIT ?

**Comment by nesrak1** [comment]
HL/JIT

**Comment by nesrak1** [comment]
I changed something and now global_value is actually pointing somewhere but that value is null as well. I've been using hl_type_get_global but it still returns NULL.

**Comment by ncannasse** [comment]
It most likely means you're calling too early before the classes are
initialized. You need to call the entry point first.

**Comment by nesrak1** [comment]
That worked, although I just realized that ClassA's global value points toward $ClassA... Now I have a reference to the constructor but I still don't know how to call it since it's an HDYN instead of an HFUN.

**Comment by nesrak1** [comment]
Okay, I figured it out. Most functions have the first argument of the function as the instance to the class so `hl_dyn_call` is automatically passing the parameter of the current class to the function. The problem is that even though the constructor is part of `$ClassA`, the function's parameter takes `ClassA`. To fix this, I created a new function that took the normal class's instance to replace the one that `hl_dyn_call` tries to use. Here's the code used in case anyone needs it:
```cpp
for (int i = 0; i < ctx.code->ntypes; i++) {
	hl_type *type = ctx.code->types + i;

	if (type->kind == HOBJ && ucmp(type->obj->name, USTR("ClassA")) == 0) {
		vdynamic* glbl = *(vdynamic**)type->obj->global_value;
		vdynamic* instMain = hl_alloc_obj(type);
		vdynamic* instGlbl = hl_alloc_obj(glbl->t);

		int hash = hl_hash((vbyte*)USTR("__constructor__"));
		hl_field_lookup* lo = obj_resolve_field(glbl->t->obj, hash);
		vdynamic* c = (vdynamic*)hl_dyn_getp(instGlbl, lo->hashed_name, &hlt_dyn);

		hl_dyn_call_constructor((vclosure*)c, instMain, NULL, 0);
	}
}
```

`hl_dyn_call_constructor` is just `hl_dyn_call` with
`tmp.args[0] = hl_make_dyn(&c->value,ctmp.t->fun->args[0])` replaced with
`tmp.args[0] = cons;`

There's probably a better way to find the original class than just manually passing the original class in, but this works for me.
