### ISSUE TITLE
can't load file lib openal.hdll

### ISSUE THREAD

**Issue by Lightnet** [HaxeFoundation/hashlink#255]
I try to run command.

`hl game.hl`

`hl-1.9.0\src\module.c(321) : FATAL ERROR : Failed to load library openal.hdll`

I get this error.  I building the src release. Window 10 64bit vs2017. Compile release x64. Using the vscode for my project build.

**Comment by ncannasse** [comment]
You need to copy soft_openal.dll as openal32.dll and have it in same
directory as hl.exe

**Comment by Lightnet** [comment]
Oh right need to add lib in release folder. But I didn't find soft_openal.dll but found 
`openal-soft-1.19.1-bin\bin\Win64`

`soft_oal.dll > OpenAL32.dll`

Hard to tell when rename the correct file.
