### ISSUE TITLE
Question: Supported target CPUs

### ISSUE THREAD

**Issue by andreasdr** [HaxeFoundation/hashlink#257]
Hi,

I am the developer of an 3d engine. Have a look here if interested
- https://github.com/andreasdr/tdme2

Now I am looking for a scripting language that I can include into tdme2 as I currently work on a game title and one requirement is now that our game designer can script our bots. I first had a look at lua, but it seems like Haxe with Hashlink is even better as I can compile haxe scripts to C code which is great for releases. I also like haxe language much more than lua scripts, but ...

My 3d engine is highly portable and I want to keep it this way. So as I am not sure after reading your wiki about:
- What CPU targets are supported for JIT and compilation to C?
- Is there a fall back interpreter or something if CPU target is too crazy like MIPS or something
- The minimum I need is X86 and ARM, will this work?
- Can I (easily) extend the functionality of the VM like adding classes or functions that can be called, think of "Bot::moveTo(x,y,z) or Bot::playAnimation(string)

Many thanx and

Best regards
Andreas

**Comment by ncannasse** [comment]
- For JIT, only x86 and x86-64 are supported. But for C compilation, all CPUs should be supported although we so far only have tested on low endian hardware. 
- There is no interpreter atm, although there might be in the future, see #195 
- yes for HL/C both x86 and ARM CPUs are supported
- yes, you can export any C/C++ function to Haxe layer using FFI, for C++ classes you can also use high level generator such as https://github.com/ncannasse/webidl
