### ISSUE TITLE
[HL 1.10] Error when try windows compile

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/hashlink#260]
I download and compile the latest hashlink ( for windows) . Everything compiles except SDL and OpenAL . The errors are :
  ```c:\haxe\hashlink\libs\sdl\gl.c(16): fatal error C1083: Cannot open include file: 'SDL.h': No such file or directory```

```c:\haxe\hashlink\libs\sdl\sdl.c(6): fatal error C1083: Cannot open include file: 'SDL.h': No such file or directory```

```c:\haxe\hashlink\libs\openal\openal.c(8): fatal error C1083: Cannot open include file: 'AL/al.h': No such file or directory```

**Comment by Gama11** [comment]
https://github.com/HaxeFoundation/hashlink#building-on-windows

>To build all of HashLink libraries it is required to download several additional distributions, read each library README file (in hashlink/libs/xxx/README.md) for additional information.

**Comment by flashultra** [comment]
Thank you .
