### ISSUE TITLE
Can't cast i32 to String?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#262]
Can't cast i32 to String?

![image](https://user-images.githubusercontent.com/748320/59839009-88b36300-9382-11e9-8fd8-c4cb8f50b7a0.png)

code from 
https://github.com/ianharrigan/hxWebSockets/blob/master/Examples/sys-server/src/MyHandler.hx

**Comment by sonygod** [comment]
hashlink :git version
haxe :4.0.0.0 rc.3

**Comment by sonygod** [comment]
It's work on Neko target.

if I change to Std.string(XXX) it's also work on Hashlink.

Maybe it's not a bug ?

**Comment by ncannasse** [comment]
It's working as indented. On static platforms casts needs to be explicit.
