### ISSUE TITLE
Dynamic from Float

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/hashlink#263]
According to https://github.com/HaxeFoundation/haxe/issues/8477
it is specified for value 3.0 to be resolved as type TInt. Is this going to change for HL? To become TInt like on any other target?

**Comment by Ilir-Liburn** [comment]
Well, now I'm getting on following code (test /= 2)

```haxe
        var f:Float = 3.0;
        var test:Dynamic = f;
        trace(Type.typeof(test) == Type.ValueType.TFloat);
        test /= 2;
        trace(test);
        trace(Type.typeof(test) == Type.ValueType.TFloat);


Main.hx:39: true
Uncaught exception: Access violation
Called from $Main.main(Main.hx:40)
Called from fun$376(?:1)
```

**Comment by RealyUniqueName** [comment]
It's not specified to be `TInt`, it's specified to be either `TInt` or `TFloat` for `3.0` depending on a target platform representation of numbers.

**Comment by Ilir-Liburn** [comment]
Ok, then HL is the only one which will stay like that. Even CPP or CS which doesn't "suffer" from everything being Float like JS, use TInt in this case.
