### ISSUE TITLE
Memory Error in New Hashlink Release

### ISSUE THREAD

**Issue by JarduDray** [HaxeFoundation/hashlink#265]
Haxe version: Development branch of git source.
GCC: 9.1.0
OS: Manjaro Linux 64-bit

After building source release and git version of Hashlink, I'm getting this error:
src/module.c(465) : FATAL ERROR : Invalid signature for function sdl@event_loop : PD_b required but POiiiiiiiiibiii__b found in hdll

**Comment by JarduDray** [comment]
It looks this issue happens on 1.9 also with the latest source. Can anyone else verify that?

**Comment by ncannasse** [comment]
You have older sdl.hdll (1.9) with newer hlsdl library (1.10)

**Comment by JarduDray** [comment]
Gotya. Thanks. :D

**Comment by A1vinSmith** [comment]
![Screen Shot 2019-07-26 at 20 11 23](https://user-images.githubusercontent.com/24937594/61936822-97281680-afe1-11e9-912c-1b68a5ad5c17.png)
