### ISSUE TITLE
sqlite " :memory:: error.

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#268]
package;

	import haxe.Json;
	import sys.db.ResultSet;
	import sys.db.Sqlite;
	import Random;

	class Main {
		static function main() {
			var t1 = Date.now().getTime();
			var cnx = Sqlite.open(":memory:");
			cnx.request("
			CREATE TABLE IF NOT EXISTS User (
				id INTEGER PRIMARY KEY AUTOINCREMENT, 
				name TEXT, 
				age INTEGER, 
				money DOUBLE
			)
	");

			for (i in 0...999) {
				cnx.request('INSERT INTO User (name,age,money) VALUES (\'${Random.string(5)}\',${Random.int(18, 60)},${Random.int(1, 100)})');
			}
	cnx.request('INSERT INTO User (name,age,money) VALUES ("sonygod",${Random.int(18, 60)},100.45)');
			
			var r :ResultSet= cnx.request("SELECT * FROM User WHERE age>55");
			
			
			
			trace(r.length);
			
			var xx = r.results();
			
			
			for (e in xx){
				
				
				trace(e); 
			}
			var t2 = Date.now().getTime();

			var t3 = t2 - t1;

			trace(t3);

			return;
		}
	}

code can run in Neko target ,but failed  HashLink .

Haxe:4.0rc3+  ,Hashlink:1.10

**Comment by sonygod** [comment]
for (i in 0...100)

when increase number  from 100 to 999,, Hashlink target is  failed,but Neko ok

**Comment by RealyUniqueName** [comment]
What are your compilation flags (hxml file)?
What is the error you see on Hashlink?

**Comment by sonygod** [comment]
![QQ图片20190715171446](https://user-images.githubusercontent.com/748320/61206000-14bb6f00-a724-11e9-97eb-8d28d9e91e40.png)

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/61206108-5815dd80-a724-11e9-9cc5-1437b704186e.png)


neko target same code ,can build an run

**Comment by sonygod** [comment]
[testsql.zip](https://github.com/HaxeFoundation/hashlink/files/3391611/testsql.zip)

here is my test project .

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/61206360-f013c700-a724-11e9-8ed9-66d64793c4ca.png)

**Comment by sonygod** [comment]
@hughsando 

hxcpp got the same error.

**Comment by sonygod** [comment]
@RealyUniqueName  java target failed

**Comment by ConstNW** [comment]
i got that:
``` Uncaught exception: Access violation
Called from $String.__add__(D:\devel\haxe4\std/hl/_std/String.hx:242)
Called from $Main.main(Main.hx:22)
Called from fun$374(?:1)
```

looks like it's not sqlite problem

**Comment by sonygod** [comment]
@ConstNW  what's your haxe and hashlink version?
I got the error:

sqlite.hx 70 

sqlite.hx .66

I'm sure it's hashlink error ,same code can run in Neko target.

**Comment by sonygod** [comment]
@ConstNW ，I test again,got the same error  std/hl/_std/String.hx:242

**Comment by ConstNW** [comment]
I got it

**Comment by sonygod** [comment]
@ConstNW ,thank you ,it's fixed.
