### ISSUE TITLE
Reflect.setField cast issue

### ISSUE THREAD

**Issue by rushmobius** [HaxeFoundation/hashlink#272]
Using hashlink 1.9.
Given a type
`
class Foo
{
public var x:Float;
}
`
The following fails with cannot cast String to Float64
`
var f = new Foo();
Reflect.setField(f, "x", "2.4");
`
I've run similar code for the as3/hxcpp targets and the type conversion for string to int/float is automatic.

Digging through the cast code, it doesn't seem to do any string to primitive conversions

**Comment by ncannasse** [comment]
Yes it's perfectly normal. HL does not automatically perform string to
number convertions for the sake of better runtime type safety.

Le mar. 23 juil. 2019 à 19:35, Ken Foster <notifications@github.com> a
écrit :

**Comment by rushmobius** [comment]
Ah, I understand the reasoning behind it.
I'll have to supplement the dyn cast calls, as we rely on other packages that expect the coercion from String to work as well as internal packages that do so as well.

I'll need to test, but I'm guessing var x:Float = "12.34" will fail as well in that case.

Thanks

**Comment by ncannasse** [comment]
Yes. you need explicit Std.parseFloat.

Le mar. 23 juil. 2019 à 20:12, Ken Foster <notifications@github.com> a
écrit :
