### ISSUE TITLE
src/alloc.c(425) : FATAL ERROR : Out of Memory (pages)

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#273]
it's seem there are more than 20% memory,it's throw this error?

![image](https://user-images.githubusercontent.com/748320/62409886-7cbcf100-b610-11e9-915a-8dc39c022f58.png)

**Comment by ncannasse** [comment]
This might happen on 32 bit compilation mode if you are trying to allocate
a large memory section and there is not enough consequent address space
available due to fragmentation.

**Comment by sonygod** [comment]
Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)

my system
