### ISSUE TITLE
Uncaught exception: Can't cast hl.types.ArrayBytes_Int to hl.types.ArrayObj

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#274]
-lib Random

--------------------------------

	var it=Random.fromArray([1,2,3,4]);
		
	race(it);

**Uncaught exception: Can't cast hl.types.ArrayBytes_Int to hl.types.ArrayObj**

**Comment by ncannasse** [comment]
Yes, you can't pass an Array of Int to an Array of T without @:generic.
