### ISSUE TITLE
src/module.c(321) : FATAL ERROR : Failed to load library sqlite.hdll

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#277]
src/module.c(321) : FATAL ERROR : Failed to load library sqlite.hdll

cd libs/sqlite/

make && make install

 sqlite.hdll  to /usr/local/lib,

it's still throw this error?

**Comment by sonygod** [comment]
after cmake build ,you have to copy to 



cp /usr/local/lib/libhl* /usr/bin
cp /usr/local/lib/libhl* /usr/lib


cp /usr/local/lib/*.hdll  /usr/lib

cp /usr/local/lib/*.hdll  /usr/bin

**Comment by Aurel300** [comment]
`/usr/local/lib` should be good enough of an installation location. The problem seems to be that the library path (`LD_LIBRARY_PATH`) is not set up correctly. See [this answer on SO](https://stackoverflow.com/a/4743249).
