### ISSUE TITLE
sqlite Can't cast String to Date

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#278]
sqlite Can't cast String to Date

	cnx.request("
			CREATE TABLE IF NOT EXISTS fa_game (
				id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
				us_id integer  NOT NULL DEFAULT 0,
				room_id integer  NOT NULL DEFAULT 1,
				round integer NOT NULL DEFAULT 0,
				coeds TEXT NOT NULL,
				win integer NOT NULL DEFAULT 0,
				lost integer NOT NULL DEFAULT 0,
				fk integer NOT NULL DEFAULT 0,
				time DATETIME NULL DEFAULT CURRENT_TIMESTAMP

			)
			");

			var q = 'SELECT * from fa_game where us_id=$playerID';

			var rs = cnx.request(q);

		var arr = [];

		for (r in rs) {
			var d:Date = r.time;//sqlite Can't cast String to Date
                     }

**Comment by sonygod** [comment]
try to fixed.but not perfect 

         var d:Date = Date.fromString(r.time);

**Comment by ConstNW** [comment]
> 2.2. Date and Time Datatype
SQLite does not have a storage class set aside for storing dates and/or times. Instead, the built-in Date And Time Functions of SQLite are capable of storing dates and times as TEXT, REAL, or INTEGER values...

https://www.sqlite.org/datatype3.html#date_and_time_datatype

**Comment by sonygod** [comment]
@ConstNW  oh,,2.2 

I use 3.0+ for test.

**Comment by sonygod** [comment]
would you update sqlite hdll? for new version?

**Comment by Aurel300** [comment]
@sonygod If you follow the link `2.2` is just the number of the chapter and has nothing to do with the version.
