### ISSUE TITLE
[hl] mysql result set alway sent date time =	1565600 back? 

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#279]
[hl] mysql result set alway sent date time =	1565600 back? 

mysql result set alway sent date time =	1565600 back?

maybe it’s a bug .

target:hashLink.

       var q = 'SELECT * from fa_game';

	var rs = cnx.request(q);

	var arr = [];

	for (r in rs) {

		
		var d:Date = r.time;//1565600  but my server database is not this value.

         }

![image](https://user-images.githubusercontent.com/748320/62908890-d5c51b80-bdac-11e9-84d7-b169e95c473f.png)

**Comment by Aurel300** [comment]
Isn't this the same as #278?

What does `trace(r.time);` in the loop output?

**Comment by ConstNW** [comment]
Looks like it's mysql lib bindings problems.
Try temporary fix:
```haxe
        @:hlNative("mysql", "set_conv_funs")
	static function setConvFuns(fstring:Dynamic, fbytes:Dynamic, fdate:Dynamic, fjson:Dynamic) {};
```
at: https://github.com/HaxeFoundation/haxe/blob/development/std/hl/_std/sys/db/Mysql.hx#L217

**Comment by sonygod** [comment]
@Aurel300 no,it's difference  error.

**Comment by sonygod** [comment]
@ConstNW ,nice! I will test

**Comment by sonygod** [comment]
@ConstNW ,please convert to ms instead of s,

1565768024064 :+1: 
1565667537 :-1:  current you modified  is this result

**Comment by ncannasse** [comment]
Fixed by https://github.com/HaxeFoundation/haxe/pull/8630

**Comment by ConstNW** [comment]
> @ConstNW ,please convert to ms instead of s,
> 
> 1565768024064 👍
> 1565667537 👎 current you modified is this result

haxe trying to get same results across all targets, so when you getting DATETIME from mysql you should be sure it's fetched as UNIX_TIMESTAMP with seconds precision and automatically by default converted to Date type.

if you think it should have milliseconds or microseconds precision or whatever changes then submit them to the [Haxe Evolution](https://github.com/HaxeFoundation/haxe-evolution)
