### ISSUE TITLE
Sys.time()

### ISSUE THREAD

**Issue by ConstNW** [HaxeFoundation/hashlink#280]
on windows Sys.time() return high precision timestamp but not in unix epoch as expected.

```haxe
class Main
{
    public static function main( ) : Void
    {
        trace(Sys.time());
        trace(Date.now().getTime());
        trace(haxe.Timer.stamp());
    }
}
```
got output:
```
src/Main.hx:23: 14583.3435118
src/Main.hx:24: 1565876592000
src/Main.hx:25: 14583.9046364
```
expected output :
```
src/Main.hx:23: 1565876154.966
src/Main.hx:24: 1565876154000
src/Main.hx:25: 1565876154.969
```

**Comment by ConstNW** [comment]
updated version output:
```
src/Main.hx:23: 1565879082.43818
src/Main.hx:24: 1565879082000
src/Main.hx:25: 1565879082.43865
```

**Comment by Aurel300** [comment]
I assume the comment from [`haxe.Timer.stamp`](https://api.haxe.org/v/development/haxe/Timer.html#stamp) applies here too?

> The value itself might differ depending on platforms, only differences between two values make sense.

**Comment by Aurel300** [comment]
I understand, and your fix seems good. I was just trying to say that that comment should have been put on `Sys.time`. And I wonder if it is not epoch-based on any other targets.

**Comment by ConstNW** [comment]
as i know every sys-target got unix-epoch from Sys.time except hashlink
