### ISSUE TITLE
[sqlite] cnx.request  excute in same time error.

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#282]
SIGNAL 11
    @0x62E291E0
    sys.db._Sqlite.SqliteResultSet.getFieldsNames(C:\HaxeToolkit\haxe\std/hl/_std/sys/db/Sqlite.hx:258)
    sys.db._Sqlite.SqliteResultSet.doNext(C:\HaxeToolkit\haxe\std/hl/_std/sys/db/Sqlite.hx:202)
    sys.db._Sqlite.SqliteResultSet.next(C:\HaxeToolkit\haxe\std/hl/_std/sys/db/Sqlite.hx:192)
    sys.db._Sqlite.SqliteResultSet.hasNext(C:\HaxeToolkit\haxe\std/hl/_std/sys/db/Sqlite.hx:177)
    sys.db._Sqlite.$SqliteResultSet.__constructor__(C:\HaxeToolkit\haxe\std/hl/_std/sys/db/Sqlite.hx:148)
    sys.db._Sqlite.SqliteConnection.request(C:\HaxeToolkit\haxe\std/hl/_std/sys/db/Sqlite.hx:70)

--------------

I have two threads  requeset  sqlite. then got that error.

**Comment by sonygod** [comment]
SIGNAL 11
	@0xC769B1E0
	sys.db._Sqlite.SqliteResultSet.doNext(C:\HaxeToolkit\haxe\std/hl/_std/sys/db/Sqlite.hx:198)
	sys.db._Sqlite.SqliteResultSet.next(C:\HaxeToolkit\haxe\std/hl/_std/sys/db/Sqlite.hx:192)
	sys.db._Sqlite.SqliteResultSet.hasNext(C:\HaxeToolkit\haxe\std/hl/_std/sys/db/Sqlite.hx:177)

**Comment by ConstNW** [comment]
provide code example, please

**Comment by sonygod** [comment]
it's in my whole project ,I need some time to provide code example,

**Comment by sonygod** [comment]
package bocai;

	import Random;
	import haxe.MainLoop;
	import sys.db.Sqlite;
	import sys.db.Connection;
	import sys.db.ResultSet;

	class Gen {
		var arr = new Array<Array<Int>>();
		var index = 0;
		private var cnx:Connection;

		public function new() {
			cnx = Sqlite.open(":memory:");

			cnx.request("
			CREATE TABLE IF NOT EXISTS fa_bocai (
			id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
			
				numbers text(9) NOT NULL 
			
			
			)");

		}

		public function gen5(callback:Array<Array<Int>>->Void):Void {
			trace("开始创建gen5");
			for (r in 0...4) {
				MainLoop.addThread(function() {
					var xx = arr.indexOf([1, 2, 3, 4, 5]) == -1;
					while (index < 1000000) {
						var genArray = [];
						// for (i in 0...5) {
						while (genArray.length < 5) {
							var insert = Random.int(0, 9);

							var temp = genArray.slice(0, genArray.length); // 克隆

							// if(check(tem))

							temp.push(insert);

							if (check(temp)) {
								// if(genArray.indexOf(insert)==-1)
								genArray.push(insert);
							}
						}

						var to = cnx.quote(genArray.join(","));
						var rs = cnx.request('select * from fa_bocai where numbers=${cnx.quote(genArray.join(","))}');
						if (rs.length < 1) {
							var rs2 = cnx.request('INSERT INTO fa_bocai (numbers) VALUES ($to)');
							index++;
							if (index % 10000 == 0) {
								trace(index);
							}
						}
					}

					callback(arr);
				});
			}
		}

		public function checkRepeat(arr:Array<Int>):Bool {
			var same = 0;
			// 按顺序检查

			var temp = [];
			for (i in 0...arr.length) {
				if (i == 0) {
					temp.push(arr[i]);
				} else {
					if (temp.indexOf(arr[i]) != -1) {
						temp.push(arr[i]);
					}
				}
			}
			return temp.length < 4;
		}

		public function check(temp:Array<Int>):Bool {
			if (temp.length < 4) {
				return true;
			}

			return checkRepeat(temp);
		}
	}
////

              var gen = new Gen();

		gen.gen5(function(b:Array<Array<Int>>) {
			trace(b.length);

			File.saveContent("c:/gen5.json", Json.stringify(b));
		});

**Comment by sonygod** [comment]
@ConstNW , it seems SQLite does not support multiple threads.

**Comment by ConstNW** [comment]
you should use mutex in threads

**Comment by sonygod** [comment]
how to use mutex in threads?  can you  give a small example?

**Comment by ConstNW** [comment]
[haxe.EntryPoint.addThread](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/EntryPoint.hx#L65-L67)

**Comment by sonygod** [comment]
@ConstNW  I added a checking 	before execute  SqliteLib.request,it's seem fixed .

      public function request(s:String):ResultSet {
			try {
				while (isRequesting) {
					Sys.sleep(1);
				}

				isRequesting = true;
				var r:SqliteResultHandle = SqliteLib.request(c, s.bytes);
				isRequesting = false;
				return new SqliteResultSet(r);
			} catch (e:String) {
				throw 'Error while executing $s ($e)';
			}

			return null;
		}

**Comment by ConstNW** [comment]
it's looks like a solution. On two threads it's ok, but you still have possibility of race condition and you will get unpredictable exceptions here.

**Comment by sonygod** [comment]
can you add something like lock feathers to keep safety get and set ?



Constantine Teplyakov <notifications@github.com> 于 2019年9月2日周一 下午6:31写道：

**Comment by ConstNW** [comment]
use neko.vm.Lock or sys.thread.Lock

**Comment by sonygod** [comment]
https://gist.github.com/sonygod/7db0ddd93d52ecb6a6ead73a473a53fd#Line=75

test ok


 	static function test() {
		
		for (i in 0...3) {
			MainLoop.addThread(function() {
				while (true) {
					var d = BackDataServer.getInstance().getUserInfo(Random.int(1, 500));//here excute sqlite request.

					if (d != null) {
						trace(d.id);
					}
				}
			});
		}
	}
