### ISSUE TITLE
Tls does not prevent GC

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/hashlink#284]
Something I found hidden in the hl docs that didn't show in the API docs:

https://github.com/HaxeFoundation/haxe/blob/72ef1d389e1f1ae3fdbf8a9f6bf76d39774db23b/std/sys/thread/Tls.hx#L32-L33

I'm guessing there should be some `hl_add_root` calls in `thread.c`.

**Comment by ncannasse** [comment]
It's been fixed in latest release.
