### ISSUE TITLE
Cast error occurs when == judgment

### ISSUE THREAD

**Issue by rainyt** [HaxeFoundation/hashlink#286]
Can two different objects be judged to be equal?
Error:
```haxe
Uncaught exception: Can't cast zygame.components.ZQuad to openfl.display.Stage
```
Code:
```haxe
private function onSelect2(e:MouseEvent):Void{
        
        if(isClick== true)return;
        if(e.target == this.stage){

        }
}
```
He seems to have made a conversion.

**Comment by rainyt** [comment]
@ncannasse Hi, hello, I have been troubled by this. Is there any way to avoid this problem? When the dynamic type is compared with other types, an error occurs when the types are inconsistent.

**Comment by ncannasse** [comment]
I think it's more of an Haxe issue when comparing Dynamic values than a HL one.
