### ISSUE TITLE
Array indexOf(e) == -1 is wrong when array length is more than 60000?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#287]
Array indexOf(e) == -1 is wrong when array length is more than 60000?

   I have a test, and I found Array indexOf(e) == -1 is wrong, so there are lot's of repeat  elements  in Array 
   
  
[60000.zip](https://github.com/HaxeFoundation/hashlink/files/3533611/60000.zip)

     
		var c = File.getContent("D:/60000.json");

		var arr :Array<Array<Int>>= Json.parse(c);

		var temp = [];

		for (e in arr) {
			if (e != null && temp.indexOf(e) == -1) {
				temp.push(e);
			}
		}

		File.saveContent('d:/bocai/temp${temp.length}.json', Json.stringify(temp));

          //there are lot's of  duplicate  elements  in files. for example search  0,4,1,4,2

**Comment by sonygod** [comment]
maybe this issue transfer to Haxe?

**Comment by RealyUniqueName** [comment]
Your items are arrays and arrays are compared by reference. That's why `temp.indexOf(e) == -1` always returns `true`.
That is `[0,4,1,4,2] == [0,4,1,4,2]` is awlays `false`, because it's two different arrays. It doesn't matter they hold the same content.
