### ISSUE TITLE
Linux VSCode debugging support?

### ISSUE THREAD

**Issue by eminfedar** [HaxeFoundation/hashlink#290]
Hello,

We are using vscode & linux for debugging with hashlink. But it seems linux debugging not implemented:

![Screenshot from 2019-08-24 14-19-51](https://user-images.githubusercontent.com/14258668/63636626-6556ae00-c67a-11e9-8616-c9aa4aae40b4.png)

When can we see this feature is implemented?

Thanks! Have a nice day beloved devs :)

**Comment by ncannasse** [comment]
Yes we're still missing correctly implementing x64 calling conventions decoding in order to translate register index into hardware register or stack position. Code TODO in `hld.Module.getFunctionRegs`

**Comment by ncannasse** [comment]
This is now working correctly with latest debugger version.
