### ISSUE TITLE
UDP Sockets from hl.uv.Udp?

### ISSUE THREAD

**Issue by eminfedar** [HaxeFoundation/hashlink#291]
Hi there, there is asynchronous tcp socket in hashlink in `hl.uv.Tcp`

But I can't find Udp socket? Is there any?
Because libuv's github page it says both tcp and udp it has.

Thanks! :)

---
Actually I want a build a udp client non-blocking way, then I've searched for threads in hashlink.
But it doesn't exist, then I saw hashlink uses asynchronous I/O for sockets, and saw the TCP exists, but there is no UDP :(

**Comment by Aurel300** [comment]
The `hl.uv` externs are a bit temporary and will be replaced. See the WIP in https://github.com/Aurel300/haxe-sys/tree/master/hl-impl. Asynchronous TCP and UDP sockets will land with the new sys APIs in 4.1.

**Comment by eminfedar** [comment]
So only solution for me for now is just waiting until haxe 4.1 released?

**Comment by Aurel300** [comment]
I think that might be the case. There are no plans to add partial async APIs into the standard library before 4.1. At some point in the future (once I restart the work on HL) you might be able to use my branches of haxe and hashlink.
