### ISSUE TITLE
haxe.$MainLoop.sortEvents  Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#295]
haxe.$MainLoop.sortEvents(C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:137)
Segmentation fault (core dumped)

I can't reproduce this error, Don't know why to throw this error.

target:Hashlink

**Comment by ncannasse** [comment]
Most likely a concurrency issue on event list. You are using threads right?

**Comment by sonygod** [comment]
yes ,you're right.
