### ISSUE TITLE
performance of Array construct to improve  

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#298]
performance of Array construct  improve  

compare between Hl ,Neko ,Nodejs,hxcpp

hl:1000ms

Neko:2000ms

node:32ms

hxcpp:~=37.74ms

php:228ms

   	package;

	/**
	 * ...
	 * @author sonygod
	 */
	class ArrayTest 
	{

		static function main() 
		{
			var t1 = Date.now().getTime();
				for (i in 10...100000) {
				var arr:Array<String> = Std.string(i).split('');//var arr:Array<String> cost lot's of cpu.
				}
				
				trace(Date.now().getTime() - t1);
		}
		
	}

![image](https://user-images.githubusercontent.com/748320/64404897-03516c00-d0b0-11e9-87f7-12854fd01fdd.png)

**Comment by ncannasse** [comment]
This is more likely GC related, not "Array constructor" (or another feature) related. It will be improved with better gc performances when we upgrade GC sometimes in the future. Please avoid in the meanwhile to post benchmarks that are mainly related to allocation.

**Comment by sonygod** [comment]
@ConstNW  What do you think?
