### ISSUE TITLE
hashlink  any plans  debugging environment for Haxe  

### ISSUE THREAD

**Issue by longde123** [HaxeFoundation/hashlink#30]
through HL/JIT virtual machine?

**Comment by ncannasse** [comment]
Yes in the long term, but not for now. I have to look at the protocol for https://github.com/vshaxe/haxe-languageserver

**Comment by ncannasse** [comment]
I'm working on it atm, see https://github.com/HaxeFoundation/hashlink/tree/master/other/debugger
It works well for Windows, will need to add `ptrace` support for Linux/OSX after.

**Comment by nadako** [comment]
Just to mention, the language server protocol is not about debugging, but there's also vscode debugger protocol and haxe externs for the microsoft's implementation by @nulld: https://github.com/vshaxe/vscode-debugadapter-extern
