### ISSUE TITLE
cpu increase

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#304]
after git pull the last version of hash link , my CPU was an increase 

and I roll back to https://github.com/ConstNW/hashlink/tree/patch-4

everything seems ok .I don't know what's wrong

**Comment by Aurel300** [comment]
Why do you keep closing and re-opening your issues? An issue is an issue, if it is low priority, it might be fixed later, if it cannot be fixed, we will close it.

**Comment by sonygod** [comment]
package;
    import haxe.MainLoop;



    class Main {

        static function calc(){

                
            var i=100%10;

    }
        static function main() {
            trace("Hello, world!");

            MainLoop.add(function() {
                calc();
            
                
            });
        
        }
    }

//test code here 

@Aurel300 

Node.js cpu ~3%
hashlink:100%
neko :100%
hxcpp:100%

**Comment by sonygod** [comment]
@Aurel300  WHY I try to keep closing and re-opening? because I'm not sure it's Hash link bug or Haxe 's  gc  bug.

**Comment by Gama11** [comment]
There's no "Haxe GC". HashLink, Neko and HXCPP each have their own separate garbage collector.
