### ISSUE TITLE
sqlite performance is very slowly  in Hashlink target!!!!!!

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#310]
![image](https://user-images.githubusercontent.com/748320/66448347-ca782e80-ea83-11e9-8109-9035c9163d22.png)

HashLink:git version.

Neko: less than 2ms
Hashlink:more than 3 minutes!!!!!!

test in Ubuntu 18.

but get the same time in Windows 

      import sys.db.Sqlite;

    class CustomTrace {
        public static function init() {
            var oldTrace = haxe.Log.trace;
            haxe.Log.trace = function(v:Dynamic, ?pos:haxe.PosInfos) {
                oldTrace("[" + Date.now().toString() + "] " + Std.string(v), pos);
            };
        }
    }

    typedef Scroe = {
        var id:Int;
        var roomID:Int;
        var round:Int;
        var cards:Array<Int>;

        var earnMoney:Int;
        var loseMoney:Int;
        var fk:Int;
        var time:Date;
        var key:Int;
    }

    class TestSqlite {
        public static function main() {
            CustomTrace.init();
            var cnx = Sqlite.open(":memory:");
            cnx.request("
            CREATE TABLE IF NOT EXISTS fa_game (
                id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                us_id integer  NOT NULL DEFAULT 0,
                room_id integer  NOT NULL DEFAULT 1,
                round integer NOT NULL DEFAULT 0,
                coeds TEXT NOT NULL,
                win integer NOT NULL DEFAULT 0,
                lost integer NOT NULL DEFAULT 0,
                fk integer NOT NULL DEFAULT 0,
                time DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
                times integer  NOT NULL,
                score integer NOT NULL DEFAULT 0,
                money integer NOT NULL DEFAULT 0,
                isBanker integer NOT NULL DEFAULT 0
            )
            ");

            var allScores:Array<Scroe> = [];

            for (i in 0...4000) {
                allScores.push({
                    id: i,
                    roomID: i,
                    fk: i,
                    round: i,
                    key: i,
                    time: Date.now(),
                    cards: [i, i + 1, i + 2],
                    loseMoney: i,
                    earnMoney: 1
                });
            }

            trace(allScores.length);
            var arr = [];
            for (p in allScores) {
                var q = 'INSERT INTO fa_game (us_id,room_id,round,coeds,win,lost,fk,time,times) VALUES(${p.id},${p.roomID},${p.round},${cnx.quote(p.cards.join(","))},${p.earnMoney},${p.loseMoney} ,${p.fk},${cnx.quote(Std.string(p.time))},${p.key})';
                arr.push(q);
            
            }

            trace("now?");

            for (p in allScores) {
                var q = 'INSERT INTO fa_game (us_id,room_id,round,coeds,win,lost,fk,time,times) VALUES(${p.id},${p.roomID},${p.round},${cnx.quote(p.cards.join(","))},${p.earnMoney},${p.loseMoney} ,${p.fk},${cnx.quote(Std.string(p.time))},${p.key})';

                // trace(q);
                cnx.request(q);
            }
            trace("finish");
        }
    }

@ConstNW would you have a look this issue?

**Comment by ConstNW** [comment]
Can't confirm yours results.
i got on Windows:
```
Main.hx:68: [2019-10-11 13:49:11] 4000  
Main.hx:76: [2019-10-11 13:49:12] now?  
Main.hx:85: [2019-10-11 13:49:13] finish
```

```
Main.hx:69: [1570790990.43461] 4000  
Main.hx:77: [1570790990.85333] now?  
Main.hx:86: [1570790991.72754] finish
```

@sonygod, Could you please provide your hashlink version or git commit

**Comment by sonygod** [comment]
Only on Ubuntu or linux have that issue
Did you try on ubuntu ?

Constantine Teplyakov <notifications@github.com> 于 2019年10月11日周五 下午6:54写道：

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/66694420-a9af1380-ece5-11e9-9061-147fa6aa8a5d.png)

oh..may be my haxe version is not the lastest ...

I retest.and get the right result.

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/66694497-abc5a200-ece6-11e9-9df7-f0872b28ef5d.png)

although  it's faster than older  version,but it's still slowly than Neko.

**Comment by ConstNW** [comment]
Profiled it on Linux and looks like bottleneck is hashlink GC not sqlite lib.

**Comment by sonygod** [comment]
@ncannasse ?

**Comment by ConstNW** [comment]
Found the problem.
Sqlite on connection call `Sys.getPath(file)` which on Linux convert `:memory:` to `洺浥牯㩹` and open regular file-based db.

Temporary fix: change SqliteConnection from
```haxe
	public function new(file:String) {
		c = SqliteLib.connect(Sys.getPath(file));
	}
```
to
```haxe
	public function new(file:String) {
		c = SqliteLib.connect(file.bytes);
	}
```

**Comment by ncannasse** [comment]
Sys.getPath uses system-dependent conversion for filesystem accesses : utf8 on linux/osx and utf16 on windows. If the SQLite lib only accepts one or the other, it should be fixed.

**Comment by ConstNW** [comment]
sqlite lib uses `sqlite3_open16` so no need to make utf8 conversion.

**Comment by sonygod** [comment]
very helpful. thanks @ConstNW

**Comment by sonygod** [comment]
increase insert speed!           

            cnx.request("begin;");
        
            for (p in allScores) {
                var q = 'INSERT INTO fa_game (us_id,room_id,round,coeds,win,lost,fk,time,times) VALUES(${p.id},${p.roomID},${p.round},${cnx.quote(p.cards.join(","))},${p.earnMoney},${p.loseMoney} ,${p.fk},${cnx.quote(Std.string(p.time))},${p.key})';

                // trace(q);
                var rs = cnx.request(q);

                //   trace(rs.length);//here cpp will crash.
            }
            cnx.request("commit;");
