### ISSUE TITLE
Can not make on macOS 10.15 (19A582a)

### ISSUE THREAD

**Issue by jszsj** [HaxeFoundation/hashlink#311]
`cc -Wall -O3 -I src -msse2 -mfpmath=sse -std=c11 -I include/pcre -I include/mikktspace -I include/minimp3 -D LIBHL_EXPORTS -mx86_64 -I /usr/local/opt/libjpeg-turbo/include -I /usr/local/opt/jpeg-turbo/include -I /usr/local/include -I /usr/local/opt/libvorbis/include -I /usr/local/opt/openal-soft/include -Dopenal_soft  -DGL_SILENCE_DEPRECATION -o include/pcre/pcre_chartables.o -c include/pcre/pcre_chartables.c
clang: error: unknown argument: '-mx86_64'
make: *** [include/pcre/pcre_chartables.o] Error 1`

How to fix this?

**Comment by ncannasse** [comment]
Uhm, that's weird,  ARCH should be either 32 or 64.
What does `getconf LONG_BIT` prints on your OSX ?

You can also try  make ARCH=64, but it should be automatically detected

**Comment by jszsj** [comment]
@ncannasse `getconf LONG_BIT` returns "64" and `make ARCH=64` works fine
Thanks!
