### ISSUE TITLE
need help in installation

### ISSUE THREAD

**Issue by HamrouniAnas** [HaxeFoundation/hashlink#312]
hi, can someone please help me in the installation of hashlink, i opened the hl.sln with visual studio, then i use the windows local debugger button, then i get an error 
![image](https://user-images.githubusercontent.com/50056752/66704508-c87ccc80-ed1c-11e9-8297-76688dacc474.png)
i would appreciate if someone helps, or gives me another way of installing the hashlink VM.

**Comment by sonygod** [comment]
maybe you could switch hl as default launched aapplication  instead of libhl.

**Comment by ncannasse** [comment]
Please ask on https://community.haxe.org/, here is for bug reports.
