### ISSUE TITLE
how to increase Memory for hashlink? 

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#313]
Out of Memory 

src\alloc.c(726) : FATAL ERROR : Out of Memory (markstack)

Are there any like 
 
   -D MAX_MEM=4096

 like  condition?

**Comment by ncannasse** [comment]
Are you building on 32 or 64 bits ? There is no memory limit in 64bits.

**Comment by sonygod** [comment]
Win 7 x64

**Comment by sonygod** [comment]
after update to git version,

    **Uncaught exception: Required memory allocation too big**


Uncaught exception: Required memory allocation too big
Called from hl.types.ArrayObj.__expand(C:\HaxeToolkit\haxe\std/hl/types/ArrayObj.hx:293)
Called from hl.types.ArrayObj.push(C:\HaxeToolkit\haxe\std/hl/types/ArrayObj.hx:67)

**Comment by ncannasse** [comment]
There's a maximum of 1GB for a single allocation block which means around
128M of Array elements.
