### ISSUE TITLE
 SQLite error: Cannot execute several SQL requests at the same time

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#314]
after adding this line

   "PRAGMA journal_mode=WAL; "

---------will throw SQLite error: Cannot execute several SQL requests at the same time

   	    var cnx = Sqlite.open(":memory:");

		cnx.request("PRAGMA synchronous = OFF");
		cnx.request("PRAGMA locking_mode=EXCLUSIVE");

		cnx.request("PRAGMA journal_mode=WAL; ");

            cnx.request("
                CREATE TABLE IF NOT EXISTS fa_game (
                    id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                    n1 integer  NOT NULL DEFAULT 0,
                    n2 integer  NOT NULL DEFAULT 0,
                    n3 integer NOT NULL DEFAULT 0,
                    n4 integer NOT NULL DEFAULT 0
					
                   
                )
                ");

       for(i in 0...1000){
			
		//for (e in pArray) {
			var q = 'INSERT INTO fa_game (n1,n2,n3,n4) VALUES(${i},${i+1},${i+2},${i+3})';

			// trace(q);
			var rs = cnx.request(q);

			

			
		}

@ConstNW  ?

**Comment by ConstNW** [comment]
remove final space from query `"PRAGMA journal_mode=WAL; "`
It will be better not use semicolon in queries
