### ISSUE TITLE
sqlite repeat request same content  will got wrong result!

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#315]
look at this code.

             var q = 'select * from fa_game order by RANDOM()';

		var rs = cndb.request(q);

		//trace(rs.length); //if I remove this code ,and put the trace below ,will got wrong result 

		var q2 = 'select * from fa_game order by RANDOM()';

		var rs2 = cndb.request(q2);
        trace(rs1.length); //here will be wrong result ,only 1;
        trace(rs2.length);//here will be right result.

@ConstNW ?

**Comment by ConstNW** [comment]
Right now sqlite lib [finalize previous request](https://github.com/HaxeFoundation/hashlink/blob/master/libs/sqlite/sqlite.c#L162)

You can use cached ResultSet if you get `length`.

**Comment by sonygod** [comment]
got!
