### ISSUE TITLE
sqlite will break threads when it's creating local file?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#316]
SQLite will break threads when it creates a local file?

    
     for (k in 0...6) {
			MainLoop.addThread(function() {
				var cnx = Sqlite.open('./klsfx8_${k + 1}.db');

				cnx.request("PRAGMA synchronous = OFF");
				cnx.request("PRAGMA locking_mode=EXCLUSIVE"); 
				cnx.request("PRAGMA journal_mode=WAL");
				cnx.request("
                CREATE TABLE IF NOT EXISTS fa_game (
                    id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                    n1 integer  NOT NULL DEFAULT 0,
                    n2 integer  NOT NULL DEFAULT 0,
                    n3 integer NOT NULL DEFAULT 0,
                    n4 integer NOT NULL DEFAULT 0,
					n5 integer NOT NULL DEFAULT 0,
                    n6 integer NOT NULL DEFAULT 0,
                    n7 integer NOT NULL DEFAULT 0,
                    n8 integer NOT NULL DEFAULT 0
                    
                   
                )
                ");
          ........

@ConstNW ?

**Comment by ConstNW** [comment]
Provided example working properly.

**Comment by sonygod** [comment]
import sys.db.Sqlite;
    import haxe.MainLoop;

    class Test2 {
        public static function main() {
            for (k in 0...6) {
                MainLoop.addThread(function() {
                    var cnx = Sqlite.open('./klsfxp_${k + 1}.db');

                    cnx.request("PRAGMA synchronous = OFF");
                    cnx.request("PRAGMA locking_mode=EXCLUSIVE");
                    cnx.request("PRAGMA journal_mode=WAL");
                    cnx.request("
                    CREATE TABLE IF NOT EXISTS fa_game (
                        id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                        n1 integer  NOT NULL DEFAULT 0,
                        n2 integer  NOT NULL DEFAULT 0,
                        n3 integer NOT NULL DEFAULT 0,
                        n4 integer NOT NULL DEFAULT 0,
                        n5 integer NOT NULL DEFAULT 0,
                        n6 integer NOT NULL DEFAULT 0,
                        n7 integer NOT NULL DEFAULT 0,
                        n8 integer NOT NULL DEFAULT 0
                        
                    
                    )
                    ");

                    var k = 0;
                    var a:Float = 0;
                    while (k < 100000000) {
                        k++;
                        a += k / 2 * 2 % 2 * Math.sqrt(2);

                        trace("can you see me fisrt time ? I don't think so!" + k); // k will not eq 100000000 anymore
                    }
                });
            }
        }
    }

**Comment by ConstNW** [comment]
it's not sqlite lib error or problem.

`trace` is not thread-safe, you should use `Lock` or `Mutex`
