### ISSUE TITLE
why not use utf-8 in sqlite instead of utf-16?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#317]
sqlite why use utf-16 instead of utf-8?

I check sqlite.c

    if( sqlite3_prepare16_v2(db->db, sql, -1, &r->r, &tl) != SQLITE_OK ) {
		HL_NAME(error)(db->db, false);
	}

why not use  sqlite3_prepare_v2 ?

@ConstNW ?   will it affect speed?

**Comment by ConstNW** [comment]
hashlink strings are UCS2
