### ISSUE TITLE
"Failed to load library openal.hdll"

### ISSUE THREAD

**Issue by deepnight** [HaxeFoundation/hashlink#318]
I pushed a new build of my app RPG Map II that uses the latest Haxe4 + Heaps + HashLink and I now get many reports of the fatal error "_Failed to load library openal.hdll_". 

https://deepnight.itch.io/tabletop-rpg-map-editor

I couldn't reproduce the issue on my install. The previous version had no issue at all. The error is the same on SDL and DirectX versions.

The content of the ZIP people download is shown below. As you can see, I bundled both **OpenAL32.dll** from the Hashlink install folder (where my hl.exe is) and **openal.hdll** (from the same source). I always did like that before, and there was no issue at all before my update to latest HL.

![image](https://user-images.githubusercontent.com/1671695/67159648-96d0ba80-f347-11e9-8ca3-c4f7734e1616.png)

**Comment by Aurel300** [comment]
Might be related to 32-bit / 64-bit issues? What HL version did you update from? Do you know what Windows version people who reported issues are using?

**Comment by ncannasse** [comment]
Yes, most likely your OpenAL32.dll is not the same platform as your
openal.dll : use the one from openal soft distribution here
https://openal-soft.org/

**Comment by deepnight** [comment]
It's the one I got from the official HL site: https://hashlink.haxe.org/#download

**Comment by deepnight** [comment]
Also, I feel a bit dumb, but where is the DLL download on OpenAL soft website? 🤔

**Comment by Aurel300** [comment]
@deepnight There is a download section on the webpage: https://openal-soft.org/#download

> Win32 and Win64 binaries are also provided
> openal-soft-1.19.1-bin.zip

**Comment by deepnight** [comment]
Now I feel really stupid 😆
