### ISSUE TITLE
 Failed to create window

### ISSUE THREAD

**Issue by shyaml** [HaxeFoundation/hashlink#319]
Ran this  hx  code

class Main extends hxd.App {
    override function init() {
        var tf = new h2d.Text(hxd.res.DefaultFont.get(), s2d);
        tf.text = "Hello World !";
    }
    static function main() {
        new Main();
    }
}

hxml  file 
-lib heaps
-lib hlsdl
-hl hello.hl
-main Main

error 
Failed to create window
Called from sdl.$Window.constructor (sdl/Window.hx line 66)
Called from hxd.$Window.constructor (hxd/Window.hl.hx line 42)
Called from hxd.$System.start (hxd/System.hl.hx line 101)
Called from hxd.$App.constructor (hxd/App.hx line 45)
Called from $Main.constructor (Main.hx line 1)
Called from $Main.main (Main.hx line 7)

**Comment by Aurel300** [comment]
Seems like a Heaps issue rather than HashLink?

**Comment by potatoelixir** [comment]
That code, in theory, should compile fine + the error was during runtime if I understand correctly. OP might want to try posting hl file to see if other can run it?

**Comment by ncannasse** [comment]
Seems like an issue with SDL2 on your computer.

Le mer. 23 oct. 2019 à 19:16, potatoelixir <notifications@github.com> a
écrit :

**Comment by shyaml** [comment]
[
[hello.zip](https://github.com/HaxeFoundation/hashlink/files/3763872/hello.zip)

](url)

the hl file is uploaded

**Comment by jefvel** [comment]
This pull request adds an error dialog showing more detailed info when sdl window creation fails: https://github.com/HaxeFoundation/hashlink/pull/320

it could be useful for tracking down what the issue is

**Comment by shyaml** [comment]
SDL_CreateWindow failed: SDL not configured with OpenGL/GLX support
is the error

**Comment by Aurel300** [comment]
@shyaml Heaps uses SDL only as a wrapper to OpenGL afaik. So if OpenGL doesn't work, there is no fallback. What is your OS? How have you installed SDL? You might have to install some GL libraries to be able to configure SDL to use GL.

**Comment by shyaml** [comment]
ubuntu 18,04  bionic

**Comment by jefvel** [comment]
have you installed `libgl1-mesa-dev` ?

**Comment by shyaml** [comment]
i have installed mesa 18.1  still getting the error

**Comment by jefvel** [comment]
and you've installed `libsdl2-2.0-0` normally?

**Comment by shyaml** [comment]
yes libsdl2  is uptodate

**Comment by shyaml** [comment]
I reinstalled SDL2 by compiling from source   and this fixed the problem  .. thanks everyone for your kind input really appreciate it
