### ISSUE TITLE
HL 64 bit on macOS

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/hashlink#32]
hl built with `ARCH=64` on macOS segfaults ([haxe group post](https://groups.google.com/forum/#!topic/haxelang/RO7vq8nwd-8)). Building with `ARCH=32` works however.

Last time I checked 64 bit wasn't quite ready but it looks like things have progressed

I'm creating this issue to help inform new macOS users (since 64 bit will be default)

**Comment by ivcoar** [comment]
It compiles using ARCH=32, but for some reason, the haxe c output compiled with gcc won't run for me because of a missing entry point and segfaults. I haven't tried it yet on my linux machine.

**Comment by anissen** [comment]
I think this is a major issue. 😞 

Haxe 3.4.0-rc.1 boasts that ["The HashLink target is now fully operational"](http://haxe.org/download/). Yet HashLink still needs to be installed separately from Haxe, there is only binaries available for Windows and it cannot be compiled and/or run on Mac.

**Comment by ncannasse** [comment]
@anissen 64 bits support is not necessary to run HL, using 32 bit compilation should work right now even on a 64 bit system. 
@ivcoar If you want to compile with to HL/C you need to compile + link hlc_main.c
