### ISSUE TITLE
int comparison to dynamic array value

### ISSUE THREAD

**Issue by hoseyjoe** [HaxeFoundation/hashlink#322]
haxe 4 using Crypto library (hl 1.10)

Hashlink appears to crash silently on  
trace( key.length * 8 == keys[0] );  
where keys[0]==["cbc"]

**Comment by ncannasse** [comment]
Please submit a reproducible example. If possible test with Git version that has some recent fixes.

**Comment by hoseyjoe** [comment]
Seems resolved or I cnat reproduce example

**Comment by hoseyjoe** [comment]
ok. Not sure its a bug in hl or cpp but there is a difference between them.  Both compile.

Main class
```haxe
package;

class Main {
    static function main() {
        trace('Hello World');
        var key="1";
        var name="1-cbc";
        var keys:Array<Dynamic> = name.split("-");
        trace( key.length * 8 == keys[0] );
        trace(" ");
    }
}
```
hxml
```haxe
-cp source
-main Main
-lib haxe-crypto
-dce full

-cpp bin/cpp/windows/debug
-cmd cd bin/cpp/windows/debug
-cmd Main.exe
-cmd cd ../../../../

--next
-cp source
-main Main
-lib haxe-crypto
-dce full
-hl bin/hl/Main.hl
-cmd cd bin/hl
-cmd hl Main.hl
```

Results
```
source/Main.hx:5: Hello World
source/Main.hx:9: false
source/Main.hx:10: 
source/Main.hx:5: Hello World
Uncaught exception: Can't cast String to f64
Called from $Main.main(Main.hx:9)
Called from fun$340(?:1)
Error: Command failed with error 1
```

**Comment by ncannasse** [comment]
Yes it's a Dynamic/Float comparison difference that cast the Dynamic (which
is a String) to Float and fails to do so. In all cases this would always be
false in HL.

Le mer. 6 nov. 2019 à 00:41, Joe Williamson <notifications@github.com> a
écrit :

**Comment by Simn** [comment]
Technically, we could generate equality checks that involve `Dynamic` as something like `!assignable(rhs, lhs) ? false : doWhatWeDoNow(lhs, rhs)`. I'm not sure if that actually improves anyone's life though...

**Comment by ncannasse** [comment]
I think we have Dynamic unit tests that should go in 4.1 and are actually
checking these kind of errors.

Le mer. 6 nov. 2019 à 09:20, Simon Krajewski <notifications@github.com> a
écrit :

**Comment by ncannasse** [comment]
Actually the problem is not Dynamic here but the fact that reading from an Array<Dynamic> will give a Unknown that will get unified with Int. We don't want to change this behavior. I think it should work with:

key.length * 8 == (keys[0] : Dynamic)
