### ISSUE TITLE
IntMap :Uncaught exception: assert

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#324]
Uncaught exception: assert
      Called from haxe.ds.IntMap.set(C:\HaxeToolkit\haxe\std/hl/_std/haxe/ds/IntMap.hx:34)

**Comment by ncannasse** [comment]
Are you using HL GIT and Haxe 4.0 ? There's no throw assert here, and GC fatal errors should not trigger this exception. A reproducible sample is required.

**Comment by jonasmalacofilho** [comment]
@sonygod when trying to construct a minimal example it might help you to know that the assert in question is _probably_ this one:

https://github.com/HaxeFoundation/hashlink/blob/7ff761453007842d443886655dd571b0b08d7131/src/std/maps.h#L75

**Comment by jonasmalacofilho** [comment]
Actually, @ncannasse, in

https://github.com/HaxeFoundation/hashlink/blob/7ff761453007842d443886655dd571b0b08d7131/src/std/maps.h#L77-L87

shouldn't `m->nentries` also be set to `nentries`?

**Comment by sonygod** [comment]
I will make a  reproducible sample soon.

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/68820948-d3ce6980-06c7-11ea-88f2-003e08a445bc.png)

found another issue

I use IntMap in MainLoop.addThread ()

**Comment by ncannasse** [comment]
Accessing the same IntMap within different threads is not safe and should
be protected with mutexes

**Comment by sonygod** [comment]
mute seem will block my code and stop run

    	function run() {
		if (mute.tryAcquire()) {
			for (key => v in map) {
				if (v == null) {
					map.remove(key);
				} else {
					v.dt += t;
					if (v.dt >= v.delay) {
						v.func();
						if (!v.keep) {
							map.remove(key);
						}
						v.dt = 0;
					}
				}
			}
			mute.release();
		}
	}

**Comment by sonygod** [comment]
use thread with mutexes fixed.
