### ISSUE TITLE
undefined reference to `fmt_dxt_decode'

### ISSUE THREAD

**Issue by Algorythmis** [HaxeFoundation/hashlink#326]
`ld` throws an error when attempting to compile an executable from C code generated by hashlink through the following command:

    gcc main.c -o ../main -I.  \
    /usr/share/hashlink/sdl.hdll    \
    /usr/share/hashlink/ui.hdll     \
    /usr/share/hashlink/fmt.hdll    \
    /usr/share/hashlink/openal.hdll \
    /usr/share/hashlink/ui.hdll     \
    /usr/share/hashlink/uv.hdll     \
    -lhl -lSDL2 -lm -lopenal -lGL

(as stated [here](https://github.com/HaxeFoundation/hashlink/issues/124#issuecomment-433626424))

Here's the error message:

    /usr/bin/ld: /tmp/cc5bQv9y.o: in function `hxd_Pixels_convert':
    main.c:(.text+0x211d9): undefined reference to `fmt_dxt_decode'
    /usr/bin/ld: main.c:(.text+0x2139f): undefined reference to `fmt_dxt_decode'
    /usr/bin/ld: /tmp/cc5bQv9y.o: in function `hl_Mikktspace_compute':
    main.c:(.text+0x16197a): undefined reference to `fmt_compute_mikkt_tangents'
    /usr/bin/ld: /tmp/cc5bQv9y.o:(.data.rel+0x6418): undefined reference to `fmt_dxt_decode'
    /usr/bin/ld: /tmp/cc5bQv9y.o:(.data.rel+0x6428): undefined reference to `fmt_compute_mikkt_tangents'
    collect2: error: ld returned 1 exit status

How should I link fmt in this case?

**Comment by ncannasse** [comment]
Seems like fmt is missing dxt.c

Le mer. 13 nov. 2019 à 21:28, Algorythmis <notifications@github.com> a
écrit :

**Comment by booti386** [comment]
This issue is fixed by https://github.com/HaxeFoundation/hashlink/pull/327

**Comment by Algorythmis** [comment]
Thanks for the very quick fix. It does fix the problem for dxt.c but the one about mikkt.c stays:

    /usr/bin/ld: /tmp/ccyPEGig.o: in function `hl_Mikktspace_compute':
    main.c:(.text+0x170099): undefined reference to `fmt_compute_mikkt_tangents'
    /usr/bin/ld: /tmp/ccyPEGig.o:(.data.rel+0x6428): undefined reference to ` fmt_compute_mikkt_tangents'

I would like to make a merge request for that but I'd need the mikktspace.h header, which I guess I could get from [there](https://github.com/teared/mikktspace-for-houdini/blob/master/source/mikktspace.h) but then I'd probably have to build the whole repo, and I don't know Houdini at all.

**Comment by ncannasse** [comment]
The mikkt sources can be found in hashlink include directory. Will requires
both header and sources.

Le mer. 13 nov. 2019 à 22:28, Algorythmis <notifications@github.com> a
écrit :

**Comment by Algorythmis** [comment]
Fixed it with #328.
