### ISSUE TITLE
[debug]after update new version,some hl file not support debug?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#329]
[debug]after update new version,some hl file not support debug?

I not update the lasted  git now ,

and got this error .

![image](https://user-images.githubusercontent.com/748320/69054480-9a3e8b00-0a46-11ea-895e-c8687616c763.png)

![image](https://user-images.githubusercontent.com/748320/69054616-f43f5080-0a46-11ea-82e9-f9c6b83b45f8.png)

![image](https://user-images.githubusercontent.com/748320/69054774-4b452580-0a47-11ea-86b8-f3e0207f68ea.png)

haxe 4.1 bugfixed

hl : 11-14 version
![image](https://user-images.githubusercontent.com/748320/69054533-bf32fe00-0a46-11ea-8076-2cd30b054664.png)

**Comment by ncannasse** [comment]
Right, that's actually @:struct class that is not yet supported by the
bytecode reader. Will fix but won't make a release immediately.

**Comment by sonygod** [comment]
thanks ,only use @:struct for cs target fixed
