### ISSUE TITLE
Plans for embedding API

### ISSUE THREAD

**Issue by sauer2** [HaxeFoundation/hashlink#33]
There was a [thread](https://www.reddit.com/r/programming/comments/5f15wi/the_new_haxe_target_hashlink_indepth_part_1/) about HashLink on Reddit where someone suggested an API for embedding the HashLink runtime into other software.

Mentioning Mono, HashLink might be an interesting alternative, as it seems to promise roughly about the same level of performance.
Is an API like this planned or does it already exist?

**Comment by ncannasse** [comment]
Right now the JIT is not part of the runtime, but you can look at how it's embedded by the `hl` vm binary here: https://github.com/HaxeFoundation/hashlink/blob/master/src/main.c

**Comment by sauer2** [comment]
@ncannasse Thanks for you response.

>Right now the JIT is not part of the runtime,

What do you mean by this? JIT as in the component emitting the code into memory? Something like GNU lightning?

**Comment by ncannasse** [comment]
@sauer2 yes, the HL VM is JIT powered

**Comment by sauer2** [comment]
@ncannasse No, what I mean is that your comment above sounds like the JIT compiler is somehow separated from the rest of the interpreter. And that sounded strange, to be honest.

**Comment by ncannasse** [comment]
The HL runtime library contains the GC and the HL standard library, it is used by both the HL JIT VM and when compiling to HL/C. Since the later does not require a JIT or a bytecode reader, it's not integrated in `libhl` but in `hl` binary which is the JIT VM which links to libhl

**Comment by sauer2** [comment]
Ah, so it's because by runtime you mean the libraries required to run the code.

Makes sense, I guess.
Thank you for your time.

**Comment by ncannasse** [comment]
I have added the necessary documentation for embedding here:
https://github.com/HaxeFoundation/hashlink/wiki/Embedding-HashLink
