### ISSUE TITLE
[sqlite] not support Date type format 

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#334]
CREATE TABLE IF NOT EXISTS fa_shopcar (
            id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
			uid integer  NOT NULL DEFAULT 0,
			goods_id integer  NOT NULL DEFAULT 0,
			num integer  NOT NULL DEFAULT 0,
			ip TEXT NOT NULL,
			create_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
			update_time DATETIME,
			status integer  NOT NULL DEFAULT 1,
			coins integer  NOT NULL DEFAULT 0,
			parent_id integer  NOT NULL DEFAULT 0
   
//----------------------------

	   var q = 'SELECT * from fa_shopcar WHERE uid=$uid ORDER BY id  DESC limit 1';

		var rs = cnx.request(q);

		if (rs.length > 0) {
			for (e in rs) {
				var coins:Int = e.coins;
                var time:Date=e.create_time;//will crash or throw error!
			
			}
		}

@ConstNW ?

![image](https://user-images.githubusercontent.com/748320/70372700-84253b80-191d-11ea-9e3d-68f7a22362b1.png)

**Comment by ConstNW** [comment]
#278

**Comment by sonygod** [comment]
also ,it's seem not support 

      ORDER BY (date format)

@ConstNW
