### ISSUE TITLE
CI failure on "Print Haxe Version"

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hashlink#346]
Ping @andyli , thanks ;)

**Comment by Simn** [comment]
I thought that this could be about the mbedtls integration, but it started failing on this commit from 3 weeks ago, which was before I merged the SSL stuff: https://github.com/HaxeFoundation/hashlink/commit/f75392b60eebc1acd76f686a3809fc493d4a9f91

So unless you had that as a local commit and only pushed that recently, the problem must be something else.

**Comment by Simn** [comment]
Fixed in Haxe.

I guess you did indeed sit on this commit.
