### ISSUE TITLE
sqlite.hdll not included

### ISSUE THREAD

**Issue by novemberisms** [HaxeFoundation/hashlink#347]
Trying to test out sqlite for my Heaps.io game and running it outputs the error: `src/module.c(337) : FATAL ERROR : Failed to load library sqlite.hdll`

After some searching, apparently it's because `sqlite.hdll` is not being built despite being in hashlink/libs

I'm a noob at all this, so can someone explain to me how to build it myself and how to get it working with hashlink? I'm using a Mac. I tried `make && make install` but sqlite.hdll is not being built. What do I do?

**Comment by ConstNW** [comment]
take a look #323
