### ISSUE TITLE
[socket]@:hlNative("std", "socket_peer") static function socket_peer return wrong port!

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#349]
@:hlNative("std", "socket_peer") static function socket_peer return wrong port!

every time I call 

       socket.peer()

will get difference port?

**Comment by Aurel300** [comment]
Can you post a full example?

**Comment by sonygod** [comment]
work with lib hxWebSockets ,same hander, it's should be same port,

 

    function toPort(hander:IHander):Int {
        var ws:WebSocketCommon = cast hander;
        var socket:Socket = @:privateAccess ws._socket;
        var h = socket.peer();

        return h.port;
    }

**Comment by Aurel300** [comment]
Well, it really depends. If you do that `socket.peer()` call multiple times **in the same function**, does it return different values? If yes, then that looks like some random memory reading, but the implementation of `hl_socket_peer` looks ok to me.

But if this is a server you are running, then it may be that you have a server listening on a particular port, say 80, and clients connecting to this server. The actual remote port of the client (i.e. the `peer`) is basically random and is different for each connection. Usually these temporary, random port numbers are higher than 1024 (or even 10000), in order not to inferfere with actual services that are listening on well-known port numbers.

**Comment by ncannasse** [comment]
class Main {
	static public function main() {
		var s = new sys.net.Socket();
		s.connect(new sys.net.Host("google.com"),80);
		trace(s.peer());
		trace(s.peer());
	}
}

Not reproducible, both print 80 correctly.
