### ISSUE TITLE
Windows HL — SQLite request — Random errors

### ISSUE THREAD

**Issue by Illuday** [HaxeFoundation/hashlink#352]
HL 1.10 — Windows 10 — Testing on my project and a fresh project

_Making a SQLite request returns random errors._ The request works well, I can trace and see my datas in the debugger, but when the execution end, a **violation access** error is thrown.

```js
var DB = Sqlite.open('database.db');
var req = DB.request('SELECT * FROM inventory');

for( item in req ) {
    trace("Item "+item.name);
}
```

>`Game.hx:48: Item leather`
>`Game.hx:48: Item glass`

Then the random errors (I just push reload 3 times)
> ObjectMap.hx
![image](https://user-images.githubusercontent.com/2337414/76456230-fdc63d00-63d6-11ea-9729-44b375039069.png)
> ArrayObj.hx
![image](https://user-images.githubusercontent.com/2337414/76456307-12a2d080-63d7-11ea-9e08-c815e0a5018f.png)
> Linker.hx
![image](https://user-images.githubusercontent.com/2337414/76456349-23534680-63d7-11ea-8acc-0fc5c3326f29.png)

Note :
- It works when running in a static method (like main())
- There is no error if I only keep the DB open
- I tried to recreate the database and to use an external DB

**Comment by ConstNW** [comment]
it's already fixed by this commits: 
https://github.com/HaxeFoundation/hashlink/commit/46e35969a2e72e8aae310c1db61f6c98d67af49e
https://github.com/HaxeFoundation/hashlink/commit/6d0a1d9dda309700e6258fe7066cff7524d8b11d
https://github.com/HaxeFoundation/hashlink/commit/b70a6f81a8f9847eef7da434351678a1c4ae6588

**Comment by Illuday** [comment]
Is there an easy way to get the sqlite.hdll modified ?

**Comment by ConstNW** [comment]
You can take a look on "nightly builds" at azure pipeline [artifacts](https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=3135&view=artifacts&type=publishedArtifacts)

**Comment by Illuday** [comment]
Do you have any solution to solve this error : 

`D:\a\1\s\src\module.c(472) : FATAL ERROR : Failed to load function fmt@compute_mikkt_tangents`

It happens on all nightly I tested.

**Comment by Aurel300** [comment]
@Illuday Sounds like you might need to download the `fmt.hdll` as well? And any other `hdll` for similar errors.

**Comment by Illuday** [comment]
> @Illuday Sounds like you might need to download the `fmt.hdll` as well? And any other `hdll` for similar errors.

I took every libraries from the nightly including fmt.hdll, I made a fresh install with the nightly.

**Comment by ConstNW** [comment]
it's fmt.hdll compilation problem on windows 
will fix by #353

**Comment by Illuday** [comment]
Ok now it's openal.hdll time (failed to load).

Any recommandations to get it up to date ?

**Comment by ConstNW** [comment]
did you put OpenAL dll in hl dir?

**Comment by Illuday** [comment]
Yes, and I tested many things about it : 

![image](https://user-images.githubusercontent.com/2337414/76503025-5a604100-6445-11ea-9ffa-081f9fde492b.png)

**Comment by Illuday** [comment]
I did a clean install with the last nightly, but it always throw :

>  D:\a\1\s\src\module.c(352) : FATAL ERROR : Failed to load library openal.hdll

Is there anything particular with this dll?

**Comment by ConstNW** [comment]
i think u should close this issue and start new one.

also check this one #255
