### ISSUE TITLE
Windows HL — Failed to load library openal.hdll

### ISSUE THREAD

**Issue by Illuday** [HaxeFoundation/hashlink#355]
HL 1.10 — Using nightly

I did a clean install with the last nightly, but it always throw :

```
D:\a\1\s\src\module.c(352) : FATAL ERROR : Failed to load library openal.hdll
```

Openal.hdll is obviously in the same folder as hl.exe

![image](https://user-images.githubusercontent.com/2337414/76549086-0a5a9c00-6490-11ea-87a6-d7e4f310da36.png)

**Comment by ConstNW** [comment]
you forget about OpenAL32.dll

**Comment by Illuday** [comment]
Even if I put OpenAl32.dll in the folder, it keeps throwing that it failed to load openal.hdll.

Is there a version problem ?

**Comment by Gama11** [comment]
@Illuday I see you closed the issue, does that mean you found a solution? What was it?

**Comment by Illuday** [comment]
I was using a 32bit OpenAl32.dll, in a Hashlink Nightly 64bit, I wasn't able to make my nightly 64bit work, so I took a 32bit one, and now it's working.
