### ISSUE TITLE
C# doesn't work as a target

### ISSUE THREAD

**Issue by laughsuggestion** [HaxeFoundation/hashlink#356]
Tried building:

```
-lib heaps
-lib hlsdl
-cs out/magepunk.cs
-main src.Main
```

And get this as a result:

```
C:\HaxeToolkit\haxe\lib\hlsdl/1,10,0/sdl/Cursor.hx:3: characters 29-54 : You cannot access the hl package while targeting cs (for hl.Abstract)
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/hxd/Cursor.hx:26: characters 20-30 :     referenced here
```

**Comment by Aurel300** [comment]
`hlsdl` is a HashLink-specific library (that's what the `hl` stands for). HashLink is a separate Haxe target, so libraries written for HashLink will not/cannot work on C#. `heaps` is a library that works on HashLink, Flash/AIR, and JavaScript, so it too cannot work on C#.

**Comment by laughsuggestion** [comment]
> `hlsdl` is a HashLink-specific library (that's what the `hl` stands for). HashLink is a separate Haxe target, so libraries written for HashLink will not/cannot work on C#. `heaps` is a library that works on HashLink, Flash/AIR, and JavaScript, so it too cannot work on C#.

Oh, I thought the hl stood for "haxe lib" or something like that. My mistake, I'm still trying to figure out the haxe ecosystem. This definitely helps. Thank you :)

**Comment by ncannasse** [comment]
This is unrelated to hashlink ;)
