### ISSUE TITLE
substr on Dynamic errors with Missing arguments

### ISSUE THREAD

**Issue by rushmobius** [HaxeFoundation/hashlink#357]
Given the following.

`
var s:String = "12345";
var arr:Array<Dynamic> = s.split(".");
var f:String = arr[0].substr(arr[0].length - 3);
`
The substr throws an exception 'Missing arguments : 3 expected but 2 passed'
I can avoid it by changing the `Array<Dynamic>` to `Array<String>`, but the error was unexpected.

**Comment by rushmobius** [comment]
Forgot to mention, this is on 1.10 and have 4.0.5

**Comment by ncannasse** [comment]
This is by design : HL does not support optional arguments for dynamic calls.
