### ISSUE TITLE
Array iterator has wrong length for non static types when modified

### ISSUE THREAD

**Issue by rushmobius** [HaxeFoundation/hashlink#358]
Haxe 4.0.5/Hashlink 1.10
The following code should trace 1 2 3, but it fails as the iterator has the wrong length after the arr.push.
This works correctly if I change the Array to Array<Int and Iterator<Int>
`
var arr:Array<Dynamic> = [1,2];
var it:Iterator<Dynamic> = arr.iterator();

while (it.hasNext())
{
    var v:Int = it.next();

    if (v == 1)
         arr.push(3);

    trace(v);
}
`

**Comment by rushmobius** [comment]
Actually looks like this is fixed in ArrayDyn.hx just not released. The comments though consider it to be undefined behavior which I find odd as it works on the other targets i've tested

**Comment by Gama11** [comment]
>just not released

Well, HL 1.11 was _just_ released. :) https://github.com/HaxeFoundation/hashlink/releases/tag/1.11
