### ISSUE TITLE
gc_save_context might miss some registers

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/hashlink#359]
Just so we don't forget about this, although it is probably a rare bug that most likely only happens on OS X or Linux compiling under clang (maybe).

https://github.com/HaxeFoundation/hashlink/blob/3f0b6a96525d91bc300ab070c4b7fff2e3b943b1/src/gc.c#L210-L213

This is problematic because it may get compiled as:

```asm
push rbp
mov rbp, rsp
push rbx ; callee saved RBX
push rax
mov rbx, rdi ; RBX trashed
mov [rbp+var_10], rbx
lea rdi, [rbx+70h]
call _setjmp ; should save local context ...
lea rax, [rbp+var_10]
mov [rbx+10h], rax
add rsp, 8
pop rbx
pop rbp
retn
```

So if, coming into this function, RBX happens to store a GC-allocated variable, `gc_save_context` will miss it because it is temporarily stored on the stack in `gc_save_context` and `setjmp` only saves registers, and after returning from `gc_save_context` the RBX value will be gone forever.

Thread marking needs to happen with the full stack (up to `setjmp`, including callee-saved registers).

**Comment by ncannasse** [comment]
If you have some reproducible code, could you try with my fix ?
