### ISSUE TITLE
HL/JIT 64 bits

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hashlink#36]
While the HL bytecode, runtime and std library are compatible with both 32 and 64 bits compilation, the current JIT is limited to 32 bits and would require some additional work to fully support 64 bits CPU.

**Comment by oxitech239** [comment]
is there such work in progress, to have HL fully supported on 64 bit CPU ?

**Comment by ncannasse** [comment]
Hugh is using SLJIT in hx/cppia/CppiaCompiler, that might be interesting to look at.

**Comment by ncannasse** [comment]
Done in 1.4
