### ISSUE TITLE
Problems building custom hdll

### ISSUE THREAD

**Issue by josuigoa** [HaxeFoundation/hashlink#360]
Hi!

I've built [bullet.hdll](https://github.com/heapsio/bullet) correctly from command line executing the sln file. But when I execute the app it says that bullet.hdll could not be found. I've also built a simple hdll from scratch in the same system and it works when executing. It seems that is not a 32/64 bit incompativility. I don't know what can it be or what should I try. Any hint?

**Comment by ncannasse** [comment]
Make sure that bullet.hdll is built with same arch as hashlink runtime.

**Comment by josuigoa** [comment]
I'm pretty sure that I compiled bullet for 64 bits and HL 1.11 is also 64
bit, isn't it? But I will try every conbination when I get back to the PC
to be 100% sure.

Nicolas Cannasse <notifications@github.com> igorleak hau idatzi zuen (2020
api. 9, og. 20:41):

**Comment by josuigoa** [comment]
These are the architectures 
![arch](https://user-images.githubusercontent.com/3088505/79206302-6f166700-7e3f-11ea-95fe-9e537e8c72a4.png)

And these are the dependencies. `hlext.hdll` is the extension I built from [scratch](https://github.com/josuigoa/hl-extension/). I see that the last depencencies are not the same, but I have both of them in my machine.
![deps](https://user-images.githubusercontent.com/3088505/79206308-70479400-7e3f-11ea-8aee-efa4fff819b1.png)

**Comment by josuigoa** [comment]
I've seen it is my configuration problem. I'm closing this
