### ISSUE TITLE
Question about threading and gc

### ISSUE THREAD

**Issue by malikzh** [HaxeFoundation/hashlink#363]
Hello! I use hashlink in my c/c++ project, and i have question about threads and gc.

I used main.c as example for hashlink initialization.

In my new thread i wrote this code (like a `hl_thread_start()`):

```c
void thread_func() {
// CODE INT THREAD
hl_register_thread(&some_thread);

hl_dyn_call(someClosure, NULL, 0);

hl_unregister_thread();
}

```
Closure has one line code, it's a:

```haxe
trace('test123');
```

Now, when i create more threads, i get "deadlock" at gc.c:324 `gc_stop_world()`:

```c
for(i=0;i<gc_threads.count;i++) {
			hl_thread_info *t = gc_threads.threads[i];
			while( t->gc_blocking == 0 ) {}; // spinwait
		}

(gdb) print i
i = 0
```

I realized the problem occurs when the `gc_major()` method is called. I tried calling the method directly in thread `hl_gc_major()`. Behavior repeated.

How properly initialize a custom thread for make `hl_dyn_call() / hl_dyn_call_safe()`?

Thanks.

**Comment by ncannasse** [comment]
HL threads needs to be cooperative, in the sense that they each need to either be in a hl_thread_blocking section or regularly allocate gc memory, as they must "rendez-vous" when one of the threads requires a major GC.

In your case, it seems one of your threads is blocking and so the others are waiting for it.

Another problem is if some exception occurs in someClosure.

**Comment by malikzh** [comment]
Thank you very much for the detailed answer.
