### ISSUE TITLE
can I get more detail of hl error?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#364]
SIGNAL 11
    database.BackDataServer.close(database/BackDataServer.hx:406)
    database.$BackUpDataServer.main(database/BackUpDataServer.hx:575)
    fun$1738(?:1)

all I got is **SIGNAL 11**  don't know why I got this ,I just call  

     cnx.close;//mysql close connect 

and I do a small test ,and can't reducde same error in my real project.

and I add some  **-D hl-check** ,not work.

**Comment by ncannasse** [comment]
Signal 11 is a segfault
