### ISSUE TITLE
Reflect.callMethod doesn't work in Hashlink target

### ISSUE THREAD

**Issue by guifes** [HaxeFoundation/hashlink#365]
```haxe
var f = Reflect.field(Math, 'cos');
trace(Reflect.callMethod(Math, f, [1]));
```

This snippet crashes with the following error in runtime:
```
Uncaught exception: Invalid function null
Called from $Reflect.callMethod(/usr/local/lib/haxe/std/hl/_std/Reflect.hx:63)
Called from $Main.__constructor__(Main.hx:48)
Called from $DocumentClass.__constructor__(ApplicationMain.hx:267)
```

Works fine in cpp and html5 target though.

**Comment by kevinresol** [comment]
More importantly, this comes from the official example of hscript:
https://github.com/HaxeFoundation/hscript#example

**Comment by ncannasse** [comment]
Did you compile with -dce no ?

Le jeu. 23 avr. 2020 à 03:54, Kevin Leung <notifications@github.com> a
écrit :

**Comment by guifes** [comment]
I'm compiling with whatever lime/openfl uses by default.

**Comment by ncannasse** [comment]
You need to add -dce no or else the Math.cos function is optimized out.

**Comment by NotHyper-474** [comment]
Seems to be related to https://github.com/HaxeFoundation/hscript/issues/96, even with `-dce no` Reflection on `@:hlNative` functions doesn't work in HashLink.
