### ISSUE TITLE
jit error with string default value for Dynamic argument

### ISSUE THREAD

**Issue by JeriXNet** [HaxeFoundation/hashlink#37]
Tried to run my project on hl and got this error:
```
JIT ERROR 8 (jic.c line 2495)
```
Here is minimal test code:
```
class Main {
    static function main() {
        test('oops');
    }
    static function test(msg:Dynamic = '') {
        trace('test ' + msg);
    }
}
```
hxml:
```
-main Main
-hl main.hl
```
and it runs ok on neko with this hxml:
```
-main Main
-neko main.n
```

**Comment by ncannasse** [comment]
Which version of HL are you using?

**Comment by JeriXNet** [comment]
it's `hl-1.0-win32.zip` from http://hashlink.haxe.org/ download link

**Comment by ncannasse** [comment]
Ah, ok, I can reproduce now although it's a different message on HL GIT `JIT ERROR 8 (jic.c line 2489)`
