### ISSUE TITLE
Linux - sdl.hdll: undefined reference to `SDL_GetWindowOpacity'

### ISSUE THREAD

**Issue by lukehayes** [HaxeFoundation/hashlink#376]
I'm trying to compile the HashLink/C version of a simple program but I am getting this error:

`    /usr/local/lib/sdl.hdll: undefined reference to `SDL_GetWindowOpacity'`
    `/usr/local/lib/sdl.hdll:` undefined reference to ``SDL_SetWindowOpacity'`

I am using this to compile:

`gcc -I out out/main.c -o main -I.  /usr/local/lib/sdl.hdll  /usr/local/lib/ui.hdll  /usr/local/lib/fmt.hdll/usr/local/lib/openal.hdll  /usr/local/lib/ui.hdll  /usr/local/lib/uv.hdll -lhl -lSDL2 -lm -lopenal -lGL`

I've noticed when I re run `make all` on the hasklink source I get this:

```
libs/sdl/sdl.c: In function ‘sdl_win_get_opacity’:
libs/sdl/sdl.c:540:2: warning: implicit declaration of function ‘SDL_GetWindowOpacity’ [-Wimplicit-function-declaration]
  SDL_GetWindowOpacity(win, &opacity);
  ^
libs/sdl/sdl.c: In function ‘sdl_win_set_opacity’:
libs/sdl/sdl.c:545:9: warning: implicit declaration of function ‘SDL_SetWindowOpacity’ [-Wimplicit-function-declaration]
  return SDL_SetWindowOpacity(win, (float)opacity) == 0;
         ^
```

What am I doing wrong?

**Comment by ncannasse** [comment]
Seems like you need SDL 2.0.5 for this

Le mer. 29 avr. 2020 à 21:46, Luke Hayes <notifications@github.com> a
écrit :

**Comment by lukehayes** [comment]
> Seems like you need SDL 2.0.5 for this

@ncannasse - That has solved it. It's all working well now - thank you for your help :+1:
