### ISSUE TITLE
[hlc]undefined reference to `hl_is_prim_loaded'

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#380]
/var/tmp/ccTbRxPO.o:(.data.rel+0x1b58): undefined reference to `hl_is_prim_loaded'

after update hl 1.12.0,I got this error.       -D hl-ver=1.11.0  to -D hl-ver=1.12.0

       gcc -O3 -o Database_BackUP -std=c11 -I out out/main.c -lhl /usr/lib/*.hdll

**Comment by ncannasse** [comment]
You haven't updated your system libhl

**Comment by sonygod** [comment]
thanks ,I'll try.
