### ISSUE TITLE
Array.map and hashlink?

### ISSUE THREAD

**Issue by rushmobius** [HaxeFoundation/hashlink#383]
As the haxe std Array class is an extern with an inline map method, it seems this method will only work for hashlink when both types are the same?

The following code works on most of the haxe targets but will fail at runtime on the s.map call since it isn't @:generic.
The only solution i can determine is to not use Array.map or Array.filter in favor of a custom util method that I can annotate with @:generic. This also means I would need to update any 3rd party haxe libraries I currently use.

Thoughts?
```
class Test {
    static function main() {
        trace("Haxe is great!");
        
        var s:Array<String> = ["1", "2"];
        
        var i:Array<Int> = s.map(Std.parseInt);
        
        trace(i.length);
    }
}
```

**Comment by nadako** [comment]
This should work.

**Comment by Simn** [comment]
What error do you get from this?

**Comment by rushmobius** [comment]
Can't cast hl.types.ArrayObj to hl.types.ArrayBytes...
I have fixed this in other cases by annotating the method with @:generic

**Comment by rushmobius** [comment]
I should state, this is with haxe 4.0.5 and hashlink 1.10

**Comment by Simn** [comment]
Hmm yes I can reproduce that...

**Comment by Simn** [comment]
This only reproduces because `parseInt`'s return type is `Null<Int>`.

**Comment by RealyUniqueName** [comment]
The issue is `s.map(Std.parseInt)` creates an `Array<Null<Int>>`
changing to 
```haxe
var i = s.map(Std.parseInt);
```

**Comment by rushmobius** [comment]
I'm blind ;P
I completely missed the Null<>. Thanks folks

**Comment by rushmobius** [comment]
Though it would be nice if we can enforce a strict or compile time error.

**Comment by nadako** [comment]
Right, this should NOT work (and even compile, to be honest) :)

**Comment by RealyUniqueName** [comment]
See https://github.com/HaxeFoundation/haxe/issues/6785
