### ISSUE TITLE
PTiA_D required but PTiAi_D found in hdll

### ISSUE THREAD

**Issue by starburst997** [HaxeFoundation/hashlink#39]
Under Linux, the HelloWorld example works perfectly, ./hl hello.hl would output 
```
HelloWorld.hx:2: Hello world!
```

But trying a more complex program like the "Base2D" example from [Heaps](https://github.com/ncannasse/heaps), this is the output:
```
src/module.c(277) : FATAL ERROR : Invalid signature for function std@alloc_enum : PTiA_D required but PTiAi_D found in hdll
```

Seems like all program that I try to run under hashlink that are more than simple console program output this error.

**Comment by Garry-H** [comment]
I am having the same problem with the "Base3D" example from Heaps.

**Comment by ncannasse** [comment]
I have made this change in HL on 12/3 so you might need latest Haxe + latest HL

**Comment by Garry-H** [comment]
I just installed the most recent versions of Hashlink, Heaps, and Haxe 3.4, yesterday. Anything else we could try, to fix the issue? Does Hashlink still rely on nightly?

**Comment by starburst997** [comment]
I'm pretty sure I had the latest version from GIT of Haxe rebuilt manually from my machine, but I can try again later.

Also, from the website it is mentioned that we can build from C.
```
gcc -o myapp hlruntime.a output.c
```

Where is this 'hlruntime.a' file or how can we compile it? 

I was able to get something to compile (by linking the libhl.so file and including the 'src' folder of HL) but I always ended up with segmentation fault or illegal hardware instruction when trying to run the compiled program.

**Comment by ncannasse** [comment]
PTiAi_D is the new signature (one additional int parameter) so it seems you have latest hashlink but not latest haxe. 

In order to link you need  hlc_main.c, I'll update the website

**Comment by ciscoheat** [comment]
I have the same problem, but I see that the binary at https://github.com/HaxeFoundation/hashlink/releases is for 3.4 RC 1 (I'm using RC 2). Could that be a reason? Exact error message: 

```
src\module.c(228) : FATAL ERROR : Invalid signature for function std@alloc_enum : PTiAi_D required but PTiA_D found in hdll
```

**Comment by ncannasse** [comment]
Yes, I made several changes, i'm waiting for 3.4 final to update hashlink binaries
