### ISSUE TITLE
Supporting WinRT ?

### ISSUE THREAD

**Issue by Linuxydable** [HaxeFoundation/hashlink#390]
Hello,

I have a question about Hashlink.
There is a possibility to support WinRT (Windows Runtime) for UWP (Universal Windows Platform) ?
Supporting WinRT can make UWP apps for Windows 10 and Xbox One.

This is can be usefull for indies developers using Heaps.
Also I'm trying to support WinRT on Hashlink but... I'm not a professional C/C++ Developer...

WinRT Github Repo : [https://github.com/microsoft/cppwinrt/](https://github.com/microsoft/cppwinrt/)
WinRT Microsoft Docs : [https://aka.ms/cppwinrt](https://aka.ms/cppwinrt)

P.S. : I'm sorry for my bad English because I'm French.

**Comment by ncannasse** [comment]
HashLink already supports XBox One but does not support UWP API
You need to be a registered XBox Developper to get access to the HashLink/Xbox sources (which allows writing games with Heaps.io using HL/C)
