### ISSUE TITLE
JIT ERROR 0 (jit.c line 1197) copy(fpu,cpu)

### ISSUE THREAD

**Issue by seanpringle** [HaxeFoundation/hashlink#391]
Ubuntu 20.04
Haxe 1:4.0.5-1 (stock package)
hashlink: 1.11 (built from source)

I tried to convert an array of `Float` to `Single` and encountered:
```
copy(fpu,cpu)
JIT ERROR 0 (jit.c line 1197)
```

An equivalent HL/C build appears to run fine.

Any tips how I can debug this? Unsure where to start as the array in question -- entity vec3 positions -- is used all over the place, and the JIT error doesn't give much context.

**Comment by ncannasse** [comment]
Can you reproduce with minimal Haxe code?


Le mer. 17 juin 2020 à 07:53, seanpringle <notifications@github.com> a
écrit :

**Comment by seanpringle** [comment]
Actually yes (accidentally):  https://github.com/seanpringle/hashlink391

I noticed stubbing out my `Box.centroid` method allows Hashlink to run.

In case it matters, the `Position` type is more complex in the original code and wraps `hl.Bytes` with `F32` fields instead of `hl.NativeArray`.

**Comment by PXshadow** [comment]
Any update on this, ran into this on HL/JIT 1.11.0 on macos

**Comment by ncannasse** [comment]
I couldn't reproduce the original posted sample using haxe 4.1.5 and HL master. Please repost a reproducible sample as a new issue.

**Comment by PXshadow** [comment]
It was fixed on mac, when compiled from source, brew version is most likely outdated.
