### ISSUE TITLE
windows 32 bit dropped?

### ISSUE THREAD

**Issue by vontoGH** [HaxeFoundation/hashlink#392]
since 1.11 HL is released for x64 only, is there a 32 bit version somewhere? Or is 32 bit dropped for HL?

**Comment by ncannasse** [comment]
32 bit still works but you need to build it yourself. We are not planning
to keep on distributing both binaries.

**Comment by nanjizal** [comment]
Lots of GL code uses Float32Array ( especially webgl ), but if Floats are 64, I am wondering how it's best approached, it's nice to have structures that map between cpp, hl, js, currently I am concerned it maybe a bane of my gl outside web issues. Can you define Float size in Haxe to be 32bit for all code via compiler and it still be ok on 64 HL?

**Comment by nanjizal** [comment]
Also it's not ideal that each toolkit and haxe library have different Float32Array Int16Array etc.. that are compatible with haxe.io ones only on html5 not on HL or Cpp.  Would be ideal if could work out commonality between toolkits, it would be better for community.

**Comment by ncannasse** [comment]
32/64 bits doesn't change anything wrt either Float or Int size in HL

**Comment by nanjizal** [comment]
I got some complaints about f64 structures not compatible with Float32Array but that may well have been cpp.
