### ISSUE TITLE
Implement profiler output for Linux

### ISSUE THREAD

**Issue by abarichello** [HaxeFoundation/hashlink#402]
Feature request for the profiler to be included in the Linux version, as mentioned by the wiki it's windows only: 
`Profiler is introduced in HL 1.11 and only implemented for Windows so far, see src/profile.c to contribute other platforms.`
So the only thing left for the profiler to work on Linux is translating the `#ifdef HL_WIN` parts of `profile.c` or is there something else?

**Comment by ncannasse** [comment]
Yes exactly.

Le lun. 20 juil. 2020 à 05:28, BARICHELLO <notifications@github.com> a
écrit :
