### ISSUE TITLE
hl: symbol lookup error. hl_prim_not_loaded

### ISSUE THREAD

**Issue by tong** [HaxeFoundation/hashlink#403]
I am getting this error when running: `hl app.hl`:
`hl: symbol lookup error: hl: undefined symbol: hl_prim_not_loaded`

Not sure since when this is happing but v1.11 works.

Hashlink built with:
```
clang version 10.0.1 
Target: x86_64-pc-linux-gnu
```

**Comment by ncannasse** [comment]
Might be you're using an older libhl with a newer hl binary, or something
like that.

**Comment by tong** [comment]
Indeed # Thanks!
