### ISSUE TITLE
Can not display Chinese

### ISSUE THREAD

**Issue by hlizard** [HaxeFoundation/hashlink#406]
I found the neko, hashlink target of haxeui-openfl also not display Chinese(flash and html target is right), but some diff, Chinese is missing:
![image](https://user-images.githubusercontent.com/6994037/89480559-3e7c8380-d7c8-11ea-9918-d23be8a0e262.png)

```
import haxe.ui.Toolkit;
import haxe.ui.components.Button;
import haxe.ui.containers.VBox;
import haxe.ui.core.Screen;

class Main {
	static function main() {
		trace("你好, 中国!");
		trace("你好, 中国!".length);

		Toolkit.init();

		var main = new VBox();

		var button1 = new Button();
		button1.text = "按钮 1";
		main.addComponent(button1);

		var button2 = new Button();
		button2.text = "按钮 2";
		main.addComponent(button2);

		var input = new TextField();
		main.addComponent(input);

		Screen.instance.addComponent(main);
	}
}

```
also https://github.com/haxeui/haxeui-hxwidgets/issues/25#issuecomment-669632768

**Comment by ncannasse** [comment]
I thin it comes from HaxeUi font. It's not related to Hashlink or Heaps.io
since both can handle correctly Chinese characters.

**Comment by hlizard** [comment]
You are right, but I found another problem, not all chinese char display:
![image](https://user-images.githubusercontent.com/6994037/89623551-61419180-d8c7-11ea-9cc8-5ec35d99a223.png)

neko ok:
![image](https://user-images.githubusercontent.com/6994037/89623228-d365a680-d8c6-11ea-83cd-9fd41b71ead7.png)

**Comment by hlizard** [comment]
Maybe like https://github.com/openfl/openfl/issues/2138, i will test it later(wait for the compatibility issue of haxe 4.2 to be resolved).

**Comment by ncannasse** [comment]
This is most likely due to the used font missing the glyphs

**Comment by hlizard** [comment]
Now the test is successful, it should be the problem of OpenFL.

openfl: [9.1.0] (git b3d910401b47b2c5ae41f0e344212801f3dd2087)
lime: [7.9.0]
haxe: 4.2.0
hl-1.10.0-win
