### ISSUE TITLE
No available information on how to install.

### ISSUE THREAD

**Issue by tlegoc** [HaxeFoundation/hashlink#407]
While it's explained how to build hashlink, it is not on how to install it.
Do you have to add it to your path ? etc.

Please make it easy for newcomers to do this.

**Comment by ConstNW** [comment]
@edoriontlg, did you look on the wiki pages?

https://github.com/HaxeFoundation/hashlink/wiki/Building-and-Installing
https://github.com/HaxeFoundation/hashlink/wiki/install-on-centos,-fedora

**Comment by edoriontlg** [comment]
> @edoriontlg, did you look on the wiki pages?
> 
> https://github.com/HaxeFoundation/hashlink/wiki/Building-and-Installing
> https://github.com/HaxeFoundation/hashlink/wiki/install-on-centos,-fedora

Yep I did. I added those lines on "How to install" myself (check the logs).
