### ISSUE TITLE
[libuv]close socket error.

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#408]
what I got is this

        hl: src/unix/stream.c:1299: uv__stream_io: Assertion `!(stream->flags & UV_CLOSING)' failed.

when I call  

        socket.close()

**Comment by ncannasse** [comment]
Maybe it's a double close ?

**Comment by sonygod** [comment]
@ncannasse Maybe ,so I add some code like here.

    if (handle != null && !wasClose) {
			wasClose = true;//add this 
			close_handle(handle, callb);
		}
