### ISSUE TITLE
VSCode Debugger issues on Linux

### ISSUE THREAD

**Issue by haddock7** [HaxeFoundation/hashlink#416]
Here are the issues I had on Ubuntu 20.04 (I have also tested on the latest version of Mint, so I guess it's the same on other distributions):
- Step in isn't working
- Continue blocks the application
- Add a breakpoint when the application is running does nothing (i.e the application doesn't stop on it).

I was able to find a hacky workaround for the first issue by modifiing the VSCode hashlink debugger extension: in hld/Debugger.hx:227 I changed this line from:
`if( cmd.r == Breakpoint && nextStep >= 0 ) {`
to
`if( cmd.r == Breakpoint && (nextStep >= 0 || onStep)) {`

But I'm not sure that the problem is in this extension, but in the low-level Linux debug code of HashLink instead.

**Comment by rcstuber** [comment]
See the issue linkes below in the Hashlink VSCode Debugger project. They are probably identical. I outlined the fixes required to solve these issues there.

https://github.com/vshaxe/hashlink-debugger/issues/77

**Comment by ncannasse** [comment]
Keeping debugger issues in debugger repo ;)
