### ISSUE TITLE
AArch64 support

### ISSUE THREAD

**Issue by phykos** [HaxeFoundation/hashlink#420]
Hello there, I tried to compile HashlinkVM on a RPi4, I had to tweak a bit the Makefile due to unrecognized command line options.
Running any snippet raises an "illegal hardware instruction (core dumped)".
I am pretty sure this is because of JIT compilation of an architecture (not AArch64) and trying to run the executable memory.

I'd like to help, I have an overall good experience with LLVM and JIT compilers in general

**Comment by shakesoda** [comment]
there is indeed no aarch64 support in the jit *at all* right now. check out jit.c as a starting point.

**Comment by ncannasse** [comment]
ATM the JIT is entirely written for x86/x86-64
I think it could be modified to emit ARM code but this would require quite extensive changes as I haven't designed it that much to be arch-agnostic.
Another option to use HashLink on ARM is to use haxe HL/C code generation and compile it with gcc + link the hashlink runtime.

**Comment by phykos** [comment]
I'll fork the repo and try to port HashLink on AArch64, perhaps it may be easier than I think

**Comment by phykos** [comment]
I have seen `src/jit.c`, and I think HL should be a LLVM-based JIT, there is too much stuff going on, and porting those to AArch64 is almost impossible

**Comment by onehundredfeet** [comment]
Would it be easier to emit LLVM byte code similarly to how the HL/C works? And then use the LLVM toolchain to build the app and link with libHL?

That's pretty similar to just running Clang on the HL/C path, but may be a much faster compile.  Just a thought.

I plan on using Hashlink for all my games and in the future, would like it to run natively on the new Mac machines.

**Comment by shakesoda** [comment]
I, for one, would *really* prefer not pulling in something like LLVM over this - an AArch64 implementation of the JIT would be nice but I really appreciate the current status of HL being relatively self contained without any monstrous deps. HL/C also works just fine on ARM Macs, today, without doing much at all (I think I had to make a few changes to disable mdbg, it's got a bunch of x64-isms, otherwise all I did was write my own build scripts).

**Comment by onehundredfeet** [comment]
That works 100% for my workflow.  I was just proposing a possible path for the OP. For my purposes, I'm fine using the HL/C path.

**Comment by bmdhacks** [comment]
Here's a seemingly working first-pass at an aarch64 jit.  It's woefully inefficient but I worked on accuracy first.  Next step is to optimize register usage/spilling to not have such heinous memory bandwith:

 https://github.com/bmdhacks/hashlink/tree/bmd-aarch64
