### ISSUE TITLE
hl not working on the outside directory but works where i built on the directory (Linux Mint 19.2)

### ISSUE THREAD

**Issue by harshetmaruff** [HaxeFoundation/hashlink#422]
hashlink command hl working inside directory where i built but not working on the other directories

**Comment by ncannasse** [comment]
most likely some issue wrt libhl.so or other hdll not being able to locate them.
Do you run make install to install is system-wise ?

**Comment by harshetmaruff** [comment]
> most likely some issue wrt libhl.so or other hdll not being able to locate them.
> Do you run make install to install is system-wise ?

I did first command:
    make
then i did 
    make install

**Comment by harshetmaruff** [comment]
i had some permission errors so i did sudo make install
