### ISSUE TITLE
Windows CI builds failing because ffmpeg host went down

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/hashlink#427]
Here are the binaries that we use, downloaded from the Wayback Machine. Where should we put them? Or maybe should we upgrade to more recent build? (see https://ffmpeg.org/download.html#build-windows)

[ffmpeg-3.4.2-win32-dev.zip](https://github.com/HaxeFoundation/hashlink/files/5648055/ffmpeg-3.4.2-win32-dev.zip)
[ffmpeg-3.4.2-win64-dev.zip](https://github.com/HaxeFoundation/hashlink/files/5648056/ffmpeg-3.4.2-win64-dev.zip)

**Comment by ncannasse** [comment]
hlvideo is a very experimental library that is not part of the windows distribution of hashlink, I don't think it's necessary to compile it using CI.
