### ISSUE TITLE
Why hashlink isn't up do date on haxelib?

### ISSUE THREAD

**Issue by lufemas** [HaxeFoundation/hashlink#429]
The only way to install is using directly the binaries or building for Windows OS?
It's outdated for 4 years on haxelib: https://lib.haxe.org/p/hashlink/
Could not find it on chocolatey package manager either.

**Comment by tobil4sk** [comment]
The Haxelib is not for installing the actual Hashlink executable, it is a Haxe library needed for generating c code with the Hashlink target. As far as I know Binary and building natively are currently the only ways of installing on Windows.

However, the library on Haxelib is out of date compared to this repository (in the [other/haxelib/](https://github.com/HaxeFoundation/hashlink/tree/master/other/haxelib) directory). It is missing the code required for generating project files for Visual Studio.

It would be helpful if the package could be updated on Haxelib? @ncannasse

**Comment by tobil4sk** [comment]
For reference, I created a [PR](https://github.com/HaxeFoundation/HaxeManual/pull/494) for the Haxe Manual that explains how to install the most up to date version of the haxelib, via the command:
```
haxelib git hashlink https://github.com/HaxeFoundation/hashlink.git master other/haxelib/
```
