### ISSUE TITLE
Sys.programPath returns name of hashlink image instead of hashlink executable

### ISSUE THREAD

**Issue by jefvel** [HaxeFoundation/hashlink#434]
I am trying to launch a new instance of Hashlink from within an existing one.
`Sys.programPath()` returns the name of the image, instead of hashlink itself.
However, `Sys.executablePath()` returns the hashlink path. But it is deprecated.

Is this by design? Is it possible get the hashlink executable path in any other non deprecated way?

**Comment by ncannasse** [comment]
It's working according to Sys documentation. You can use Sys.executablePath and disable deprecation warnings instead.
