### ISSUE TITLE
scope of hashlink

### ISSUE THREAD

**Issue by coderofsalvation** [HaxeFoundation/hashlink#438]
I'm trying to wrap my head around what hashlink **is** and what it **isn't**

Is it: 
* basically haxe as a runtime with some crossplatform libs bundled?
* if so, will there be binaries in the release section for every OS?

And what are the benefits of hashlink vs just running/distributing haxe-apps using `run.bat`  (in other words: `haxe -main MyApp`) ?

**Comment by Aurel300** [comment]
HashLink should have binary releases for multiple platforms (see #419 and #73), in fact there used to be OS X binaries in the releases (see 1.3). I think it's just an issue of the CI not being set up for it.

Distributing apps and running with `haxe --main MyApp` would have multiple issues:

- It requires that the compiler is packed with the application, but the compiler is licensed under the GPL license, which is not as permissible as MIT (used for HashLink). This might matter for commercial applications.
- It requires that the source code is packed with the application. Unusable for closed-source games etc…
- The `eval` interpreter of the `haxe` compiler is quite a lot slower than HashLink in many cases. See the [benchmarks](https://benchs.haxe.org/).

**Comment by ncannasse** [comment]
Same ;)
