### ISSUE TITLE
[hl] .map(Std.parseInt) throws "Can't cast hl.types.ArrayObj to hl.types.ArrayBytes_Int"

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/hashlink#441]
This throws an exception with HL, but runs ok on other targets (I've tested neko, cpp, js, interp).

```haxe
  var intArray:Array<Int>;
  var intStr = "12 13";
  intArray = intStr.split(" ").map(Std.parseInt);
```

`Uncaught exception: Can't cast hl.types.ArrayObj to hl.types.ArrayBytes_Int`

Not sure this could be classified as a bug or not. :)

haxe 4.2.0-rc.1
hl 1.11.0 win

**Comment by ncannasse** [comment]
This is more a haxe bug as it allows casting Array<Null<Int>> to Array<Int>
while it should not.

**Comment by Gama11** [comment]
https://github.com/HaxeFoundation/haxe/issues/6785
