### ISSUE TITLE
Access Violation: mutex.acquire()

### ISSUE THREAD

**Issue by vangroan** [HaxeFoundation/hashlink#446]
I'm encountering an access violation when running a minimal Heaps program.

**OS:** Windows 10
**HashLink version:** 1.10.0 and 1.11.0
**Haxe:** 4.2.0

```haxe
class Main extends hxd.App {
    override function init() {}

    static function main() {
        new Main();
    }
}
```

This happens when `MainLoop.injectIntoEventLoop()` in the haxe standard library attempts to acquire a mutex. Here: https://github.com/HaxeFoundation/haxe/blob/2f9f75123be233a666df2e23cf6defde764e0833/std/haxe/MainLoop.hx#L112

From the VSCode debugger it looks like the `mutex` field on the `MainLoop` class is null.

![image](https://user-images.githubusercontent.com/7265531/109347291-991c2080-787b-11eb-8bd0-7348004ce7ed.png)

The access violation comes from `libhl`

```
libhl!hl_mutex_acquire+0x6:
00007ff9`5232c746 80793000        cmp     byte ptr [rcx+30h],0 ds:00000000`00000030=??
```

**Comment by Gama11** [comment]
I think that may be fixed with Haxe 4.2.1?

**Comment by vangroan** [comment]
Related:
- https://github.com/HaxeFoundation/haxe/issues/10059
- https://github.com/HeapsIO/heaps/issues/922

Just tried Haxe 4.2.1 and the issue still present. Using Haxe 4.1.5 works.

**Comment by ncannasse** [comment]
We're working on it, heaps GIT has been fixed and I will release a new Heaps on haxelib as well. Requires Haxe 4.2.1

**Comment by vangroan** [comment]
That's great! Thank you.
