### ISSUE TITLE
Segfault running heaps app compiled with haxe >= 4.2

### ISSUE THREAD

**Issue by linuxfranz** [HaxeFoundation/hashlink#447]
When I compile the Heaps hello world example on Linux with haxe 4.1.5 (haxe -cp src -lib heaps -lib hlsdl -hl hello.hl -main Main
) and start it with hl hello.hl it runs without problems.
Compiling it with haxe 4.2.0 or 4.2.1 gives me a segfault on start:

franz@linux-7gdi:~/Projekte/haxe/heaps/helloHeaps> haxe -cp src -lib heaps -lib hlsdl -hl hello.hl -main Main
franz@linux-7gdi:~/Projekte/haxe/heaps/helloHeaps> hl hello.hl 
SIGNAL 11
haxe.$MainLoop.injectIntoEventLoop(/home/franz/Software/haxe_20210208160017_bfcbf80/std/haxe/MainLoop.hx:114)
haxe.$MainLoop.add(/home/franz/Software/haxe_20210208160017_bfcbf80/std/haxe/MainLoop.hx:108)
fun$5106(hxd/System.hl.hx:403)
Segmentation fault (Speicherabzug geschrieben)

**Comment by ncannasse** [comment]
Please upgrade to latest Heaps GIT or use Heaps 1.9 that was just released ;)

**Comment by linuxfranz** [comment]
I'm using heaps git...

**Comment by ncannasse** [comment]
Are you using Haxe 4.2.1 ?

**Comment by linuxfranz** [comment]
Yes. But I also tested with 4.2.0 with the same error.

**Comment by ncannasse** [comment]
Ping @Yanrishatum

**Comment by Yanrishatum** [comment]
Are you using the latest git heaps? The 4.2 fix was merged just a few hours ago: https://github.com/HeapsIO/heaps/commits/master
Additionally, are you certain that HL file is compiled with 4.2.1 (not 4.2)? Because as I understand the `__init__` order is hard-coded into HL file and unless you compile with 4.2.1 it would produce invalid bytecode. 
Stack trace is clearly indicating that MainLoop was not initialized before `__init__` methods were invoked, which was the issue on 4.2.0

**Comment by linuxfranz** [comment]
franz@linux-7gdi:~/Projekte/haxe/heaps> cd helloHeaps/
franz@linux-7gdi:~/Projekte/haxe/heaps/helloHeaps> haxe --version
4.2.1+bf9ff69
franz@linux-7gdi:~/Projekte/haxe/heaps/helloHeaps> haxelib update heaps
heaps was updated
franz@linux-7gdi:~/Projekte/haxe/heaps/helloHeaps> haxe -cp src -lib heaps -lib hlsdl -hl hello.hl -main Main
franz@linux-7gdi:~/Projekte/haxe/heaps/helloHeaps> hl hello.hl 
SIGNAL 11
haxe.$MainLoop.injectIntoEventLoop(/home/franz/Software/haxe_20210226105244_bf9ff69/std/haxe/MainLoop.hx:112)
haxe.$MainLoop.add(/home/franz/Software/haxe_20210226105244_bf9ff69/std/haxe/MainLoop.hx:106)
fun$5105(hxd/System.hl.hx:422)
Segmentation fault (Speicherabzug geschrieben)

**Comment by Yanrishatum** [comment]
Can you open `MainLoop.hx` and trace if mutex is null or not at line 112? This is exactly what happens with HL file compiled by 4.2.0, as it does not initialize the variables properly. Also, delete the .hl file just in case, as iirc Haxe started to skip compilation if nothing was changed (thought I think it only relates to compilation with cache). If nothing helps, I suspect it's Linux-exclusive issue with threading. (Also please post logs like that with triple backtick ( ` ``` ` ) before and after)

**Comment by linuxfranz** [comment]
Thanks for the hints. I'm away from my computer for a while now. Will try your suggestions and post the results when back.

**Comment by linuxfranz** [comment]
I've deleted hello.hl, compiled again with haxe 4.2.1
A trace(mutex) before line 112 in `mainloop.hx` shows it is null

**Comment by ncannasse** [comment]
Can you confirm https://github.com/HeapsIO/heaps/pull/933 fixes it ?

**Comment by linuxfranz** [comment]
Yes. Works now for me. Thank you!
