### ISSUE TITLE
Unsure how to embed Hashlink in existing project

### ISSUE THREAD

**Issue by 3snowp7im** [HaxeFoundation/hashlink#459]
Researching how to embed hashlink, I am confused to what extent its possible. I think the best source of information on embedding hashlink is the code linked in the github wiki article "Embedding HashLink" at https://github.com/HaxeFoundation/hashlink/blob/master/src/main.c

The file above relies on the `hlmodule.h` header. However, this is not meant as a blueprint for how to embed hashlink in your own project as `hlmodule.h` is not a public header. That is to say, it is not copied to a system location when installing the hashlink project.

Is embedding hashlink in your project possible given that `hlmodule.h` is an internal interface to the hashlink library? Is there a different way to embed hashlink that does not rely on the hlmodule interface?

**Comment by ncannasse** [comment]
Yes you need to copy some headers that are not installed in /include directory, because atm include is for building hdlls for extensions.
