### ISSUE TITLE
hl.NativeArray cannot directly be used in Arrays/Maps (Debug only)

### ISSUE THREAD

**Issue by nspitko** [HaxeFoundation/hashlink#461]
Minimal repro:
```haxe
    public var map: Map<String, hl.NativeArray<String>> = [];
    public function new()
    {
        map["test"] = new hl.NativeArray<String>(10);
        var test = map["test"];
    }
```
produces `JIT ERROR 12 (jit.c line 1856)` ***with -debug***.

Tested with Hashlink 1.11 / Haxe 4.2.3

A workaround is simply use Dynamic, but this is non-obvious, and the error leaves you with little information to try and debug this.

possibly related to #394

**Comment by dipyalov** [comment]
I guess this may be related to https://github.com/HaxeFoundation/haxe/issues/11468

**Comment by yuxiaomao** [comment]
Cannot reproduce with Hashlink git latest + Haxe git latest, on both HL and HLC target.
