### ISSUE TITLE
Large Enums fail at runtime

### ISSUE THREAD

**Issue by aartzrc** [HaxeFoundation/hashlink#463]
HashLink appears to store Enums indexed in a way that limits them to 127 entries. For example:
```haxe
class EnumTest {
    public static function main() {
        trace(Test.getConstructors());
    }
}

enum Test {
    A1;
    .... A2 thru A126 here
    A127;
    A128;
}
```
This works on other targets but HL fails at runtime with errors like `Invalid type index`, `Invalid string index`, and `Negative Index`. Once `A128;` is commented out everything runs fine. It isn't common to have such large Enum ranges, but we ran into this recently and it was a confusing bug to nail down.

**Comment by shakesoda** [comment]
is your HL outdated? this sounds like https://github.com/HaxeFoundation/hashlink/issues/409, fixed by https://github.com/HaxeFoundation/hashlink/commit/5bdaef4cd785d0b0f459c83c87dd00738228a849

**Comment by aartzrc** [comment]
You are correct. I am running the pre-built version available here: https://github.com/HaxeFoundation/hashlink/releases which is 1.11. I will pull source and rebuilt. Thanks for the quick response!
