### ISSUE TITLE
C API Access to types

### ISSUE THREAD

**Issue by onehundredfeet** [HaxeFoundation/hashlink#474]
Hi folks,

I'm looking for a way to retrieve the 'String' hl_type*.  Right now, I'm doing this in a SUPER sketchy way:

```
static  hl_type *strType = nullptr;
void cacheStringType( vstring *str) {
   strType = str->t;
}
```
but I'd like to do this a proper way, but I can't find any functions that return an hl_type * based on a string.

There must be something deep down inside that is doing this for the internal routines or I'm missing an API call.

Cheers,
Ryan.

**Comment by ncannasse** [comment]
There's no "clean" way of doing this as it's not the way it's intended : you should directly return bytes from your C API and have the String (or Array) objects allocated by your Haxe wrapper.
