### ISSUE TITLE
JIT ERROR 142 (jit.c line 814)

### ISSUE THREAD

**Issue by nspitko** [HaxeFoundation/hashlink#476]
This one's a head scratcher.

Checked against both the release 1.11 version and locally build git binaries as of the time of filing, both reproduce this error.

I cut down this repro case as much as I could, but it's still pretty meaty, despite being butchered nonsense. Sorry for that in advance. Also this specific example will crash when launched due to the amount I cut out, but the bug itself is that it won't even launch due to the JIT error. If this is a problem, I can add a bit more code back in.

Some fun notes:
- Removing a single float from `intersects` fixes everything
- The code compiles and runs fine in hlc. 
- Locally built 32 bit binaries ALSO seem to run the code just fine, only 64 bit produces the issue.
- Removing a single float from `intersects` fixes the bug. *adding one* also works.

```haxe
class CollisionManager
{
	var buckets: haxe.ds.Vector<List<CollisionObject>>;

	public function new() { }

	public function tick( delta: Float )
	{
		var bucket = buckets[0];
		for( object in bucket )
		{
			for( other in buckets[0])
			{
				/**
				 * The main trigger is in "intersects". Even in my original code, removing a single
				 * float from the argument list allows it to work fine. It seems the 5th arg is what
				 * pushes something over the edge. What's left in this function is what appears to be
				 * the minimal repro, but it's extremely fiddly, and seemingly unrelated changes will
				 * fix the error.
				 */
				if( other.colliders[0].intersects(other.colliders[0], 0, 0, 0, 0) )
				{
					object.handleCollision(other);
				}
			}
		}
	}
}

interface CollisionObject
{
	public var colliders(default, null): haxe.ds.Vector<Collider>;
	public function handleCollision( other: CollisionObject ) : Void;
}

interface Collider
{
	public function intersects( other: Collider, x: Float, y: Float, otherX: Float, otherY: Float ): Bool;
}

class Main
{
    public function new()
    {
		var f = new CollisionManager();
		f.tick(0);
    }

	static function main()
	{
		new Main();
	}
}
```

**Comment by ncannasse** [comment]
Try compiling with  `haxe -D hl-check` to verify the compiler bytecode

**Comment by nspitko** [comment]
`hl-check` doesn't report anything.

I've attached hlcode.txt and hlopt.txt as well if those are useful.

[dump.zip](https://github.com/HaxeFoundation/hashlink/files/7227665/dump.zip)
