### ISSUE TITLE
`Std.parseInt` parses numbers with leading whitespaces incorrectly

### ISSUE THREAD

**Issue by kiwwisk** [HaxeFoundation/hashlink#477]
## How to reproduce the error?

https://try.haxe.org/#B68880c8

If there's newline character at the beginning, `Std.parseInt` fails to parse the number correctly.

```hx
    trace(Std.parseInt("\n10"));
    trace(Std.parseInt("\n0x10"));
    trace(Std.parseInt("\r10"));
    trace(Std.parseInt("\r0x10"));
```

Prints:

```none
Test.hx:3: null
Test.hx:4: null
Test.hx:5: null
Test.hx:6: null
```

Should print:

```none
Test.hx:3: 10
Test.hx:4: 16
Test.hx:5: 10
Test.hx:6: 16
```

Note: The neko target also fails to parse the numbers correctly.

**Comment by Yanrishatum** [comment]
Related: https://github.com/HaxeFoundation/hashlink/issues/330
Fix only checks for ` `  character, but not the CR / LF characters which are also considered to be white-space, meaning that described behavior of leading white-space being stripped is not respected.

**Comment by ncannasse** [comment]
Having leading spaces in the parsed String in unspecified according to API documentation https://api.haxe.org/Std.html#parseInt

**Comment by Yanrishatum** [comment]
@ncannasse Quite the opposite thought? Behavior description is explicit about leading whitespace.

> Leading whitespaces are ignored.

Common "whitespace" characters are space and newline characters.
Another related issue that touches up on all languages: https://github.com/HaxeFoundation/haxe/issues/8970
Note that fix for other languages was doing `(c > 8 && c < 14) || c == 32)` check, while HL checks for `32`, i.e. space character only.

See implementation: 
https://github.com/HaxeFoundation/hashlink/blob/master/src/std/bytes.c#L193-L196

And while for `parseFloat` it is not explicitly stated that leading whitespace is trimmed, it is a fairly common expectation, and again, on HL side it does perform stripping of leading spaces, but not whitespaces: 
https://github.com/HaxeFoundation/hashlink/blob/master/src/std/bytes.c#L183

**Comment by Yanrishatum** [comment]
@ncannasse This solution has 2 flaws (one of which is critical):
1. It only applies if `HL_NATIVE_UCHAR_FUN` is not set, which is not the case for `HL_WIN && !HL_LLVM` see [hl.h, line 210](https://github.com/HaxeFoundation/hashlink/blob/master/src/hl.h#L210), meaning that it won't be fixed for windows build that is not using llvm. Windows is smart enough to strip whitespace for base10, but in case of hexadecimal - it does not properly parse integers (`\r0x10` would yield `0`). 
2. Range check is incomplete, and expected characters being 9, 10, 11, 12 and 13, i.e. `TAB, LF, VT, FF, CR`, hence other targets check for `c > 8 && c < 14`.
