### ISSUE TITLE
Fields in native returned object are garbage collected

### ISSUE THREAD

**Issue by ianxm** [HaxeFoundation/hashlink#480]
The [docs say](https://github.com/HaxeFoundation/hashlink/wiki/C-API-Documentation#accessing-objects-from-c) that it is possible to pass haxe objects to native code as c structs by adding a type field to the struct. Returning a c struct as a haxe object seems to work also, but after a while the fields of the return object are garbage collected even though the returned object is still in scope. Is this not allowed?

TestCaller.hx:

    class HL_TestResult {
        public var testInt :Int;
        public var testString :String;
    }
    
    @:hlNative("testnative")
    class TestCaller {
        public static function _test_call() :HL_TestResult { return null; }
    
        public static function main() {
            var testRet = _test_call();
            for( ii in 0...200 ){
                trace('$ii ${testRet.testInt} ${testRet.testString}');
            }
        }
    }

native/testnative.cpp:

    #define HL_NAME(n) testnative_##n
    
    #include <hl.h>
    
    typedef struct {
        hl_type *t;
        int testInt;
        vstring *testString;
    } vtestResult;
    
    #undef _TEST_RESULT
    #define _TEST_RESULT _OBJ(_I32 _STRING)
    
    HL_PRIM vtestResult* HL_NAME(_test_call)() {
        vtestResult *ret  = (vtestResult*) hl_gc_alloc_raw(sizeof(vtestResult));
    
        ret->testInt = 1;
    
        ret->testString = (vstring*) hl_alloc_bytes(sizeof(vstring));
        // FIXME not sure if &hlt_bytes is right, but there's no &hlt_string or &hlt_obj.
        ret->testString->t = &hlt_bytes;
        ret->testString->bytes = hl_to_utf16("one");
        ret->testString->length = hl_utf8_length((const vbyte*) "one", 0);
    
        return ret;
    }
    
    DEFINE_PRIM(_TEST_RESULT, _test_call, _NO_ARG);

build.hxml:

    -cmd g++ -fPIC -fno-use-cxa-atexit -o bin/testnative.o -I/usr/include/x86_64-linux-gnu -I/opt/hashlink-1.11/ -I/usr/local/include -c native/testnative.cpp 
    -cmd ld -o bin/testnative.hdll -shared -fPIC -fno-use-cxa-atexit -lhl -ldl -lpthread -lrt -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib bin/testnative.o
    
    --next
    
    -main TestCaller
    -cp src
    -hl bin/testcaller.hl
    -cmd LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./bin:/usr/local/lib hl bin/testcaller.hl

This is the output. The string "one" becomes "13" at iteration 151.

    TestCaller.hx:13: 0 1 one
    TestCaller.hx:13: 1 1 one
    TestCaller.hx:13: 2 1 one
    TestCaller.hx:13: 3 1 one
    TestCaller.hx:13: 4 1 one
    ...
    TestCaller.hx:13: 146 1 one
    TestCaller.hx:13: 147 1 one
    TestCaller.hx:13: 148 1 one
    TestCaller.hx:13: 149 1 one
    TestCaller.hx:13: 150 1 one
    TestCaller.hx:13: 151 1 13
    TestCaller.hx:13: 152 1 13
    TestCaller.hx:13: 153 1 13
    ...

**Comment by ncannasse** [comment]
The problem here is that you're using hl_alloc_bytes(sizeof(vstring)) which means your testString->bytes will not be scanned by GC.

**Comment by ianxm** [comment]
Yes, you're right. Thank you.
