### ISSUE TITLE
Invalid signature in sqlite.hdll

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/hashlink#485]
`src\module.c(478) : FATAL ERROR : Invalid signature for function sqlite@result_get : PXsqlite_result_i_B required but PXsqlite_result_i_NB found in hdll`

This error happens whenever I have haxe code that contains the `sys.db.ResultSet.getResult()` function.

**Comment by ncannasse** [comment]
You most likely have a difference between the hashlink version you are
using and the Haxe bindings for sqlite requiring a different version.

**Comment by tobil4sk** [comment]
I have both haxe and hashlink built from source. Using `-D hl-ver=1.12.0` doesn't fix it. Are current versions of Haxe and Hashlink not compatible?
