### ISSUE TITLE
Phantom fields appear in typedef argument in 64-bit Hashlink

### ISSUE THREAD

**Issue by Cleod9** [HaxeFoundation/hashlink#491]
Created a repo to demonstrate the issue: https://github.com/Cleod9/hashlink-typedef-bug

In short, when certain conditions are met, a relatively harmless method such as this can have a phantom field appear in the passed object:

```haxe
public function myFunc(obj:MyTypedef) {
	// obj may contain an addtional field that you didn't set!!!
}
```

I've only been able to narrow it down to the following conditions:

- The `typedef` needs to contain many fields
- The amount of fields affects whether the bug occurs or not
- The names of the fields affects whether the bug occurs or not
- The bug only occurs in the 64-bit version of hashlink

It was extremely difficult to break this down to a generalized example because of the volatile conditions. Unfortunately I was unable to identify where this might be caused in Hashlink's code base as it's unclear which part of the code would be responsible for this behavior, and it seems this issue has existed since 64-bit support was first introduced.

Any help on this issue would be greatly appreciated!

**Comment by ncannasse** [comment]
Thanks for the repro !
