### ISSUE TITLE
flixel code not running on hashlink - error with openal

### ISSUE THREAD

**Issue by linuxfranz** [HaxeFoundation/hashlink#494]
When I compile my flixel project to hl and run it I get the following error:

> Executing task: lime test hl --connect 6000 <

/home/franz/haxelib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
/home/franz/haxelib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
/home/franz/haxelib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
/home/franz/haxelib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
/home/franz/haxelib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead.
AL lib: (EE) GetLoadedHrtf: Invalid header in /usr/share/openal/hrtf/Default HRTF.mhr: "MinPHR03"
AL lib: (EE) GetLoadedHrtf: Failed to load /usr/share/openal/hrtf/Default HRTF.mhr
Der Terminalprozess "bash '-c', 'lime test hl --connect 6000'" wurde mit folgendem Exitcode beendet: 1.

Is this a problem on my side (OS LinuxcOpenSuse Tumbleweed) or haxeflixel or hashlink?

**Comment by linuxfranz** [comment]
Additional comment: The Hello Heaps example runs on my system without problem

**Comment by ncannasse** [comment]
Seems more like a Lime error than a HashLink one. Please report to Lime repository.
