### ISSUE TITLE
HL/JIT on Apple Silicon / M1 via Rosetta?

### ISSUE THREAD

**Issue by jeremyfa** [HaxeFoundation/hashlink#497]
According to current Rosetta documentation (https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment) : _Rosetta can translate most Intel-based apps, including apps that contain just-in-time (JIT) compilers_

I know it is not planned to make HL/JIT work natively with ARM processors, but I was wondering if anybody tried to make HL/JIT work on the new macs using Rosetta? From what I can read, it should theoretically work.

Unfortunately I don't have an ARM mac myself to test this, but I am opening this issue hoping that somebody having one could try running HL/JIT via Rosetta on it and see if it works or not?

**Comment by shakesoda** [comment]
just double checked to be sure, and yes, x64 hl/jit works just fine in rosetta.

**Comment by jeremyfa** [comment]
That’s good news! I can close this issue then as we now have an answer. Thanks for checking that :)
