### ISSUE TITLE
Native Extensions path

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/hashlink#504]
I try to load a native extension into hashlink.
It doesn't work.
I put the ndll file into the hashlink folder, into the "current path" folder and in the folder where the Main.hl lies.
I get this error without any information why it fails:
```
D:\Avalu>D:\hl\hl.exe build\heaps\hl\Main.hl
d:\a\hashlink\hashlink\src\module.c(370) : FATAL ERROR : Failed to load library audio_input_device_loudness.hdll
```

**Comment by ncannasse** [comment]
More likely this hdll requires other DLLs which cannot be found in the
current directory

**Comment by lublak** [comment]
@ncannasse That was exactly the problem. Thank you, I've been looking for a place where the error could be.

Thank you very much for that!
