### ISSUE TITLE
MUnit not working (Reflect.callMethod)

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/hashlink#52]
When trying to test the [haxe-doctest](https://github.com/vegardit/haxe-doctest) against the hashlink target.

I get the following exception:
```
Uncaught exception: Can't cast #hx.doctest.tests.MUnitDocTests to #massive.munit.TestClassHelper
Called from $Reflect.callMethod(C:\apps\dev\haxe\haxe-3.4.0\std/hl/_std/Reflect.hx:85)
Called from massive.munit.TestRunner.execute(massive/munit/TestRunner.hx:243)
Called from massive.munit.TestRunner.run(massive/munit/TestRunner.hx:229)
Called from hx.doctest.tests.$MUnitTest.main(hx/doctest/tests/MUnitTest.hx:33)
Called from hx.doctest.$TestRunner.main(hx/doctest/TestRunner.hx:53)
Called from fun$629(?:1)
```

This only happens with HL. All other targets work. Is there maybe something wrong within the HL implementation of `Reflect.callMethod`?

I test the HL target using this batch file: https://github.com/vegardit/haxe-doctest/blob/master/test-hl.cmd

I am using HL 1.1 and the latest Haxe build.

**Comment by ncannasse** [comment]
Does MUnitDocTests extends/implements TestClassHelper ?

**Comment by sebthom** [comment]
No it does not and it should not.

```haxe
class MUnitTest extends TestSuite {
    public static function main() {
        var client = new RichPrintClient();
        var runner = new TestRunner(client);
        runner.run([MUnitTest]);
    }
    
    public function new() {
        super();
        add(MUnitDocTests);
    }
}

@:build(hx.doctest.DocTestGenerator.generateDocTests("test"))
class MUnitDocTests {
    public function new() {    }
}
```

The build macro adds test methods to the class.

I tried it with Haxe 3.4.2, HL 1.1.0 and munit 2.1.2.

```
Uncaught exception: Can't cast #hx.doctest.tests.MUnitDocTests to #massive.munit.TestClassHelper
Called from $Reflect.callMethod(C:\apps\dev\haxe\haxe-3.4.2\std/hl/_std/Reflect.hx:85)
Called from massive.munit.TestRunner.execute(massive/munit/TestRunner.hx:243)
Called from massive.munit.TestRunner.run(massive/munit/TestRunner.hx:229)
Called from hx.doctest.tests.$MUnitTest.main(hx/doctest/tests/MUnitTest.hx:33)
Called from hx.doctest.$TestRunner.main(hx/doctest/TestRunner.hx:53)
Called from fun$630(?:1)
```

Neko has no problem executing this.

The Reflect.callMethod is invoked like this in munit:

```haxe
for (testClass in suite)
{
    if (activeHelper == null || activeHelper.type != testClass)
    {
        activeHelper = new TestClassHelper(testClass, isDebug);
        Reflect.callMethod(activeHelper.test, activeHelper.beforeClass, emptyParams); // Line 243 exception occurs here
    }
    executeTestCases();
```

I don't understand why this results in the Reflect.callMethod trying to cast my test class to TestClassHelper.

**Comment by ncannasse** [comment]
Can you check if it's the case with Haxe Nightly + HashLink 1.4 ?

If it's still does not work:

This shows an invalid MUnit behavior, which is passing the first argument of the Reflect.callMethod with an object value that does not match the function closure. 

I think in that case, activeHelper.beforeClass being a closure, it should either pass the class instance on which it comes from (, or null (but that would break on non-closure platforms such as JS)

**Comment by sebthom** [comment]
Unfortunately same issue with latest Haxe 4 nightly and HashLink 1.4.

**Comment by ncannasse** [comment]
Copying my comment on munit issue.

**Comment by sebthom** [comment]
Thanks a lot for looking into it. I am closing this issue and track it in the munit repo.
