### ISSUE TITLE
Linux nightly build is unusable

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/hashlink#525]
Right now, the nightly build for linux cannot be used "out of the box" because it is not relocatable. With neko you were able to simply download a nightly build, extract it, add the extracted path to PATH, and use the neko binary from anywhere without any issues. When trying to do this with hashlink, `libhl.so` is not found, because the rpath used when building it does not contain `$ORIGIN`.

Ways to fix this:
- Adding `$ORIGIN` to rpath, but Nicolas has been reluctant to add anything to rpath, see: https://github.com/HaxeFoundation/hashlink/pull/437#issuecomment-757533270 
- Distribute the nightly build with an `install.sh` script. However, unless this script installs the binaries directly to `/usr/`, then the user will experience #386. This cannot be fixed either unless we modify the rpath setting.

Neko also had a `RELOCATABLE` cmake option, to toggle whether `$ORIGIN` is added to rpath.

Unless rpath is modified, then there is no way for Linux users to be able to use hashlink without installing to `/usr/`. This is especially confusing for new linux users or people just trying to find a way to test if their game works on linux with the latest hashlink.

This is a pretty urgent issue. I am happy to create a new PR for a fix for this, or modify #483 to fit the solution decided upon, but a decision has to be made on how to approach this.

**Comment by Magnesus** [comment]
Not sure if related but I also get "./hl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by ./hl)
./hl: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./libhl.so)" errors when trying to run that hl on Ubuntu.

**Comment by Apprentice-Alchemist** [comment]
Are you using Ubuntu 18.04?
If yes, then it's just the usual glibc issues.
CI uses 20.04, and thus a more recent version of glibc.
Solutions: build from source, or upgrade to an up to date OS.

**Comment by Magnesus** [comment]
Yes, I use old Ubuntu. I have to admit though I was expecting HL to work on every Linux version out there, otherwise releasing with it is a bit risky since users may have unsupported version of libraries.

**Comment by Apprentice-Alchemist** [comment]
> work on every Linux version

That is not practically feasible since it would require building against the oldest versions of glibc etc.

But, building on Ubuntu 18.04 should do the trick for people that for some reason use LTS releases of Debian or Ubuntu.

@sebthom It seems CI originally used 18.04, but then you updated that to 20.04.
I assume this is because of #506? If yes, CI should be able to use 18.04 again, since that has been fixed.

**Comment by sebthom** [comment]
@tobil4sk can you please try the latest build

**Comment by tobil4sk** [comment]
@sebthom I think #529 might address @Magnesus's issue with the GLIBC error (which is slightly unrelated), however, the original issue here is about the rpath setting.
