### ISSUE TITLE
Finalize / IDisposable pattern

### ISSUE THREAD

**Issue by onehundredfeet** [HaxeFoundation/hashlink#540]
Is there a common haxe HL convention for disposing / finalizing objects manually rather than waiting for the garbage collector?

This is especially relevant in temporary objets inside a function.

- Allocate a temp object
- Use it
- Ideally, dispose of it.

Or should I just implement my own IDisposable style paradigm?  C# has some reasonable stuff in this area.

**Comment by ncannasse** [comment]
Usually we add a dispose() method to such objects, and you don't need an
interface in Haxe you can simply type them as { function dispose():Void }

Le jeu. 21 avr. 2022 à 23:09, Ryan Cleven ***@***.***> a
écrit :

**Comment by onehundredfeet** [comment]
Thanks!

**Comment by onehundredfeet** [comment]
Could potentially be nice to add the C# using paradigm.
https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/using-objects

**Comment by ncannasse** [comment]
Im quite sure this can easily be done through macros 😉

Le ven. 22 avr. 2022 à 06:30, Ryan Cleven ***@***.***> a
écrit :

**Comment by onehundredfeet** [comment]
fair enough.
