### ISSUE TITLE
@:hlNative method arguments treated as _REF(T) if they have default value

### ISSUE THREAD

**Issue by Yanrishatum** [HaxeFoundation/hashlink#543]
Currently, if native method can have optional arguments - they cannot be described on Haxe side explicitly.
For the following example:
```c
// C
HL_PRIM void HL_NAME(some_method)(value: Int, flag: Bool) {}
DEFINE_PRIM(_VOID, some_method, _I32 _BOOL); // Signature: Pib_v
```
```haxe
// Haxe
static function someMethod(value: Int, flag: Bool) {} // OK: Looks up for Pib_v
static function someMethod(value:Int = 0, flag: Bool = false) {} // ERROR: Looks up for PRiRb_v
```
And even more: Said default values are ignored completely, and not only treated as `_REF(_I32) _REF(_BOOL)` signature, but also passes `nullptr` to the function instead of default value (I.e. call `someMethod()` without arguments).
Default values should either be explicitly forbidden (i.e. compiler error) or properly handled (i.e. not treated as `_REF(T)` and sent proper default value on call).

**Comment by ncannasse** [comment]
Optional arguments are not replaced at call site in Haxe (because the default values could be changed in subclasses) so NULL values are added as arguments and they are replaced in the called method so it makes it very hard to implement what you want here.
