### ISSUE TITLE
Date.fromString TODO

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/hashlink#55]
I was doodling with HL again and spotted a TODO when using `Date.fromString`

```
src\std\date.c(73) : FATAL ERROR : TODO
```

https://github.com/HaxeFoundation/hashlink/blob/master/src/std/date.c#L73

**Comment by anissen** [comment]
Unrelated but there's also a `hl_fatal("TODO")` [here in fun.c](https://github.com/HaxeFoundation/hashlink/blob/7ba3ed29719ee0c2fa4e29837c3d11a9fb2374d1/src/std/fun.c#L290).
