### ISSUE TITLE
Optimize OSafeCast

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hashlink#551]
When we have OSafeCast from Null<T> to T we could inline the null check in JIT instead of calling hl_dyn_castX (example : Map<Int,Int> get)

**Comment by ncannasse** [comment]
TODO : also perform this optimisation in HL/C

**Comment by ncannasse** [comment]
HL/C still not finished

**Comment by yuxiaomao** [comment]
Already done in 2017 - this commit : https://github.com/HaxeFoundation/haxe/commit/f98a9458041db1377fcabc541911ddc9a4d8fc8b

Corresponding code:
https://github.com/HaxeFoundation/haxe/blob/a85fd3d53081496c3b0493983d278ca96ff63393/src/generators/hl2c.ml#L1016-L1022
