### ISSUE TITLE
Possible bug in hl_wrapper_call?

### ISSUE THREAD

**Issue by rushmobius** [HaxeFoundation/hashlink#552]
Attempting to call an object instance method from native code using hl_dyn_call_obj but kept crashing on hl_dyn_casti:279 inside of hl_wrapper_call in fun.c. This is on latest hashlink code and 1.12 release as well.

Giving a basic type
```
public class Foo
{
    public function do(a:Int):Bool
    {
        return true;
    }
}
```
And native code similar to
```
vdynamic* foo; // passed in just declared here for the example
int field = hl_hash_utf8("do");
hl_field_lookup* fieldLookup = hl_resolve_field(foo->t->obj, field); // function is declared elsewhere but verified return is correct

int32_t arg1 = 10;
void* args[1];

args[0] = &arg1;

hl_dyn_call_obj(foo, fieldLookup->t, field, (void**)&args, &result);

```
When it tries to cast the args[0] to the method type, it thinks the args[0] value is an HOBJ type. The w->hasValue is true so it pass the `this` pointer as the first arg. The isssue seems to be in the for loop on fun.c line 271
It seems if I change the current code to account for the p++ for the this arg, it would move to the correct 2nd arg on the wrapper
```
hl_type *t = tfun->args[p+i];
```

Or I am just doing something wrong =)

Thanks

**Comment by ncannasse** [comment]
You need to call the method with the object as first argument.

**Comment by rushmobius** [comment]
I tried that as well, but then it attempts to cast the object to an int32 on line 279 since the wrapper function only has 1 arg, the int32, while the tfun has 2 args(this, int32). It sets the vargs[0] with the object, then tries to cast the vargs[1]. I'll try some other variations.
```
int32_t arg2 = 10;
void* args[2];

args[0] = foo;
args[1] = &arg2;
```

**Comment by rushmobius** [comment]
As an additional follow up. If I am calling a static function on a type it works fine as is, my change would break that path. But I have been unable to get it work on an function of an object instance.

**Comment by ncannasse** [comment]
Looking at how hl_dyn_call_obj is used, it's mostly in order to call virtual fields in JIT.
So you're right it's not necessary to pass the the obj as parameter, but you need to pass a method type that does not contain the object value, so it's the "closure type" which you can get using hl_get_closure_type (currently not public API).
