### ISSUE TITLE
vbyte* to char*?

### ISSUE THREAD

**Issue by smallcoderofme** [HaxeFoundation/hashlink#556]
I'm doing some third-party library extensions for hl, I'm not very good at C, is there any way to convert vbyte* to char* or c++ std::string?

**Comment by shakesoda** [comment]
you probably want vstring* (and corresponding _STRING in DEFINE_PRIM), which you can convert to a utf8-encoded char* with hl_to_utf8(vstring*)

**Comment by smallcoderofme** [comment]
> you probably want vstring* (and corresponding _STRING in DEFINE_PRIM), which you can convert to a utf8-encoded char* with hl_to_utf8(vstring*)
> 
> edit: if you really actually have some string byte data then you can cast it, or if you're returning a string from c to hx you can return a vbyte and get a string using `@:privateAccess String.fromUCS2(str)` or `@:privateAccess String.fromUTF8(str)` in the externs (depending on if you're sending utf16 around or utf8)

Thanks for your reply, it's working！
