### ISSUE TITLE
HLC  '(' Error

### ISSUE THREAD

**Issue by rayloi777** [HaxeFoundation/hashlink#576]
Haxe 4.2.5
hashlink Git
heaps Git
hlsdl  Git
---------
❯ arch -x86_64 gcc -O3 -o myapp -std=c11 -I out out/main.c -lhl -Lfmt.hdll -Lui.hdll -Lopenal.hdll -Lsdl.hdll
In file included from out/main.c:10:
In file included from out/hl/functions.c:38:
out/hl/natives.h:32:15: error: expected identifier or '('
HL_API vbyte* ?sdl_get_clipboard_text(void);
              ^
out/hl/natives.h:33:18: error: expected identifier or '('
HL_API vdynamic* ?sdl_get_current_display_mode(int,bool);
                 ^
out/hl/natives.h:34:16: error: expected identifier or '('
HL_API varray* ?sdl_get_display_modes(int);
               ^
out/hl/natives.h:35:16: error: expected identifier or '('
HL_API varray* ?sdl_get_displays(void);
               ^
out/hl/natives.h:36:12: error: expected identifier or '('
HL_API int ?sdl_get_framerate(sdl_window*);
           ^
out/hl/natives.h:37:12: error: expected identifier or '('
HL_API int ?sdl_get_screen_height(void);
           ^
out/hl/natives.h:38:12: error: expected identifier or '('
HL_API int ?sdl_get_screen_height_of_window(sdl_window*);
           ^
out/hl/natives.h:39:12: error: expected identifier or '('
HL_API int ?sdl_get_screen_width(void);
           ^
out/hl/natives.h:40:12: error: expected identifier or '('
HL_API int ?sdl_get_screen_width_of_window(sdl_window*);
           ^
out/hl/natives.h:41:13: error: expected identifier or '('
HL_API void ?sdl_gl_compressed_tex_sub_image2d(int,int,int,int,int,int,int,int,vbyte*);
            ^
out/hl/natives.h:42:13: error: expected identifier or '('
HL_API void ?sdl_gl_compressed_tex_sub_image3d(int,int,int,int,int,int,int,int,int,int,vbyte*);
            ^
out/hl/natives.h:43:13: error: expected identifier or '('
HL_API void ?sdl_gl_tex_sub_image2d(int,int,int,int,int,int,int,int,vbyte*);
            ^
out/hl/natives.h:44:13: error: expected identifier or '('
HL_API void ?sdl_gl_tex_sub_image3d(int,int,int,int,int,int,int,int,int,int,vbyte*);
            ^
out/hl/natives.h:45:13: error: expected identifier or '('
HL_API bool ?sdl_set_clipboard_text(vbyte*);
            ^
out/hl/natives.h:46:12: error: expected identifier or '('
HL_API int ?sdl_win_display_handle(sdl_window*);
           ^
out/hl/natives.h:47:13: error: expected identifier or '('
HL_API bool ?sdl_win_set_display_mode(sdl_window*,int,int,int);
            ^
In file included from out/main.c:10:
out/hl/functions.c:8832:91678: error: expected expression
out/hl/functions.c:8832:91743: error: expected expression
out/hl/functions.c:8832:91679: error: use of undeclared identifier 'sdl_gl_compressed_tex_sub_image3d'; did you mean 'sdl_gl_compressed_tex_image3d'?
out/hl/natives.h:236:13: note: 'sdl_gl_compressed_tex_image3d' declared here
HL_API void sdl_gl_compressed_tex_image3d(int,int,int,int,int,int,int,int,vbyte*);
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by ncannasse** [comment]
This has been fixed on Haxe GIT already.
