### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/hashlink#584]
https://try.haxe.org/#7828cd8f
the expected output
```
Test.hx:13: Haxe
Test.hx:14: true
```
```haxe
typedef MyData = {
  var name:String;
  var valid:Bool;
}

class Test {
  static function main() {
    var s = '{
      "name": "Haxe",
      "valid": "true"
    }';
    var o:MyData = haxe.Json.parse(s);
    trace(o.name);
    trace(o.valid);
  }
}
```
in try haxe the eval, neko and js all give same output.

**Comment by ncannasse** [comment]
Hashlink, like some other platforms supported by Haxe, is a strictly typed platform, so here you're trying to assign the String `"true"` to a boolean value but it's not supported. Maybe you meant `"valid":true`

**Comment by nanjizal** [comment]
JSON parsing seems does not coerce the type, my misunderstanding. Probably a json2object would be more suitable. It is not ideal HL crashes and no way for compiler to complain. Ideal if HL was more like other targets but closing.

**Comment by nanjizal** [comment]
( context - was considering xml to typedef conversion but the JSON current approach is unsafe, and does not allow runtime string check coercion so emulating that string parse approach is not suitable as would require too many abstracts, currently bad formed inline string xml fails at runtime, no way to get typing without lots of macros  )
