### ISSUE TITLE
Library issue - Dead Cells Steam

### ISSUE THREAD

**Issue by ErdemTuna24** [HaxeFoundation/hashlink#592]
Last login: Fri Mar 10 11:48:59 on ttys000
/Users/erdemtunabalta/Library/Application\ Support/Steam/steamapps/common/Dead\ Cells/deadcells ; exit;
erdemtunabalta@Erdems-MacBook-Air ~ % /Users/erdemtunabalta/Library/Application\ Support/Steam/steamapps/common/Dead\ Cells/deadcells ; exit;
dyld: Library not loaded: libhl.dylib
  Referenced from: /Users/erdemtunabalta/Library/Application Support/Steam/steamapps/common/Dead Cells/deadcells
  Reason: image not found
zsh: abort      
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

I have problem opening dead cells on macOS Big Sur version 11.6.8. It gives this error when I tried to open it. Please help me solve it.

**Comment by tobil4sk** [comment]
Some people have solved similar issues on Linux by editing the launch options for steam games, e.g. you could try setting it to: `DYLD_LIBRARY_PATH=/path/to/game/install/location %command%`, where the install location should contain the `libhl.dylib`.

If you still have issues you should probably contact support for the game.

**Comment by Aurel300** [comment]
`DYLD_LIBRARY_PATH` is macOS specific, on Linux the variable is `LD_LIBRARY_PATH`.
