### ISSUE TITLE
Compiling fails on an M1 Mac

### ISSUE THREAD

**Issue by avrame** [HaxeFoundation/hashlink#593]
I followed the instructions in [this thread](https://github.com/HaxeFoundation/hashlink/issues/457) but I get the following error when running `make`:

```
cc -Wall -O3 -I src -msse2 -mfpmath=sse -std=c11 -D LIBHL_EXPORTS -m64 -I include -I /usr/local/include -I /usr/local/homebrew/include -I /usr/local/homebrew/opt/libjpeg-turbo/include -I /usr/local/homebrew/opt/jpeg-turbo/include -I /usr/local/homebrew/opt/sdl2/include -I /usr/local/homebrew/opt/libvorbis/include -I /usr/local/homebrew/opt/openal-soft/include -Dopenal_soft  -DGL_SILENCE_DEPRECATION -shared -o fmt.hdll libs/fmt/fmt.o libs/fmt/sha1.o include/mikktspace/mikktspace.o libs/fmt/mikkt.o libs/fmt/dxt.o  -L/usr/local/homebrew/opt/libjpeg-turbo/lib -L/usr/local/homebrew/opt/jpeg-turbo/lib -L/usr/local/lib -L/usr/local/homebrew/opt/libvorbis/lib -L/usr/local/homebrew/opt/openal-soft/lib -L. -lhl -lpng -lturbojpeg -lz -lvorbisfile
ld: library not found for -lpng
```

**Comment by tobil4sk** [comment]
Did you make sure to install all the dependencies?
https://github.com/HaxeFoundation/hashlink#building-on-linuxosx

**Comment by avrame** [comment]
yes, I ran `brew bundle` as is documented.

**Comment by tobil4sk** [comment]
Did you make sure to run `brew bundle` with the x86_64 build of homebrew?

**Comment by avrame** [comment]
yes

**Comment by tobil4sk** [comment]
https://github.com/HaxeFoundation/hashlink/blob/b5509c0c4f34dae8918d01dac22f9c42ceb186e8/Makefile#L95

Looks like the path for libpng is missing here? You could try adding it.

Alternatively, you could also try the makefile patches for M1 from this PR: https://github.com/HaxeFoundation/hashlink/pull/577/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52

**Comment by avrame** [comment]
Unfortunately, neither of those ideas worked. I get the same `ld: library not found for -lpng` error after adding the directory where libpng is.

And when using the branch in the PR I get this when running make:
```
Undefined symbols for architecture x86_64:
  "_ov_clear", referenced from:
      _ogg_finalize in fmt.o
  "_ov_info", referenced from:
      _fmt_ogg_info in fmt.o
  "_ov_open_callbacks", referenced from:
      _fmt_ogg_open in fmt.o
  "_ov_pcm_seek", referenced from:
      _fmt_ogg_seek in fmt.o
  "_ov_pcm_tell", referenced from:
      _fmt_ogg_tell in fmt.o
  "_ov_pcm_total", referenced from:
      _fmt_ogg_info in fmt.o
  "_ov_read", referenced from:
      _fmt_ogg_read in fmt.o
  "_png_image_begin_read_from_memory", referenced from:
      _fmt_png_decode in fmt.o
  "_png_image_finish_read", referenced from:
      _fmt_png_decode in fmt.o
  "_png_image_free", referenced from:
      _fmt_png_decode in fmt.o
  "_tjDecompress2", referenced from:
      _fmt_jpg_decode in fmt.o
  "_tjDestroy", referenced from:
      _fmt_jpg_decode in fmt.o
  "_tjInitDecompress", referenced from:
      _fmt_jpg_decode in fmt.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [fmt] Error 1
```

**Comment by avrame** [comment]
ok, I finally got it working. Thanks for your help @tobil4sk 
I did indeed need to add the libpng library dir to that line that sets `LIBFLAGS`, along with several others. In the end, this is what worked:

`LIBFLAGS += -L/usr/local/homebrew/opt/libjpeg-turbo/lib -L/usr/local/homebrew/opt -L/usr/local/homebrew/opt/jpeg-turbo/lib -L/usr/local/lib -L/usr/local/homebrew/opt/libvorbis/lib -L/usr/local/homebrew/opt/openal-soft/lib -L/usr/local/homebrew/opt/libpng/lib -L/usr/local/homebrew/opt/sdl2/lib -L/usr/local/homebrew/opt/mbedtls@2/lib -L/usr/local/homebrew/opt/libuv/lib`

I hope this is useful for anyone else with an arm64 Mac.
