### ISSUE TITLE
Bytecode version check always fails.

### ISSUE THREAD

**Issue by Yanrishatum** [HaxeFoundation/hashlink#62]
Commit c07d480d68a1b3c308a4800a7e29e36acf25a799 made changes to bytecode version check, resulting in always throwing error about unsupported bytecode version:  
https://github.com/HaxeFoundation/hashlink/blob/master/src/code.c#L434  
Shouldn't it be `if( c->version < 1 || c->version > 2 )`?
UPD: Oh, I just noticed `>2`, not `>=`, anyway, bytecode generated version 1 code, resulting in not executing.

**Comment by Simn** [comment]
That is indeed a funny way of saying `!=`.

I don't know if it's supposed to be 1 or 2 though.

**Comment by Yanrishatum** [comment]
@Simn Generated bytecode version is 1. And as I noted - commit checks for `X <= 1` and `X > 2`, obviously resulting in passing always. ;)

**Comment by ncannasse** [comment]
you need to use haxe git with hashlink git, which uses bytecode version 2 and successfully pass the check.  Previous code was erroring on <= 0 hence the somewhat strange code :)

**Comment by fzzr-** [comment]
[There is a problem.](https://travis-ci.org/HaxeFoundation/hashlink/jobs/227858782#L2091)

I think we need two branches on this repo:

- `master` - where CI uses release version of Haxe
- `develop` - where CI uses git-dev-haxe version.

@ncannasse What about back-capability?

**Comment by ncannasse** [comment]
@fzzr- I don't plan to maintain backward capability while HL is still in early stage, although I'm trying not to break things when possible

**Comment by ncannasse** [comment]
@andyli could you look at CI ?

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/41143543-3a6acbae-6b2c-11e8-9393-97431f7df877.png)

haxe nightbuild 6-8-2018
