### ISSUE TITLE
JIT ERROR 0 in Haxe unit tests

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/hashlink#63]
Steps to repro:

- comment out `-D interp` in `tests/unit/compile-hl.hxml` and run it to generate the `.hl`
- `hl tests/unit/bin/unit.hl`

Results in:

>JIT ERROR 0 (jit.c line 884)

Platform: Win10
HaxeFoundation/hashlink@6e27e0b
HaxeFoundation/haxe@4497a35

**Comment by Simn** [comment]
I managed to reproduce that as well with my compilation attempts.

Out of registers! :(

**Comment by ncannasse** [comment]
Should be ok now

**Comment by Simn** [comment]
That error is gone, but the tests still don't quite pass yet:

```
TestMain.hx:37: Generated at: 2017-05-12 12:33:59
TestMain.hx:39: START
Test.hx:275: ABORTED : Can't perform dyn op f64 % i32 in unit.TestOps.testOps
Test.hx:278: STACK :

Called from unit.TestOps.testOps (unit/TestOps.hx line 70)
Called from $Reflect.callMethod (C:\GitHub\haxe\std/hl/_std/Reflect.hx line 85)
Called from unit.$TestMain.main (unit/TestMain.hx line 127)
Called from unit.$TestMain.main (unit/TestMain.hx line 126)
Called from unit.$TestMain.main (unit/TestMain.hx line 111)
Test.hx:221: DONE [6832 tests]
Test.hx:222: SUCCESS: false
```
