### ISSUE TITLE
Recent change breaks hashlink builds.

### ISSUE THREAD

**Issue by NitroPlum** [HaxeFoundation/hashlink#637]
Two people have tried building hashlink and when you try to run it, we get the following error :
`src/module.c(574) : FATAL ERROR : Invalid signature for function fmt@mp3_open : PBi_Xfmt_mp3_ required but P_Xfmt_mp3_ found in hdll`

We purposefully reverted the changes from this commit and it works afterwards: https://github.com/HaxeFoundation/hashlink/commit/102f09be3f02824beda093680f855ba06a1c871c

**Comment by ncannasse** [comment]
The change requires https://github.com/HeapsIO/heaps/pull/1175

**Comment by NitroPlum** [comment]
@ncannasse I think you misundertood. As of now, if you pull master and build hashlink, it will build. However the resulting hashlink will not work when you try to run it. If you undo these changes and build, it works great. https://github.com/HaxeFoundation/hashlink/commit/102f09be3f02824beda093680f855ba06a1c871c

**Comment by ncannasse** [comment]
I understand well. You need to patch heaps so it works with latest hashlink.
