### ISSUE TITLE
The Hashlink GC can block the main thread if sys.thread.Thread is used

### ISSUE THREAD

**Issue by LostBranch5502** [HaxeFoundation/hashlink#655]
On Linux and Hashlink, sys.thread.Thread can block the entire program. This can most easily be observed on a graphical program like the Heaps Base2D sample (since for some reason the `trace` function momentarily unblocks threads, this issue is difficult to demonstrate on a command line program).

I have observed the issue on both OpenFL and Heaps programs. The test program below is based on the Heaps Base2D sample and will start a number of background threads when the Enter key is pressed. These threads will then block the execution of the main loop, resulting in the graphical display of the rotating logos being stuck in one frame until the background threads have finished.

The expected correct behaviour would be for the logos to continue rotating without pause even while the background threads are running.

**Test environment**

* Haxe: 4.3.3
* Hashlink 1.14.0 (commit 20df6529c932f7e9ab4e1c528a0321723f2d09ae)
* Operating System: Ubuntu Linux 20.04.6 LTS (64-bit)

**A temporary solution**

The issue is somehow caused by the garbage collector. If I block the gc in `gc_thread_entry`, the problem goes away and the test program runs smoothly:

```C
#ifdef HL_THREADS
static void gc_thread_entry( thread_start *_s ) {
	thread_start s = *_s;
	hl_register_thread(&s);
	hl_lock_release(_s->wait);
	s.wait = _s->wait = NULL;
	_s = NULL;
	hl_blocking(true); // Line added for example
	s.callb(s.param);
	hl_blocking(false); // Line added for example
	hl_unregister_thread();
}
#endif
```

However, this is probably not a good solution, since background threads can potentially run for a long time, and suspending garbage collection for all that time might cause other issues.

Related to this issue, I have observed the following behaviours, which may or may not be relevant:

**The problem is not consistent**

Sometimes starting a thread blocks the whole program, sometimes not. If more than one background threads are run at the same time (as with the three threads in the test program), it is almost certain that at least one thread will block the entire program. I assume this is because the garbage collector runs on its own schedule.

**Neko threads do not block**

I originally observed this issue on OpenFL. Since OpenFL programs can be compiled for both Hashlink and Neko, I tested the same OpenFL program also on Neko, and with Neko the background threads never block the rendering. Looking at both Neko `vm/threads.c` and the Hashlink `std/thread.c` code, might there be something the Boehm GC does that avoids this issue?

**Calling trace can partially unblock threads**

Some functions like `trace` can cause the render loop to be partially unblocked. If the background thread calls `trace` every few seconds, the render loop can stutter along at corresponding intervals. Nevertheless, the progress of the foreground and background threads remain abnormally connected.

**The test program**

The test program was compiled (for the VM) with the following command: `haxe -lib heaps:2.0.0 -lib hlsdl -lib format -hl test.hl -main Main`. The issue affects both the VM and the compiled C versions.

```haxe
import hxd.Key;
import sys.thread.Thread;

class Main extends hxd.App
{
	var obj : h2d.Object;
	var tf : h2d.Text;

    public function new()
    {
        super();
        hxd.Window.getInstance().addEventTarget(onEvent);
    }

    // Threads ////////////////////////////////////////////////////////////////

    static function startWorker(name:String, duration:Float)
    {
        Thread.create(() -> worker(name, duration));
    }

    static function worker(name:String, duration:Float)
    {
        trace('Starting worker $name');
        var startTime = Sys.time();
        var elapsedTime = 0.0;
        while (elapsedTime < duration)
            elapsedTime = Sys.time() - startTime;
        trace('Stopping worker $name');
    }

    function onEvent(event : hxd.Event)
    {
        switch(event.kind) {
            case EKeyUp:
                if (event.keyCode == Key.ENTER)
                    trace('Adding workers');
                    startWorker('A', 20);
                    startWorker('B', 20);
                    startWorker('C', 20);
            default:
        }
    }

    // Base2D /////////////////////////////////////////////////////////////////

	override function init() {
		// creates a new object and put it at the center of the sceen
		obj = new h2d.Object(s2d);
		obj.x = Std.int(s2d.width / 2);
		obj.y = Std.int(s2d.height / 2);

		// load the haxe logo png into a tile
		var tile = hxd.Res.hxlogo.toTile();

		// change its pivot so it is centered
		tile = tile.center();

		for( i in 0...15 ) {
			// creates a bitmap into the object
			var bmp = new h2d.Bitmap(tile, obj);

			// move its position
			bmp.x = Math.cos(i * Math.PI / 8) * 100;
			bmp.y = Math.sin(i * Math.PI / 8) * 100;

			// makes it transparent by 10%
			bmp.alpha = 0.1;

			// makes the colors adds to the background
			bmp.blendMode = Add;
		}

		// load a bitmap font Resource
		var font = hxd.Res.customFont.toFont();

		// creates another text field with this font
		var tf = new h2d.Text(font, s2d);
		tf.textColor = 0xFFFFFF;
		tf.dropShadow = { dx : 0.5, dy : 0.5, color : 0xFF0000, alpha : 0.8 };
		tf.text = "Héllò h2d !";

		tf.y = 20;
		tf.x = 20;
		tf.scale(7);
	}

	// if we the window has been resized
	override function onResize() {

		if( obj == null ) return;

		// center our object
		obj.x = Std.int(s2d.width / 2);
		obj.y = Std.int(s2d.height / 2);

		// move our text up/down accordingly
		if( tf != null ) tf.y = s2d.height - 80;
	}

	override function update(dt:Float) {
		// rotate our object every frame
		if( obj != null ) obj.rotation += 0.6 * dt;
	}

	static function main() {
		hxd.Res.initEmbed();
		new Main();
	}

}
```

**Comment by ncannasse** [comment]
Hi,

This works as intended by design.

In order for the threads to collaborate wrt garbage collection, when a collection is required we will wait for all the threads to be ready until we start marking and collecting. This means that we might wait for some thread if he's in a long calculus and does not perform any memory allocation. You can add some regular calls that will do hl_blocking() calls to prevent this from happening, I think for instance Sys.sleep(0) should work.

Hope that helps
