### ISSUE TITLE
Make HL Bytecode as executable (like `nekotools boot`)

### ISSUE THREAD

**Issue by Yanrishatum** [HaxeFoundation/hashlink#66]
While HL does compiles to C executable, it's currently not possible to simply make .hl file as executable file which depends on pre-installed HL in the system.
I request feature of making executable for .hl bytecode which should run the installed HashLink.
Neko already have such feature via `nekotools boot` utility, which were pretty convenient when executable file output were required but compilation time weren't as long as for C++.

**Comment by andyli** [comment]
The existing `nekotools boot ...` implementation is problematic... See https://github.com/HaxeFoundation/neko/issues/130
Unless we have a way to generate a "proper" binary on all major platform, using a c compiler is the right way to go.

**Comment by ncannasse** [comment]
We already discussed how to properly embed HL bytecode in executable with
@pperidont in the meanwhile you can simply name your hl file as hlboot.dat
and the hl.exe will start it automatically

**Comment by ppenzin** [comment]
Would it be, in theory, possible to produce object files from HL bytecode?

LLVM has support for garbage collection and hashlink might be a good target to translate to LLVM.

**Comment by ncannasse** [comment]
@ppenzin you can already generate C files from HL and compile them to native using any C compiler

**Comment by ncannasse** [comment]
Closing this, as I have no time for it.
