### ISSUE TITLE
--debug is faster to run than non debug.

### ISSUE THREAD

**Issue by onehundredfeet** [HaxeFoundation/hashlink#662]
I'm finding a very odd behaviour where I'm finding the same code with --debug is running about 1/6th (approx 15%) faster than without.  This is the opposite of what I would expect.  

I've tried both hashlink and hl/c.  I have no idea why --debug would be faster.  This is the only switch I am changing.

Any ideas? I'm happy investigating, but it seems to be broadly distributed across all routines, rather than a single routine taking longer.

**Comment by ncannasse** [comment]
That's very weird as --debug shouldn't change much HashLink output. You can
compare the dump/hlcode.txt with -D dump

Le sam. 16 mars 2024 à 14:45, Ryan Cleven ***@***.***> a
écrit :

**Comment by ncannasse** [comment]
You can compare bytecode output with -D dump=pretty then look at dump/hlcode.txt
