### ISSUE TITLE
src/module.c(567) : FATAL ERROR : Failed to load function sdl@gl_polygon_offset

### ISSUE THREAD

**Issue by unerr** [HaxeFoundation/hashlink#675]
I tried to install GameBase. I launched `haxe setup.hxml`. Then I tried to launch `haxe build.opengl.hxml`. It workes fine but when I try to launch `hl bin/client.hl` it gives me the error: `src/module.c(567) : FATAL ERROR : Failed to load function sdl@gl_polygon_offset`. Hashlink worked fine before but I do not know what is happening now.

Haxe version: 4.3.3.
HL/JIT: 1.14.0
OS: Arch Linux

**Comment by unerr** [comment]
I solved it by removing all libraries that I had in haxelib storage file. I guessed that there's a problem exactly there. And I was right

**Comment by wihu** [comment]
I think I managed to do that as well, however, I got segmentation fault, but I guess that is another issue with M1, hashlink does not support arm64 at the moment apparently, so I need to rebuilt all the libs in x86_64 instead. Thanks anyway!
