### ISSUE TITLE
Arguments misbehaving on nightly

### ISSUE THREAD

**Issue by Geokureli** [HaxeFoundation/hashlink#694]
Looks like `foo(false, true, true, false)` actually passes `(false, true, true, true)` for some reason, but only with static functions

This should recreate the issue:
```hx
class Test
{
	static function main()
	{
		new HLArithTest().create();
	}
}

class HLArithTest// extends flixel.FlxState
{
	public function new () {}
	
	//override
	public function create()
	{
		// only true in nightly HL
		trace(checkDownStatic(false, true, true, false));
		
		// no issues
		trace(checkDownInstance(false, true, true, false));
	}
	
	public static function checkDownStatic(left:Bool, right:Bool, up:Bool, down:Bool)
	{
		return down;
	}
	
	public function checkDownInstance(left:Bool, right:Bool, up:Bool, down:Bool)
	{
		return down;
	}
}
```

small note, my actual test was in an instance of a class extending FlxState, but I'm sure this will repro, just the same

**Comment by Apprentice-Alchemist** [comment]
Appears to be caused by https://github.com/HaxeFoundation/hashlink/commit/068bb35f826133bc3022279a05d9b9dd9e2489e4
