### ISSUE TITLE
I have a question!

### ISSUE THREAD

**Issue by XiaJack** [HaxeFoundation/hashlink#719]
![image](https://github.com/user-attachments/assets/460773e8-9a69-497e-870b-2979370e8d87)
That's why?

**Comment by tobil4sk** [comment]
Looks like you are missing the hl binary from PATH. You have to install the hashlink binaries and add to the user/system `PATH` variable.

**Comment by XiaJack** [comment]
> Looks like you are missing the hl binary from PATH. You have to install the hashlink binaries and add to the user/system `PATH` variable.

yes, thank you,I've solved it

**Comment by yuxiaomao** [comment]
Next time for basic questions, you can ask in haxe/heaps discord server, you'll probably have quicker response there

**Comment by XiaJack** [comment]
> Next time for basic questions, you can ask in haxe/heaps discord server, you'll probably have quicker response there. And please try to add more information in the title x)

@yuxiaomao Are You Chinese too? Can you add a friend？
