### ISSUE TITLE
[NIGHTLY?] Array getDyn broken

### ISSUE THREAD

**Issue by NeeEoo** [HaxeFoundation/hashlink#723]
Unsure if this also happens in base hashlink since theres no mac build for the stable release.

but

```hx
var hello = [];
trace(hello[hello.length - 1]); // crash
```

```
hl.types.ArrayDyn.getDyn(/Users/neo/.haxeget/std/hl/types/ArrayDyn.hx:62)
$Main.main(Main.hx:13)
.init(?:1)
```

haxe version: 4.3.4
hashlink version: 1.14.0

**Comment by yuxiaomao** [comment]
As hello is empty, `hello.length - 1` gives `-1`, and docs https://haxe.org/manual/std-Array.html says: 

> If a write access is made with a negative index, the result is unspecified.

Tested on my machine with latest haxe and hashlink, it gives access violation. This behavior is expected. You may not have access violation all the time but it's just unspecified.

**Comment by Apprentice-Alchemist** [comment]
Looking at the code for `ArrayObj.getDyn` it looks like returning `null` is the intended behavior, except that comparing `UInt` and `Int` generates OJSLt instead of OJULt.

**Comment by yuxiaomao** [comment]
(You're tagging the wrong people xD, there's another yuxiao s on github!)
Thank you for the tips, will check!
