### ISSUE TITLE
Nighlty builds

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/hashlink#73]
Is it possible to setup nightly builds just like compiler nightlies?
I think that will allow people to avoid all issues they have on Linux and OSX trying to build hashlink manually.

**Comment by ncannasse** [comment]
We need to fix our CI first (ping @andyli) then see if @waneck can help with it. Given that we do that already for Neko it shouldn't be that hard.

**Comment by andyli** [comment]
CI is green at the moment.

**Comment by waneck** [comment]
Just let me know what files we should submit and I'll set it up

**Comment by ncannasse** [comment]
Ah good :) I don't know where the build files are located but for a full distrib we need:

- hl binary (.exe in windows)
- libhl (.so or .dll depending on target)
- *.hdll files
- we might want to include some binaries on Windows so the package does not need any extra install (SDL2.dll, OpenAL32.dll -- openal soft version, vs_redist.x86.exe)
- sources necessary to build hl/C : hlc_main.c , hl.h, hlc.h  (+.lib files on windows)

You can check my windows distribution here for an example 
https://github.com/HaxeFoundation/hashlink/releases

**Comment by waneck** [comment]
Do we have hashlink builds setup on AppVeyor for windows? It would be nice if we had a `make release` that would at least copy all the relevant files. But I'll take a look into this tonight

**Comment by RealyUniqueName** [comment]
What about hlsdl and friends? Should they also be in nightlies?

**Comment by ncannasse** [comment]
@waneck Appveyor is green, can we setup the nightly ? :)

**Comment by ncannasse** [comment]
@waneck up :)

**Comment by nadako** [comment]
Note that I did set up build artifacts on appveyor: https://ci.appveyor.com/project/HaxeFoundation/hashlink/build/498/job/ih1ilw6fkfaagmjq/artifacts

**Comment by ncannasse** [comment]
Anyone up to setup nightly builds ? :) @waneck @andyli

**Comment by ncannasse** [comment]
Ping again @andyli  :)

**Comment by thomasjwebb** [comment]
This would be useful to have. I'm trying to add hashlink to a docker config so it would be better to have it download and install something than try to build it.

**Comment by thomasjwebb** [comment]
I ended up just having docker compile and install but in general it would be useful to have builds and ultimately packages.

**Comment by Simn** [comment]
I'm told that this can be closed now!
