### ISSUE TITLE
OpenAL jack disconnect

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hashlink#78]
Under Windows 10, OpenAL stops working if you unplug the jack and plug it again.
You get the following trace in console:

`AL lib: (EE) ALCmmdevPlayback_mixerProc: Failed to get padding: 0x88890004`

**Comment by ncannasse** [comment]
ping @pperidont @mcapdegelle

**Comment by ncannasse** [comment]
@mcapdegelle has this been fixed by chance by a recent commit?

**Comment by lunarcleint** [comment]
any chance someone found the issue? I want to fix this too

**Comment by eliottness** [comment]
Got the same issue
