### ISSUE TITLE
hashlink on ARM devices?

### ISSUE THREAD

**Issue by bentxt** [HaxeFoundation/hashlink#85]
This is simply a question. What does it take to port the hl/c backend to ARM (android/ios) devices?

**Comment by ncannasse** [comment]
We have confirmed that hashlink + heaps combination successfully run on
various ARM cpus, and on Android and iOS as well, so nothing to be ported
in particular.

**Comment by ncannasse** [comment]
Please note that it's using HL/C
HL/JIT is not supported on ARM CPUs.
