### ISSUE TITLE
FileSystem.readDirectory returns chinese characters on mac

### ISSUE THREAD

**Issue by josuigoa** [HaxeFoundation/hashlink#87]
[Here](https://github.com/josuigoa/hl-readDir-issue) is test project that give me that behaviour, if you want to try. I put two screenshots to resume:

on windows works fine
![windows](https://raw.githubusercontent.com/josuigoa/hl-readDir-issue/master/win.png)
on mac, neko is working fine but HL returns those characters
![mac](https://raw.githubusercontent.com/josuigoa/hl-readDir-issue/master/mac.png)

**Comment by ncannasse** [comment]
I think it's the same as https://github.com/HaxeFoundation/hashlink/commit/00ada9091c02672f53522216e8d50f365dab7956 , so it should be fixed already, reopen either.
