### ISSUE TITLE
Unsupported bytecode version

### ISSUE THREAD

**Issue by r3d9u11** [HaxeFoundation/hashlink#98]
Hi. I tried to run minimal sample, but got runtime exception.
Main.hx:
```
class Main {
	public static function main () trace(123);
}
```
build:
```
$ haxe -hl output.hl -main Main
$ ../hashlink-1.4/hl output.hl
VER=1
Unsupported bytecode version
```

Linux Mint 18.3 x64
Haxe 3.4.4
hashlink 0.1.0
HL/JIT 1.4.0

What I'm doing wrong?
Thanks.

**Comment by ncannasse** [comment]
You need Haxe nightly build from http://build.haxe.org to compile for HL 1.4

**Comment by flamendless** [comment]
Hi, im having this issue as well.I have haxe 3.4.7 and hashlink 1.8, i get
```
VER=1
Unsupported bytecode version
```

**Comment by ncannasse** [comment]
@flamendless you need to use haxe-preview 5 with HL 1.8

**Comment by flamendless** [comment]
ive used haxe 4.0 preview 5, when compiling a compile.xml, i get this error
`File "_build/src/context/common.ml", line 410, characters 21-27: Assertion failed haxe`

**Comment by flamendless** [comment]
> Most likely you're using preview 5 binaries with 3.x std library...

im compiling from the branch `4.0.preview.5`, i get into this error when i run `make`
```
arning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
HFinal
File "src/typing/type.ml", line 1506, characters 41-55:
Error: This expression has type Ast.placed_access list
       but an expression was expected of type Ast.access list
       Type Ast.placed_access = Ast.access * Globals.pos
       is not compatible with type Ast.access 
make[1]: *** [Makefile:313: _build/src/typing/type.cmx] Error 1
make[1]: Leaving directory '/home/brbl/Softwares/haxe/haxe'
make: *** [Makefile:139: haxe] Error 2

```
